### ISSUE TITLE
Progression path for Netherite mesh

### ISSUE THREAD

**Issue by thaimichael** [AllTheMods/atm6-sky#1]
Currently, the netherite mesh is made by upgrading the diamond mesh. Iron > Diamond > Netherite.
The emerald mesh is currently a dead end upgrade.  Iron > Diamond > Emerald no path to Netherite
Recipes:
Iron mesh > Diamond mesh > Netherite mesh
and as an alternate recipe allow the upgrade of emerald
Iron mesh > Diamond mesh > Emerald mesh > Netherite mesh

**Describe alternatives you've considered**
The other alternative would be to remove the Diamond mesh > Netherite mesh recipe
Require the emerald mesh as part of the upgrade path
Iron mesh > Diamond mesh > Emerald mesh > Netherite mesh
Since the drop chance for Emeralds with iron mesh is the same as diamond drop rate may want to consider tweaking the percentage of drop for emeralds lower with iron mesh or require diamond mesh for them to drop,

**Comment by SpuSpu** [comment]
Isn't the current use of emerald and netherite meshes useless? Since they have the same drop rates as diamond and durability for meshes is turned off in the config.

**Comment by hadeedsarfaraz** [comment]
Perhaps upping rates for netherite? and making emerald just add the specific special drops? So to get the items beyond diamond you go emerald and you then upgrade to netherite to make everything have higher chances?

This assumes you go Iron mesh > Diamond mesh > Emerald mesh > Netherite mesh
