### ISSUE TITLE
Things just stop

### ISSUE THREAD

**Issue by Chocopuffs** [AllTheMods/atm6-sky#10]
**So, people have reported that pedestals just randomly stop working for no reason, I thought this was specific to pedestals so I kinda just left it. But now I'm using AE to store things, I've noticed it happen with this mod as well... So instead of using AE crafting, I export the items into an rftools crafter, crafts it, then imports back into AE, then exports out into storage drawers. Randomly it'll just stop exporting into the rftools crafter, we'll come back with essence all through our system, then I'll put one stack of anything needed to craft, and then it boots back up again and starts sending all the essence again.**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by WhitePhant0m** [comment]
havent been able confirm this, will close, open again if still happens
