### ISSUE TITLE
possible Quest Task/Reward error

### ISSUE THREAD

**Issue by GamerXD8991** [AllTheMods/atm6-sky#101]
**Describe the bug**
In the Tech section the "Tiered Storage" Quest is Checkmark with Reward Furnator (Starter) while the 2 quest before have Thermal Generator (Starter) and Magmator (Starter) as Task with empty reward. I assume the quest should have followed the same pattern but got mixed up.

**To Reproduce**
1. Go to Tech Section
2. Follow the Powah! generator quest line till the end
3. notice that something could be wrong

**Expected behavior**
see intro text

**Additional context**
And by the way why does a "Storage" Quest doesn't requiere the player to craft a storage block but a generator?

**Comment by oly2o6** [comment]
@Thunder-Nova
