### ISSUE TITLE
Bigger reactor inside Compact Machine

### ISSUE THREAD

**Issue by cwilkinsvi** [AllTheMods/atm6-sky#104]
Pack Version 1.0.5.

Bigger reactor set up in a compact machine, tested in the max size compact machine. When you leave the compact machine, all data on bigger reactor is cleared. When you go back in, it no longer has fuel/waste, no energy, and reactor is turned back off. Have to remain in the compact machine for the reactor to run.

**Comment by RogueLogix** [comment]
Unable to reproduce with biggerreactors-0.5.0-indev.9c4a53b and compactmachines-4.0.0-beta.2

**Comment by oly2o6** [comment]
this is a mod issue and should be reported to the author instead of us
