### ISSUE TITLE
Pipez energy pipe not extracting from redstone flux cell

### ISSUE THREAD

**Issue by Daschi1** [AllTheMods/atm6-sky#105]
**Describe the bug**
Since version `1.0.5` the energy pipes from pipez won't extract energy from a redstone flux cell (from Thermal) anymore. 

**To Reproduce**
1. Place a redstone flux cell (filled of course)
2. Configure its output to a side
3. Connect a pipez energy pipe to the side
4. Configure the pipe to extract
5. Connect it to any machine
6. No energy is getting transmitted

**Expected behavior**
I expect energy to be transmitted.

**Additional context**
Worked in every version below `1.0.5`, since I upgraded it did not work anymore. Filling the cell functions still though.

**Comment by oly2o6** [comment]
apparently its just a visual bug, if not this is a mod issue and should be reported to the author instead of us
