### ISSUE TITLE
Integrated Dynamics Mechanical Squeezer Does Not Produce Lava from Netherrack

### ISSUE THREAD

**Issue by DizzyDJW** [AllTheMods/atm6-sky#109]
**Describe the bug**
As title states, the Mechanical Squeezer says it can produce a single bucket of lava from a block of Netherrack but instead it crushes it into Crushed Netherrack, which is a useless feature as the hammers can do it much faster for much less resources and energy cost.

**Expected behavior**
Placing Netherrack in a Mechanical Squeezer should get you a bucket of Lava after about 40secs.

**Comment by oly2o6** [comment]
there are multiple ways to create lava, but this is a mod issue and should be reported to the author instead of us

**Comment by DizzyDJW** [comment]
> there are multiple ways to create lava, but this is a mod issue and should be reported to the author instead of us

No. Absolutely not. You can't just lazily close a ton of issues and say it's somebody else's problem. This one is specifically an issue in this modpack. Quite an easy one to fix too. Simply remove the recipe that some other, (most likely Ex Nihilo) is forcing upon the Mechanical Squeezer. It's really not that hard. 

Sounds like the Modpack Author didn't remove that one thing. Not an issue for some other mod author.
