### ISSUE TITLE
Server Ping Issue

### ISSUE THREAD

**Issue by Seniorendi** [AllTheMods/atm6-sky#110]
**Describe the bug**
When I want to ping my Minecraft Server in the Multiplayer Server list in-game, the server is marked as offline.
But I can join the Server without any issue.
And the Server throws this Stacktrace when I want to ping it: https://gist.github.com/Seniorendi/ad8b1daca41d0a3df73d9a653710b8f7

I have this issue since 1.0.5

The Server runs on an BisectHosting Premium Server(if necessary) with 8 GB Memory.

**To Reproduce**
1.  Starting the Server and the Game
2. Click on `refresh` at the multiplayer window
3. The Server is marked as offline.

**Expected behavior**
No problem with the ping and the server should be marked as online.

**Comment by oly2o6** [comment]
unsure whats going on here, going to get this looked into still even though i am closing it
