### ISSUE TITLE
No Nether fortresses spawning bug or did I do something wrong?

### ISSUE THREAD

**Issue by Ringmaster500** [AllTheMods/atm6-sky#111]
I've explored a 2000-3000 diameter square and cannot find a fortress, I've also tried the /locate fortress command and it cant find one either, I've checked my world settings and generate structures is on, is there any way I can fix this?

**Comment by tyler489** [comment]
They spawn in the other dimention

**Comment by sweetlew20** [comment]
I had them spawning in both the nether and the other.
