### ISSUE TITLE
Energy pipes from the Pipez mod do not draw power from Flux Points

### ISSUE THREAD

**Issue by Pwapy** [AllTheMods/atm6-sky#112]
Energy pipes from the Pipez mod do not draw power from Flux Points

1. Properly set up flux network with the flux point mod
2. attach flux point to energy pipe from pipez mod
3. set energy pipe to pull

**Expected behavior**
The energy pipe should be drawing power from the flux plug 

**Additional context**
The flux network is properly set up. When the flux point is attached directly to a machine it recieves power.

**Comment by Aho-Senpai** [comment]
https://discord.com/channels/254530689225981953/818252878115766322/826145341534634055

**Comment by andremiller** [comment]
Possibly related to https://github.com/henkelmax/pipez/issues/16

**Comment by oly2o6** [comment]
this is a mod issue and should be reported to the author instead of us
