### ISSUE TITLE
Steel Block Types and IE Multiblocks

### ISSUE THREAD

**Issue by pbutternj** [AllTheMods/atm6-sky#114]
**Describe the bug**
All of the immersive engineering multiblocks that require steel blocks cant be created because the mekanism steel block that is the only available block does not count. Also Immersive engineering's steal block looks so much better

**To Reproduce**
Build a Bucket Wheel or other IE or IP multiblock that uses steel blocks and using a projector the block shows as an error and will not build

**Expected behavior**
Mekanism Steel block does not work for Immersive engineer multiblocks such as the Bucket Wheel for the excavator

**Comment by MelanX** [comment]
Similar solution as here: https://github.com/AllTheMods/atm6-sky/issues/222
