### ISSUE TITLE
Vibranium and unobtanium is not possible to make Alloy ingot. Anyone even noticed?

### ISSUE THREAD

**Issue by VersioniX** [AllTheMods/atm6-sky#119]
(sorry for the bad English, I'm in hurry)
So I have so many Ingot also vibr. and unob. and I cannot make alloy... Please anyone help. It is a bug or sth?

**Comment by DrMrPotatoe** [comment]
What dragon forge are u uding

**Comment by VersioniX** [comment]
> What dragon forge are u uding

I don't use any Dragon forge... That's problem? Any alternative?

**Comment by VersioniX** [comment]
> > > What dragon forge are u uding
> 
> > 
> 
> > I don't use any Dragon forge... That's problem? Any alternative?
> 
> 
> 
> Check the recipe for the alloy ingot using jei

JEI is not showing any recipes... I think the crafting recipes of the alloys is not in the game... It think its missing

**Comment by Vertigo81** [comment]
That's odd then.  They show up fine for me, each of them uses a Dragon forge (that I haven't figured out how to use yet, nor seen a dragon, but there are definitely recipes)

**Comment by Pdiddy973** [comment]
Recipes do show using a dragon forge, you will need to look at different tabs in JEI to see it. You can find dragons in the other.
