### ISSUE TITLE
Increase dragon Spawn rate

### ISSUE THREAD

**Issue by tyler489** [AllTheMods/atm6-sky#120]
Tier 5 Dragons are VERY RARE

**Describe the solution you'd like**
Decrease the "distance between dangerous structure" in the ice and fire configs or increase the number of biomes they are in... or make the biomes bigger.

**Additional context**
our other world size for 5 players on the server i was playing on was 1.5 GIGS and we had yet to find a t5 dragon... This is INSANE

**Comment by chulund** [comment]
by rare so I assume you're able to find one? I've been looking for several hours in The Other and still no luck in finding some dragons. I've checked the underground and above the ground and 40k+ from spawn. I've also tried to change the biome setting in the config and still can't get the dragon to spawn.

**Comment by oly2o6** [comment]
we removed some of the un-used dragons so this should be better in 1.0.6

**Comment by tyler489** [comment]
> we removed some of the un-used dragons so this should be better in 1.0.6

What do you mean by "unused". arnt they all used to make a certain alloy?
