### ISSUE TITLE
Mob Imprisonment Tool and Easy Villager Conflict

### ISSUE THREAD

**Issue by pbutternj** [AllTheMods/atm6-sky#123]
**Describe the bug**
You cannot pick up villagers anymore with the mob imprisonment tool because its the same interaction as easy villagers pick up interaction. There is a key bind option for easy villagers to pick up already so the duplicate control is not needed. Using the mob duplicator with villagers is now impossible.

**To Reproduce**
Using a mob imprisonment tool shift click on a villager and it will go into your inventory instead of into the imprisonment tool.

**Comment by oly2o6** [comment]
this is a mod issue and should be reported to the author instead of us

**Comment by MaxGivno** [comment]
There is a config file option in `config/easy_villagers-client.toml` for sneaking and right-clicking. Disabling it fixes the issue.
