### ISSUE TITLE
Problems With The End Dimension

### ISSUE THREAD

**Issue by john13210** [AllTheMods/atm6-sky#124]
In Earlier versions Ender Dragon didnt spawn at all but dimension was acting up like it was alive so Exit Portal wasnt open and now in version .5 i wiped it and no Ender Dragon and Exit Portal didnt even generate , this was on a server so idk if this can happen on single player

example : https://imgur.com/a/YwIGX3j

**Comment by oly2o6** [comment]
closing in favour of #134
