### ISSUE TITLE
Refined Storage Wireless Receiver Disappearing

### ISSUE THREAD

**Issue by Jacobus619** [AllTheMods/atm6-sky#125]
**Describe the bug**
When going into a Compact Machine and coming back out, Refined Storage's Network Receiver disappears from the world.

**To Reproduce**
1. Place down 'wireless receiver'
2. Go into compact machine 
3. Leave compact machine

**Expected behavior**
Wireless receiver and transmitter will transport items between dimensions

**Comment by Jacobus619** [comment]
Also: It only disappears after you have linked the network card and then put the linked network card in the transmitter from the compact machine.

**Comment by oly2o6** [comment]
this is a mod issue and should be reported to the author instead of us
