### ISSUE TITLE
Every Login Must Break and Replace Refined Storage External Storage to Storage Drawers inside Compact Machine

### ISSUE THREAD

**Issue by DizzyDJW** [AllTheMods/atm6-sky#127]
**Describe the bug**
Every time I log out and log back in, none of the items stored inside the Storage Drawers inside the Compact Machine show up in Refined Storage, unless I go back into the Compact Machine and break and replace the External Storage cable.

**To Reproduce**
1. Make Compact Machine (Chunk Loaded)
2. Put Storage Drawers inside Compact Machine
3. Fill drawers with items
4. Set up Refined Storage and Wireless Network inside Compact Machine
5. Attach an External Storage to Drawer Controller inside Compact Machine
6. Log out and back in
7. See no items in Refined Storage

**Expected behavior**
Pretty obvious what's expected to happen here.

**Comment by Jacobus619** [comment]
Refined Storage seems to act strange in compact machines. My network receiver disappears after I link it to a transmitter in a compact machine every time.

**Comment by oly2o6** [comment]
this is a mod issue and should be reported to the authors instead of us
