### ISSUE TITLE
Quark Dragon Scales not Ore Dictionaried with Other Dragon Scales Can't Craft Elytra, Quark Dragon Scales Don't Exist

### ISSUE THREAD

**Issue by DizzyDJW** [AllTheMods/atm6-sky#128]
**Describe the bug**
Basically Quark Dragon Scales are impossible to obtain. Making the Elytra also impossible to obtain.

**Comment by Eugene21040** [comment]
I killed 2 dragons in the end with 2 dragons dropped an item,  Try more

**Comment by Vertigo81** [comment]
How did you spawn your second one?  I can't seem to.

**Comment by oly2o6** [comment]
closing in favour of #134
