### ISSUE TITLE
Unlimited Energy single hightier Block

### ISSUE THREAD

**Issue by tenshiamon** [AllTheMods/atm6-sky#129]
**Describe the bug**
Bug was found on server with few buddies. Involving Mekanism Universal Cabling and Environmental Tech FE Output (IO Block). Only the block is needed and is generating power.

**To Reproduce**
1. Create any Tier Environmental Tech FE Output (IO Block) and connect Mekanism Universal cabling to 1 or multiple sides. More sides connected more energy.
2. Set Mekanism Cable to Pull Function and it will pull energy out of nowhere. No Solar Panel Needed. Block was never used with Void Miner and bug found due to being used for Solar.
3. This has been tested multiple ways on server even using Flux Network which the bug could not replicate. UNLESS we connected the Mekanism cabling first and used the flux for wireless transfer. 

**Expected behavior**
Structure should still be needed to generate power bug is between Mekanism and Environmental Tech blocks. Informing of bug found. Removing Solar again will not be the issue since FE IO Output block was available to add to void miner as well.

**Comment by oly2o6** [comment]
this is a mod issue and should be reported to the author instead of us
