### ISSUE TITLE
Ex Compressum recipes conflicting with Compressium

### ISSUE THREAD

**Issue by Kurunoa** [AllTheMods/atm6-sky#13]
I have crafters setup to compact dirt with Compressium recipes, to free up space in the RS.

Now the 9 'Dirt' -> 1 'Compressed Block of Dirt (1x)' recipe is making 'Compressed Dirt' from Ex Compressum.

**Comment by WhitePhant0m** [comment]
fixed in 8b0377efbdac20368da254ea110a3ca887fbbbd6

**Comment by WhitePhant0m** [comment]
Update to 1.0.2
Fixed in that version.
