### ISSUE TITLE
Disable Corail Tombstones' Soulbound

### ISSUE THREAD

**Issue by tyler489** [AllTheMods/atm6-sky#130]
**Describe the bug**
Corail Tombstone Soulbound is broken with Apotheosis's cursed enchanted

**To Reproduce**
If a player dies from Berserkers fury and their armor is soulbound the player will die twice (2 messages in chat) and their gear will be deleted. Ensorcellations soubound works correctly although the player still dies twice
**Expected behavior**
Not to lose Armor

**Comment by oly2o6** [comment]
this is a mod issue and should be reported to the author instead of us, will be patching around it on our side though

**Comment by tyler489** [comment]
https://www.curseforge.com/minecraft/mc-mods/corail-tombstone/issues/3 Already Did however they say its not their issue that their soulbound doesnt work... not sure if thats just a language barrier or what.
