### ISSUE TITLE
HELP!? Permanently stuck in sleeping animation!! 

### ISSUE THREAD

**Issue by DizzyDJW** [AllTheMods/atm6-sky#131]
**Describe the bug**
I tried using a sleeping bag in the Other and my character laid down and never got back up. I obviously tried "Esc" and the "Leave Bed" button, nothing works. I even used "/home" and he's still trapped in that same state.

**Expected behavior**
Using the sleping bag shouldn't trap your character in a perpetual animation with no way out.

**Screenshots**
![image](https://user-images.githubusercontent.com/26727521/113116844-d73e9400-91db-11eb-9b51-166ac265f655.png)

**Comment by tyler489** [comment]
did you try /kill

**Comment by oly2o6** [comment]
going to close this as i hope you have not spent 4days in the bed, that would be bad for you but please feel free to reopen an issue on this with more information (is it the other, is it a sleeping bag issue etc, try narrow this down) and then we can get it fixed

**Comment by DizzyDJW** [comment]
> going to close this as i hope you have not spent 4days in the bed, that would be bad for you but please feel free to reopen an issue on this with more information (is it the other, is it a sleeping bag issue etc, try narrow this down) and then we can get it fixed

"/kill" did work but it shouldn't have to be a workaround. Simply remove the ability to use beds or sleeping bags in the Other so others do not accidentally experience this same bug and have to kill themselves.
