### ISSUE TITLE
5x ore processing not working

### ISSUE THREAD

**Issue by Alsososcar** [AllTheMods/atm6-sky#132]
5x ore processing platinum goes to JAOPCA Slurry witch does nothing but all the mods platinum slurry does, so some problems there

![Screenshot 2021-03-31 141623](https://user-images.githubusercontent.com/54909507/113142875-b867ee00-922b-11eb-9f47-84ccf5cee7ee.png)

**Comment by DaRepe** [comment]
I have already posted this and made a fix for it at [https://github.com/AllTheMods/atm6-sky/issues/96](https://github.com/AllTheMods/atm6-sky/issues/96)
