### ISSUE TITLE
Dragon Spawns?

### ISSUE THREAD

**Issue by chupamane** [AllTheMods/atm6-sky#135]
I've looked in "The Other" for quite awhile and have not found a single dragon. I tried deleting the dimension and refreshing it, but still no dragons anywhere. I looked through the configs and searched specifically for the biomes they spawn in, but still no luck.

Anyone else not able to find dragons, or know a fix for this??
I'm not able to make the dragon forge without them. :(

**Comment by DizzyDJW** [comment]
Same here. Actually just spent hours traveling 30k blocks and checking the biomes listed in the config but not a single Ice&Fire mob at all aside from cockatrices and ghosts...
No Amphitheres, Stymphalions, or Dragons...

**Comment by oly2o6** [comment]
should be fixed now we removed un-needed dragons (cockatrices) from the other, delete the dimension to reset it and try in 1.0.6
