### ISSUE TITLE
Missing recipe: Tin Ore Chunk w/ Ore Crushing Hammer

### ISSUE THREAD

**Issue by lumi-jay** [AllTheMods/atm6-sky#137]
Missing the recipe for ore doubling with Tin Ore Chunk.
Expecting to get 2 dust by using the Ore Crushing Hammer from Engineer's Tools
Results in no possible crafting.

Maybe this is intended?

**Comment by MelanX** [comment]
Tin, Platinum, Zinc, Allthemodium, Vibranium, Unobtainium and Osmium are affected by this.
