### ISSUE TITLE
Two Osmium ores from KubeJS and from Ex Nihilo: Sequentia

### ISSUE THREAD

**Issue by starforcraft** [AllTheMods/atm6-sky#14]
There are 2 Osmium chunk pieces and 2 osmium ore chunks and they result the same ingot

Proof:
https://imgur.com/a/MnLkXdd
https://imgur.com/a/1YdHGy9

**Comment by ModernGamingWorld** [comment]
Yeah thats cause Ex Nihilo has a Mek addon that already adds Osmium Chunk, I am helping out the Ex Nihilo dev with some more add ons for Ex Nihilo

**Comment by jeremiahwinsley** [comment]
Addon wasn't supposed to be added, should be removed next update.

**Comment by WhitePhant0m** [comment]
Update to 1.0.2
Fixed in that version.
