### ISSUE TITLE
1.0.5 nether not void

### ISSUE THREAD

**Issue by VillyLane** [AllTheMods/atm6-sky#140]
Hey guys, 

i've tried deleting my nether dimension multiple times now and my nether keeps being created the normal way.

world was created in 1.0.2

so it was a gog world type

**Comment by MelanX** [comment]
I think the only solution would be to modify the level.dat file in your world.

**Comment by oly2o6** [comment]
yeah unfortunately melanx is correct, going to close this as its a bug due to an older version of the pack, modifying the level.dat is the only fix i have found for this
