### ISSUE TITLE
Need help with map crash

### ISSUE THREAD

**Issue by Grd100000** [AllTheMods/atm6-sky#141]
Hi, my map suddenly crashed for some reason and I can't figure out what happened.
I can't open it again and when it crashes it just says "Exit Code: 0", I can't find a crash log.
Here's my map in case anyone needs it.
The version is 1.0.5
[Grd100000World.zip](https://github.com/AllTheMods/atm6-sky/files/6246864/Grd100000World.zip)

**Comment by tyler489** [comment]
there should be a crash log in the crash report folder.

**Comment by oly2o6** [comment]
closing this due to no context/logs, also though this is a mod issue and should be reported to the author instead of us
