### ISSUE TITLE
Increase Thermo Generator (Nitro) Max Extract

### ISSUE THREAD

**Issue by stupex** [AllTheMods/atm6-sky#143]
A Thermo Generator (Nitro) heated with a Block of Blazing Crystal generates 13,440 FE/t but its max extract is only 10,000 FE/t

Solution: Edit Thermo Generator (Nitro) config to have a max extract above 13,440 FE/t

**Comment by starforcraft** [comment]
The Thermo Generator has 10k Output per **Side**. so just extract from 2 different sides.
