### ISSUE TITLE
Crash due to enchantment?

### ISSUE THREAD

**Issue by RStieber** [AllTheMods/atm6-sky#144]
Solo player world, running overnight -- server crashed and will not launch.  Looking at the crash reports, I think it's my mob farm with the Mob Grinder Utils Grinder.  I think a mob has an enchantment that has an "on-hit" effect, and that's causing the server to crash.  Any way to fix it?  Also looks like I don't have any backups generated, so I can't restore from an earlier version :(
[crash-2021-04-02_02.35.22-server.txt](https://github.com/AllTheMods/atm6-sky/files/6249654/crash-2021-04-02_02.35.22-server.txt)

**Comment by MacBurro** [comment]
Hey man, had the same problem with the FrostRebukeEnchantment and no backup. I recovered the save with NBTEditor and deleted the entity with the enchantment. hope it helps.

**Comment by RStieber** [comment]
> Hey man, had the same problem with the FrostRebukeEnchantment and no backup. I recovered the save with NBTEditor and deleted the entity with the enchantment. hope it helps.

I actually did the same, and disabled the enchantment in the configs as well. Still should be addressed though

**Comment by D3adCookie** [comment]
> > Hey man, had the same problem with the FrostRebukeEnchantment and no backup. I recovered the save with NBTEditor and deleted the entity with the enchantment. hope it helps.
> 
> I actually did the same, and disabled the enchantment in the configs as well. Still should be addressed though

Where did you find the config for it? I can't seem to find a config for MGU in the configs folder

**Comment by MacBurro** [comment]
> > > Hey man, had the same problem with the FrostRebukeEnchantment and no backup. I recovered the save with NBTEditor and deleted the entity with the enchantment. hope it helps.
> > 
> > 
> > I actually did the same, and disabled the enchantment in the configs as well. Still should be addressed though
> 
> Where did you find the config for it? I can't seem to find a config for MGU in the configs folder

I think it's from the Ensorcellation Mod, maybe you could disable it directly from the config files of the mod in the save folder, should be named something like ensorcellation-server.toml

**Comment by RStieber** [comment]
It's from the Ensorcellation mod, and I disabled chilling rebuke and flame
rebuke (https://www.curseforge.com/minecraft/mc-mods/ensorcellation ),
/saves/WORLD_NAME/serverconfigs/ensorcellation-server.toml

**Comment by jeremiahwinsley** [comment]
Fixed in 1.5.8.

**Comment by jeremiahwinsley** [comment]
Fixed in latest version of Mob Grinding Utils, should be in next update.

**Comment by oly2o6** [comment]
in 1.0,6
