### ISSUE TITLE
Anyone have a good Wool automation?

### ISSUE THREAD

**Issue by Vertigo81** [AllTheMods/atm6-sky#145]
So AE2 cables are burning thousands of wool and I'm really tired of shearing an enormous flock of sheep which are causing a ton of noise and lag >_<

Thing is I haven't found a good way to automate it.  There is no Mystical Agriculture recipe for wool, weirdly enough.  The sheep essence can only make mutton.  Any chance of adding a wool recipe to that?  Would be very helpful and it's weird it's not in there already.  I mean you can make leather and milk with cow essence...

Options I've come up with so far all require a sizeable space investment to keep up with the wool demand.  I could make a large create based crop farm to harvest hemp fibre and turn that into wool.  But to keep up with the demand it will need to be very large.  Only crop accelerators I've found are the pedestal fertilizer mod and the MA watering can.  The later I can't figure out if I can automate, and the former has a very small range.

There's the garden cloches from IE and the little plant pots, but both need a deep investment into mods I haven't started yet (IE, Botania or that pressure thing that looks weird as hell)

Anyway, are there any obvious solutions I'm missing here?  I'd rather not have to build a huge farm just for one resource I only need for 1 very specific purpose >_<

**Comment by Mightylight** [comment]
Maybe look into spider seeds from mystical agriculture. They can make string i think and from that you can make wool. I don't see a better way, but making wool from sheep essence would nullify the string from spider essence. you can grind down wool into string

**Comment by Topside08** [comment]
you can farm to get string or flax and auto-craft that into wool there are a lot of farmables that can be made into string

**Comment by tyler489** [comment]
I used a t4 woot factory eith phantoms and sheep. got a few hundred of each wool in little time and still working through it all almost a week later.

**Comment by Eugene21040** [comment]
shears+pedestal(reliquary)+farm sheep= autofarm wool
