### ISSUE TITLE
Game crash 

### ISSUE THREAD

**Issue by D3adCookie** [AllTheMods/atm6-sky#146]
My game keeps crashing and I think it's because of a enchantment from Mob Grinding Utils, however I am not certain of this. 

If that is the case then where do I find the config to turn that enchantment of? I can't seem to find a config for MGU in my configs folder

Crash report:
[crash-2021-04-03_15.56.17-server.txt](https://github.com/AllTheMods/atm6-sky/files/6252809/crash-2021-04-03_15.56.17-server.txt)

**Comment by sanyi** [comment]
Yes I got the same problem with `mob_grinding_utils:saw` game crashed immediately the world loaded. I ended up deleting/replacing the block from the save game and I was able to play once more. I used this `https://github.com/DonoA/PyAnvilEditor`

**Comment by D3adCookie** [comment]
> Yes I got the same problem with `mob_grinding_utils:saw` game crashed immediately the world loaded. I ended up deleting/replacing the block from the save game and I was able to play once more. I used this `https://github.com/DonoA/PyAnvilEditor`

I am not so good with the whole coding thing. Is there a simply way for me to disable the enchant and or fix my world?

**Comment by sanyi** [comment]
Maybe `https://www.mcedit.net/` probably will not recognize the grinder but you should be able to replace by coordinate. I am not able to run this on my OS but should work on Windows and Mac.

**Comment by D3adCookie** [comment]
> Maybe `https://www.mcedit.net/` probably will not recognize the grinder but you should be able to replace by coordinate. I am not able to run this on my OS but should work on Windows and Mac.

Yeah I am getting a "'NoneType' object is not iterable" whilst trying to use the MCEdit program but thanks for helping

Screenshot:
![image](https://user-images.githubusercontent.com/40703368/113489017-e8302380-94c1-11eb-9e00-0e07fe89b059.png)

**Comment by D3adCookie** [comment]
I deleted the mod and I could load up the world just fine. So I guess it's "fixed"

**Comment by D3adCookie** [comment]
I deleted the mod and I could load up the world just fine. So I guess it's "fixed"
