### ISSUE TITLE
Crash caused by bpm-1.0.2.71.jar

### ISSUE THREAD

**Issue by Pandaxgamingx** [AllTheMods/atm6-sky#148]
**Describe the bug**
I was having issues launching the modpack because it'd crash every time it would finish freezing the data and it'd take me back to the launcher with an error code 255. After a little research I saw that it might be caused by the bpm mod so I took it out the mod folder for ATM6S and launched it and it went all the way through but now I can't play servers due to missing a mod. 
**To Reproduce**
1. Go to launch the modpackt
2. Click on play
3. allow to load until the loading screen disappears

**Expected behavior**
I expected to be able to launch the game without having this issue

**Comment by oly2o6** [comment]
can we have your logs please? if there isnt a crash log latest.log will do fine

**Comment by Pandaxgamingx** [comment]
https://pastebin.com/RcS4LGmS

**Comment by oly2o6** [comment]
reported to the mod author and also checking on our end
