### ISSUE TITLE
Checkbox word command quest erase existing island 

### ISSUE THREAD

**Issue by NicolasDuboisToulouse** [AllTheMods/atm6-sky#151]
Checkbox quest "Syblock World Command" :
If we check the checkbox, our existing island is entirely replaced (as if we have manually run the command /skublock create)

I do this after updating the modpack. Fortunately, I had a backup...

**Comment by servireettueri** [comment]
Same thing here, but the old island isnt deleted. If you open the map (m by default) and scroll out, your original island is 8000 blocks away lmao. Thankfully I had a back-up as well but at least I had creative flight so I would have been fine either way.

**Comment by MelanX** [comment]
![image](https://user-images.githubusercontent.com/26039509/114321004-0082ec80-9b19-11eb-83b3-31610aea5a72.png)
Yes, the reward is `/skyblock create`. Should be noted somewhere :D Maybe someone collects all rewards at once and wonders why he has a new island.
