### ISSUE TITLE
Creative Crafter Issues

### ISSUE THREAD

**Issue by Epicycle23** [AllTheMods/atm6-sky#152]
Version: 1.0.5

1. I was able to pick up the creative crafter using a cardboard box. Unfortunately afterwards all patterns were gone.
2. I am not 100% certain but I suspect the creative crafter was the cause: At one point I was trying to access the crafter manager and it took a few seconds showing "Waiting for server...". When the server was back the gui opened and all patterns where moved to the most top slots. Afterwards I removed the creative crafter with a pick and it just disappeared instead of going into my inventory (that was actually the 2. time this happened, the first time I wasn't sure if my magnet just didn't work for some reason.

**Comment by starforcraft** [comment]
Currently the Creative Crafter has some lag issues if you craft like 100k items at the same time.

**Comment by Epicycle23** [comment]
> Currently the Creative Crafter has some small lag issues if you craft like 100k items at the same time.

I didn't craft anything and it is more about patterns disappearing/rearranging.

**Comment by starforcraft** [comment]
> 
> 
> > Currently the Creative Crafter has some small lag issues if you craft like 100k items at the same time.
> 
> I didn't craft anything and it is more about patterns disappearing/rearranging.

For me the Creative Crafter works fine ¯\_(ツ)_/¯

**Comment by Epicycle23** [comment]
> > > Currently the Creative Crafter has some small lag issues if you craft like 100k items at the same time.
> > 
> > 
> > I didn't craft anything and it is more about patterns disappearing/rearranging.
> 
> For me the Creative Crafter works fine ¯_(ツ)_/¯

Did you pick it up with a cardboard box?

**Comment by starforcraft** [comment]
> 
> 
> > > > Currently the Creative Crafter has some small lag issues if you craft like 100k items at the same time.
> > > 
> > > 
> > > I didn't craft anything and it is more about patterns disappearing/rearranging.
> > 
> > 
> > For me the Creative Crafter works fine ¯_(ツ)_/¯
> 
> Did you pick it up with a cardboard box when it contains patterns?

No I just break it with a Pickaxe

**Comment by Epicycle23** [comment]
> > > > > Currently the Creative Crafter has some small lag issues if you craft like 100k items at the same time.
> > > > 
> > > > 
> > > > I didn't craft anything and it is more about patterns disappearing/rearranging.
> > > 
> > > 
> > > For me the Creative Crafter works fine ¯_(ツ)_/¯
> > 
> > 
> > Did you pick it up with a cardboard box when it contains patterns?
> 
> No I just break it with a Pickaxe
> Edit: The Cardboard Box seems to delete the patterns. That is not my fault. Mekanism has to fix it.

I didn't say it's anyones fault, jsut trying to make people aware of the issues I was facing.
As a side note: other crafters cannot be picked up with the cardboard box, just the creative one.

**Comment by starforcraft** [comment]
> 
> 
> > > > > > Currently the Creative Crafter has some small lag issues if you craft like 100k items at the same time.
> > > > > 
> > > > > 
> > > > > I didn't craft anything and it is more about patterns disappearing/rearranging.
> > > > 
> > > > 
> > > > For me the Creative Crafter works fine ¯_(ツ)_/¯
> > > 
> > > 
> > > Did you pick it up with a cardboard box when it contains patterns?
> > 
> > 
> > No I just break it with a Pickaxe
> > Edit: The Cardboard Box seems to delete the patterns. That is not my fault. Mekanism has to fix it.
> 
> I didn't say it's anyones fault, jsut trying to make people aware of the issues I was facing.
> As a side note: other crafters cannot be picked up with the cardboard box, just the creative one.

(Im the dev of Creative Crafter :) )

**Comment by Epicycle23** [comment]
The disappearing of the creative crafter is reproducable on my end.
I just created a new world, cheated in a creative crafter in survival mode via JEI and tried to pick it up with a diamond pick, it just vanishes every time.

**Comment by starforcraft** [comment]
> 
> 
> The disappearing of the creative crafter is reproducable on my end.
> I just created a new world, cheated in a creative crafter in survival mode via JEI and tried to pick it up with a diamond pick, it just vanishes every time.

Which Version of Creative Crafter do you have?

**Comment by Epicycle23** [comment]
All the mods 6  - to the sky 1.0.5
->  creativecrafter-1.16x-0.1.jar

**Comment by starforcraft** [comment]
> 
> 
> All the mods 6 - to the sky 1.0.5
> -> creativecrafter-1.16x-0.1.jar

That could it be can you maybe try it out with the newest Version?

**Comment by Epicycle23** [comment]
Duplicated the profile.
Updated to creativecrafter-1.16x-0.11.jar.
Created a new survival world.
Cheated in a creative crafter in survival mode via JEI and tried to pick it up with a diamond pick, it still vanishes every time although it looks more creative now  ;)

**Comment by starforcraft** [comment]
huh now I tested it again and it didnt worked. I will fix it now :)

**Comment by Epicycle23** [comment]
this is so strange, I was trying to check if crafting it makes a difference, but now it doesn't vanish anymore even when cheated in...

**Comment by Epicycle23** [comment]
As far as the cardboard box goes, there seems to be a way to blacklist blocks from being picked up, which apparently is used for the other crafters:

https://github.com/mekanism/Mekanism/issues/5899

**Comment by starforcraft** [comment]
Its fixed and pushed on curse :)
