### ISSUE TITLE
Pedestals not working

### ISSUE THREAD

**Issue by Mario5572** [AllTheMods/atm6-sky#154]
Pedestals are not accepting the upgrades.

1. Craft a pedestal and any upgrade.
2. Right click the upgrade in the pedestal.
3. See that it doesn't go into the upgrade slot, but to the item slot.

![2021-04-04_12 05 50](https://user-images.githubusercontent.com/64431764/113505346-63cfb600-953e-11eb-8ba5-4f3b00f5fd01.png)

**Comment by featherspeed** [comment]
same problem

**Comment by Eugene21040** [comment]
yp its new bug

**Comment by tyler489** [comment]
https://youtu.be/N3Doz6OKjmY
May want to watch the new update video i think it was changed.

**Comment by Mario5572** [comment]
Problem solved, you just put the upgrade on the left hand and right click.
