### ISSUE TITLE
Crying Obsidian

### ISSUE THREAD

**Issue by D3adCookie** [AllTheMods/atm6-sky#156]
Is there a way to get Crying Obsidian? Can't seem to find a way in any of the mods

**Comment by Eugene21040** [comment]
Crying Obsidian in vanilla minecraft is obtained by trading with piglins or from portals generated in the world.
I don't think there is a way to get it through mods.

**Comment by servireettueri** [comment]
You should be able to create a platform in the correct biome in the nether and have them spawn. Then create an auto-trader which, with the mob capture tool and redstone timer should be easy.

**Comment by D3adCookie** [comment]
Alright will do the vanilla way. Just thought there might be a easier way. Thanks for answering :)
