### ISSUE TITLE
Pedestal upgrades display rather than upgrade

### ISSUE THREAD

**Issue by Wall-Nut595959** [AllTheMods/atm6-sky#158]
**Describe the bug**
In versions 1.0.5 and below, pedestals accept upgrades like they should. In the latest release (1.0.6), right-clicking with a pedestal upgrade puts it on display rather that upgrading it.

**To Reproduce**
1. Go on version 1.0.6
2. Create new world and get a pedestal and any upgrade

**Expected behavior**
I expect the pedestal to upgrade with the item instead of displaying it.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/81923294/113516362-d98c4f80-9547-11eb-968d-49c39d179a7b.png)

**Additional context**

**Comment by Eugene21040** [comment]
https://www.youtube.com/watch?v=N3Doz6OKjmY&t=734s

**Comment by RoxasLamprunge** [comment]
right click the pedestal with the upgrade in or off hand
