### ISSUE TITLE
Ex Nihilo Mesh Enchantments

### ISSUE THREAD

**Issue by CrispyPigeon131** [AllTheMods/atm6-sky#16]
Generally in Ex nihilo you are able to enchant the meshes with efficiency as well as fortune.; this however is not an option in ATM6 Skies. 
![image](https://user-images.githubusercontent.com/63083209/110416377-40a60980-8059-11eb-91e1-9ae7ed447f8b.png)
 There are currently a handful of enchantments that do not make sense at all available for the meshes.

**Comment by jeremiahwinsley** [comment]
Ex Nihilo Sequentia does not have Sieve Fortune / Sieve Efficiency enchantments yet. You are welcome to suggest this to them, but this is not something we can fix. Most of those other enchantments are added automatically to items with durability - we have mesh damage turned off, but it does have durability.
