### ISSUE TITLE
Swamps Villagers breed incorrect babies

### ISSUE THREAD

**Issue by RANGER428** [AllTheMods/atm6-sky#160]
Swamps Villagers breed incorrect babies when mating in the swamps, the breed normal babies. Is this a bug?

I don't have the same issue so far with the Frozen Tundra Villagers, Savanna Villagers is fine and breed the correct clothed babies.

All the Mods 6-1.5.4b

see image attached
![IMG-20210404-WA0016](https://user-images.githubusercontent.com/49692804/113520656-e2efd900-9594-11eb-88c9-ef2dc58b84d3.jpg)

**Comment by MelanX** [comment]
This is ATM6 Sky issue tracker, not ATM6.
