### ISSUE TITLE
Diamond Jetpack not Craftable

### ISSUE THREAD

**Issue by UnhappyCodings** [AllTheMods/atm6-sky#162]
It's not possible to Craft the Diamond Jetpack from the Iron Jetpacks mod!

I'm on 1.0.6 and its still occuring.
The endgame quest is not possible

**Comment by ghingis** [comment]
It broke in the [bees and stuff commit](https://github.com/AllTheMods/atm6-sky/commit/159958b3e52847e07dff8c4af50364f5ac929fe3), just created a pull request for it (#183)
