### ISSUE TITLE
Missing recipes on Server

### ISSUE THREAD

**Issue by Seniorendi** [AllTheMods/atm6-sky#163]
Hey, we have no Diamond Jetpack recipe on the server, but in a singleplayer world. 
When I want to craft the diamond jetpack without jei, it does not work.
![image](https://user-images.githubusercontent.com/67484093/113553716-74446700-95f8-11eb-8a6f-c5e9856ef415.png)

Modpack version: 1.0.6b

**Comment by tyler489** [comment]
Duplicate #162

**Comment by Seniorendi** [comment]
Ahh yes, sorry.
