### ISSUE TITLE
1.0.6 Failure to correctly apply right click actions

### ISSUE THREAD

**Issue by Calgor73** [AllTheMods/atm6-sky#164]
Two incidents, two separate mods (so far):

Integrated Dynamics - Attempting to place menril log into manual squeezer, log not accepted. Log can be placed via piping methods (hopper and item pipe from pipez) - all other mod functionality appears unaffected. 

Pedestals - Unable to attach upgrades to pedestals from pedestal mod, but upgrades can be placed (and removed) as display items.

Both actions relate to right clicking on items, but other right click functions within mods appears unaffected

**Comment by EvilGodz** [comment]
Pedetals mod have been reworked so
To insert an Upgrade, put the upgrade in your offhand, then Right-Click the pedestal with an empty hand.
