### ISSUE TITLE
The Other

### ISSUE THREAD

**Issue by spaidis** [AllTheMods/atm6-sky#165]
Can't seem to find any dragons, its this on my end or what. ( flying while using spectral eye)

**Comment by MelanX** [comment]
Should be fixed by updating Skyblock Builder in 1.0.7

**Comment by starforcraft** [comment]
> Can't seem to find any dragons, its this on my end or what. ( flying while using spectral eye)

Are you looking in the right Biomes and Underground? (The Spectral Eye vision isn't far enough)
