### ISSUE TITLE
Time in a bottle resets the time collected if auto organizing inventory

### ISSUE THREAD

**Issue by MiniVinny** [AllTheMods/atm6-sky#166]
**Describe the bug**
As the title states i clicked the ↓AZ button for auto organizing my inventory and i have multiple TIAB (Time in a bottle) the ones that were in my inventory and auto organized the time that had been collected overnight was reset to 0. I dont know if its because i have multiples or what but it just keeps getting reset like it will go up to 9 seconds and reset to zero but the one in my hotbar is fine. 
**To Reproduce**                     
1. Go to '↓AZ at top right of inventory'
2. Click on '↓AZ'

**Expected behavior**
the time in a bottles accumulated time will reset

**Screenshots**
![image](https://user-images.githubusercontent.com/81973396/113583546-c33dcc80-95f7-11eb-8191-36fdd4580882.png)
![image](https://user-images.githubusercontent.com/81973396/113583620-dc467d80-95f7-11eb-8adb-ca090adee665.png)
![image](https://user-images.githubusercontent.com/81973396/113583758-0f890c80-95f8-11eb-82fb-9a395bc2fd01.png)

**Additional context**
again, i dont know if its because i have multiples of the TIAB.

**Comment by haoict** [comment]
Hi, I am the owner of Time in a bottle mod.
You can only have one TIAB item in your inventory, if you have more than one, the others will not collect time.
Why? To make the game balance.
