### ISSUE TITLE
Resourceful bees

### ISSUE THREAD

**Issue by daitye** [AllTheMods/atm6-sky#170]
How do I get Resourceful Bees as the starter eggs are not craft able

**Comment by DankMemesys** [comment]
ATM6Sky ver. 1.0.7 will add bee progression

**Comment by Eugene21040** [comment]
And when is 1.07 already known?

**Comment by DankMemesys** [comment]
IIRC there is a w.i.p. branch about the 1.0.7 update

**Comment by Gremkow** [comment]
Bee Progression was just added in 1.0.6b - to obtain the base Bee's you will need to craft their spawn egg via Mystical Agricultures Infusion Crafting. You can then start breeding.

**Comment by MelanX** [comment]
This can be closed then.
