### ISSUE TITLE
infinite xp when updated from 1.0.5 to 1.0.6

### ISSUE THREAD

**Issue by ponduzn** [AllTheMods/atm6-sky#171]
When i updated to 1.0.6, my simple mob farm has infinite exp in the singularity tank/absorption hopper.
Setup is a simple farm with vector plates, mob grinder, absorption hopper that pushes items down into pipez, and sideways to a singularity tank.

**To Reproduce**
1. Go to mob farm
2. open exp tap
3. get drenched in infinite exp.

**Expected behavior**
Tank should empty out.

**Screenshots**
I included world save instead, so you can check it out.

World Link:
https://drive.google.com/file/d/1M3ARj-YSeCM1pENo3sejwJEUQq6Bc4wr/view?usp=sharing

**Comment by Vertigo81** [comment]
I tried it after seeing this.  Can confirm, xp came out in a slow trickle forever with no new exp coming in to the tank.  I turned the farm back on for a second and closed and reopened the spigot and it stopped and behaved normally.
