### ISSUE TITLE
Game keeps freezing every few seconds.

### ISSUE THREAD

**Issue by clojac12345** [AllTheMods/atm6-sky#172]
After playing for 30-60 mins, the game starts to eat up all of the allocated RAM and freezes for a few seconds, then frees up, and rapidly climbs back up in RAM usage until it freezes again for a few seconds.

I have 10Gb allocated for the game and with F3 open, I can see it'll go up to 100% RAM usage, then jump down to 7.5Gb and climb back up to 10Gb where it freezes for 5-10 seconds before restarting the cycle. 

This happened on all versions I've played on, 1.0.4, 1.0.5, and 1.0.6

**Comment by MelanX** [comment]
Can you send a log?

**Comment by clojac12345** [comment]
[2021-04-03-2.log.gz](https://github.com/AllTheMods/atm6-sky/files/6298618/2021-04-03-2.log.gz)
That is client log, this is server log:
[2021-04-03-2.log.gz](https://github.com/AllTheMods/atm6-sky/files/6298627/2021-04-03-2.log.gz)

**Comment by oly2o6** [comment]
mem leak issues fixed
