### ISSUE TITLE
Ice and Fire Dragon's Not Spawning

### ISSUE THREAD

**Issue by Karan-Sidhu** [AllTheMods/atm6-sky#173]
In The Other dimension ice and fire dragon caves have a 1/8 chance per chunk to generate in their designated biomes. While searching for a couple hours far away from spawn you can conclude that none are spawning. Checking the configs there is no option to turn on or off dragon spawns, while for most every other creature there is such option. With cockatri they have the spawns manually turned off so that behavior is correct. This is a freshly created Other in 1.06. I manually searched in creative with amulet then switched over into spectator mode. I know the dragon's have select biomes they spawn in and I made sure to check those and it seemed only underground nether fortresses spawned. Are the dragon's still being worked on or turned on later, because I have reached the point in which the dragon forge is needed to forge alloy's of the end game ingots to complete the quests for "FUUUSIOON HA!" and beyond in the last quest set.

**EDIT: With a newly loaded 1.06 server the terminal spits out that all spawns are false. I'm not sure how to change this.** 

1. **FIRE_DRAGON_CAVE_CF=false,** 
2. **LIGHTNING_DRAGON_CAVE_CF=false**, 
3. **ICE_DRAGON_CAVE_CF=false,**

[18:53:58] [Server thread/INFO] [co.gi.al.ic.IceAndFire/]: {SPAWN_DRAGON_SKELETON_I_CF=false, HYDRA_CAVE_CF=false, SPAWN_SEA_SERPENT_CF=false, SPAWN_STYMPHALIAN_BIRD_CF=false, SPAWN_WANDERING_CYCLOPS_CF=false, PIXIE_VILLAGE_CF=false, SPAWN_DEATH_WORM_CF=false, **FIRE_DRAGON_CAVE_CF=false,** SIREN_ISLAND_CF=true, MYRMEX_HIVE_DESERT_CF=false, SPAWN_HIPPOCAMPUS_CF=false, FIRE_DRAGON_ROOST_CF=false, MYRMEX_HIVE_JUNGLE_CF=false, GORGON_TEMPLE_CF=false, COPPER_ORE_CF=false, SILVER_ORE_CF=false, **LIGHTNING_DRAGON_CAVE_CF=false**, SPAWN_DRAGON_SKELETON_F_CF=false, AMETHYST_ORE_CF=false, SPAWN_DRAGON_SKELETON_L_CF=false, LIGHTNING_LILY_CF=true, MAUSOLEUM_CF=false, **ICE_DRAGON_CAVE_CF=false,** GRAVEYARD_CF=false, SAPPHIRE_ORE_CF=false, LIGHTNING_DRAGON_ROOST_CF=false, CYCLOPS_CAVE_CF=false, FROST_LILY_CF=true, FIRE_LILY_CF=true, ICE_DRAGON_ROOST_CF=false}
[18:53:58] [Server thread/INFO] [co.gi.al.ic.IceAndFire/]: {TROLL_S=false, HIPPOGRYPH=true, AMPHITHERE=false, COCKATRICE=false, TROLL_M=false, DREAD_LICH=false, TROLL_F=false}

**Comment by Lolam33** [comment]
Hello I had the same problem and after a lot of testing I finally found the solution.
The problem has to do with the world type Sky Block. In the config from skyblockbuilder are whitelistet structures listet. 

![ConficSkyBlockBuilder](https://user-images.githubusercontent.com/80175154/113884440-42313180-97bf-11eb-9f06-f8bc1af2aa4c.PNG)

Before there were just end_spike and end_gateway, I added the 3 dragon caves. They can be found in the features txt in the config folder from skyblockbuilder. After adding these I loaded my world and searched, but I didnt need to search for a long time. Found a lightning dragon under a desert immediately.

![2021-04-07_16 38 11](https://user-images.githubusercontent.com/80175154/113884990-be2b7980-97bf-11eb-8c94-ac672163a548.png)

If you dont want to add stuff to your config you can also just start a new world with the world type Garden of Glass from Botania. That also seem to work.

**Comment by NicolasDuboisToulouse** [comment]
Hello, thank ! That worked for me! 
I've added the 3 caves in skyblockbuilder/config.toml, remove "The Other" dimension and caves are now generated.

They still really hard to find in survival:
* The Spectral Eye Amulet has a short view distance: you cannot see dragons when flying a Y 180.
* Caves seem only generated in pure vanilla biomes and there are not a lot of these biomes in "The Other".

**Comment by Mightylight** [comment]
i haven't been able to find the specific code that you send a screenshot off. maybe it has changed, cause i updated to 1.0.6b, but i can't find it

**Comment by Mightylight** [comment]
Update: The piece of code that you send, has been deleted from the folder. They might have fixed the whole dragons not spawning, but i haven't gotten the chance to play yet

**Comment by Lolam33** [comment]
Ye, I just testet and it has been fixed with the release of 1.0.6b.

**Comment by Vertigo81** [comment]
Yeah the Other is much changed.  I need to reset mine.  Where I've generated new chunks in places I didn't scour yet there are soul lava sources, crude oil, tons of ores.  Actual vegetation and lots of new stuff.  (there are random way stones all over the place O_o ?)

I haven't found a living dragon yet, but I've found a few skeletons that have health but don't move?  I assume this is a normal part of the fire and ice mod?  But I haven't gotten into it at all yet.  Found some monster bugs in a resin cave thing.

**Comment by Lolam33** [comment]
Make sure you search for the dragons in the right biomes. 
Fire Dragons spawn in Basalt Deltas
Ice Dragons spawn in Mountain biomes
Lightning Dragong spawn in the Desert 
It's easiest (at least for me) to take a spectral eye amulet and dig underground in the above mentioned biomes.

**Comment by Karan-Sidhu** [comment]
Thanks for all the help guys! Issue was fixed in 1.06b but all the temporary solutions were appreciated.
