### ISSUE TITLE
Soul Lava Is ignored by Pumps

### ISSUE THREAD

**Issue by tyler489** [AllTheMods/atm6-sky#175]
Soul Lava does not work with Rftools Builders with a quarry card. is this intended?

**Comment by Vertigo81** [comment]
Woah where'd you find it?  I scoured the other and no dice

**Comment by tyler489** [comment]
It's Rare underground like 1 block every 5 chunks or more.

**Comment by Vertigo81** [comment]
Weird.  (I totally resorted to spectator mode and still can't find any)
