### ISSUE TITLE
Lower fps. compacting drawer

### ISSUE THREAD

**Issue by Eugene21040** [AllTheMods/atm6-sky#177]
Compacting drawer lower my fps built a wall from a drawer (59 units) to store all the ingots and other things, as a result, the fps fell from 90 to 40 or even lower
https://prnt.sc/115owf6 no drawer
https://prnt.sc/115ozel there is a drawer
I understand that my computer is weak, but not so weak that a couple of boxes would lower the FPS in half

Maybe it's time to start thinking about adding optifine?

**Comment by tyler489** [comment]
Please Do not add optifine to the pack by default. It breaks more than it fixes, and alot of mod devs say they won't support issues when optifine is installed. Optifine is client side and if a user wants it they can add it with no problem, why force people to use it that may not what it.
