### ISSUE TITLE
Insane Lag after using the Drawbridge from Tinkers' Mechworks

### ISSUE THREAD

**Issue by ArcheTypeY** [AllTheMods/atm6-sky#178]
I was building my base when I realised that this mod was in the pack. So I thought let's make a cool bridge with this mod, because it is easy to use and I'm still new to ''Create". But then when I activated the Drawbridge it didn't do what it was supposed to do and my whole game froze. It turned out my game was still running at like 1 fps. Luckily, I had my pickaxe equipped and could remove the drawbridge, which fixed my game.

**Comment by ArcheTypeY** [comment]
- [bug ]

**Comment by ArcheTypeY** [comment]
- [ ] Bug

**Comment by ArcheTypeY** [comment]
> bug

**Comment by tyler489** [comment]
I imagine this is probably due to the way the game calculates lighting. If you place a large amount of blocks over the void at once the game freaks out when it tries to do lighting calculations.
How big was this drawbridge?

**Comment by ArcheTypeY** [comment]
I think you
