### ISSUE TITLE
Resourceful Bees 

### ISSUE THREAD

**Issue by Mifwiin** [AllTheMods/atm6-sky#179]
I was trying to progress in this mod but it seems like some bees are unreachable. I dont know how to get other bee types like magma bee or etc.

**Comment by Mightylight** [comment]
Bees are not yet integrated in the modpack. i saw another post where that was made clear.

**Comment by Mightylight** [comment]
https://github.com/AllTheMods/atm6-sky/issues/98#issuecomment-812980590

**Comment by Mifwiin** [comment]
Oh i didnt see that. Thanks
