### ISSUE TITLE
Nether not void in singleplayer

### ISSUE THREAD

**Issue by MelanX** [AllTheMods/atm6-sky#18]
**Describe the bug**

**To Reproduce**
1. Go into singleplayer
2. Go into nether
3. be happy that it's a normal nether

**Expected behavior**
Void nether, like on server

**Comment by thevortex** [comment]
what worldtype did you use for singleplayer?

**Comment by MelanX** [comment]
GoG, same as official server (and it's void on this server)

**Comment by Rithenar** [comment]
Experiencing the same issue. Updated to 1.0.2 and deleted Dim-1 to test old world. No changes. Re-installed fresh version and created a new test world, same thing. Nether is not void

**Comment by MelanX** [comment]
I think it will be fixed in next update. They will switch mod for world generation. New mod works on server and client.
