### ISSUE TITLE
Integrated dynamics, world block  importer not working.

### ISSUE THREAD

**Issue by WisestWise** [AllTheMods/atm6-sky#180]
**Describe the bug**
World block importer not imports blocks to connected inventories.

**To Reproduce**
1. Put a item container(chest).
2. Connect one item interface(integrated dynamics) to item container.
3. Connect it to a world block importer(integrated dynamics) with cables(integrated dynamics).
4. Right click to world block importer(I.D), put one variable card(I.D) in the "pick up all blocks" slot. (Be sure the bottom text says true)
5. Put a block to front of the world blpck importer(I.D)
6. It,s not doing anything.

**Expected behavior**
Normally, world block importer(I.D) should take amy block in front of it to connected item container. 

**Screenshots**
Can't.

**Additional context**
 I'm not sure but it must be about some config file that u can set the world block importers(I.D) harvest level.

**Comment by oly2o6** [comment]
mod has been updated let me know if the issue persists
