### ISSUE TITLE
Pedestal Mod error or Bug

### ISSUE THREAD

**Issue by kigen84** [AllTheMods/atm6-sky#181]
**Describe the bug**

I got problem that you can't put on the upgrades any more i try put on but it dont work?
![Error](https://user-images.githubusercontent.com/7106441/113759708-aeeff180-9715-11eb-81ce-f447f13974fa.jpg)

**Comment by Eugene21040** [comment]
Pedetals mod have been reworked so
To insert an Upgrade, put the upgrade in your offhand, then Right-Click the pedestal with an empty hand.
https://www.youtube.com/watch?v=N3Doz6OKjmY&t=4s official video

**Comment by tyler489** [comment]
#176 #174 #158 etc...

**Comment by twreid** [comment]
> Pedetals mod have been reworked so
> To insert an Upgrade, put the upgrade in your offhand, then Right-Click the pedestal with an empty hand.
> [youtube.com/watch?v=N3Doz6OKjmY&t=4s](https://www.youtube.com/watch?v=N3Doz6OKjmY&t=4s) official video

Just commenting to say had the same problem did this exact thing and it behaved as expected. Thank you.

**Comment by Vertigo81** [comment]
Super irritating, and long video just to get to the explanation, but works as intended
