### ISSUE TITLE
Fluorite Block Wrong Name in Compacting Drawer

### ISSUE THREAD

**Issue by phametic** [AllTheMods/atm6-sky#184]
Putting in fluorite into a compacting drawer does not give it a proper name.

![2021-04-06_21 08 15](https://user-images.githubusercontent.com/6393311/113796229-bf579a80-971c-11eb-84e0-c5b4c4f26a47.png)

**Comment by oly2o6** [comment]
this would (as far as i can tell) be an issue on our side and instead should be reported to the respective mod author

**Comment by tyler489** [comment]
> this would (as far as i can tell) not be an issue on our side and instead should be reported to the respective mod author

There you go ;p fixed it
