### ISSUE TITLE
Curseforge Application modpack installation error

### ISSUE THREAD

**Issue by FloppyGlots** [AllTheMods/atm6-sky#185]
I can run several modpacks from the Curseforge application such as RLcraft, Valhesia and MC eternal however All the Mods 6 To the Sky refuses to install, claiming there was an error in installation. I have the storage capacity to house the modpack. as well as upwards of 8 gigabytes of ram applicable. I understand if this is a curseforge problem or a me problem but would like to know potential reasons or fixes for such an issue

**Comment by oly2o6** [comment]
this isnt something i have seen before, in the past most people could not load packs past 1.12 but as you have played val, this is not the issue you are getting, im going to close this as a curse issue but may reopen/mention it if a similar issue comes up, all i can do for you is recommend multimc or gdlauncher as an alternative
