### ISSUE TITLE
Middle Clicking on Auto Sieve Inventory makes mesh disapper

### ISSUE THREAD

**Issue by twreid** [AllTheMods/atm6-sky#186]
I have a bad habit of sorting inventories every time I open them by clicking the mouse wheel. Every time I habitually do this with an Auto Sieve open it removes my mesh and it just disappears I have yet to be able to find my mesh after doing this.

**To Reproduce**
1. Open Auto Sieve
2. Insert Mesh
3. Press Mouse Wheel to Sort inventory

**Expected behavior**
 In this case I would expect nothing to happen or to sort the side with the crushed blocks.

**Comment by Pdiddy973** [comment]
already tracked here
https://github.com/blay09/ExCompressum/issues/309
