### ISSUE TITLE
Few more small bugs

### ISSUE THREAD

**Issue by Vertigo81** [AllTheMods/atm6-sky#189]
Pipez fluid pipe extracting from a Mekanism evaporation tower seems to forget it's set to extract every time I load the world (inside a compact machine).    

Each time I close the game and come back my smelter shuts down, I go into the machine to take a look and find the pipe is no longer extracting.  

Edit - I have this wrong.  It happened again without closing the game.  But hopping in and out of the machine doesn't cause it.  Not sure what is.

Also the heavy auto sifter deletes it's mesh and contents if I click the sort alphabetically button.  Has happened a few times by accident.  Each time I click it, the mesh vanishes along with everything inside it.  It's not going to my inventory, seems to just be deleted.

**Comment by oly2o6** [comment]
these are mod issues so would need to be reported to the mod authors
