### ISSUE TITLE
Pedestal Bug?

### ISSUE THREAD

**Issue by kuchinteavuth** [AllTheMods/atm6-sky#190]
I happened to come across pedestal while a was playing with the mod and noticed that I can't put upgrade to the pedestal it not go to the slot it always go to the top of the pedestal.
I don't know it is the mod it self or my fault. 
![Untitled](https://user-images.githubusercontent.com/18546024/113884548-4114fa00-97e9-11eb-8cf9-d8761eb5173f.png)

**Comment by Mightylight** [comment]
I don't know if it's a bug, but you can fix it by holding the upgrade in your offhand

**Comment by starforcraft** [comment]
Thats **not** a bug Pedestals mod changed that to offhand.

**Comment by kuchinteavuth** [comment]
oh thank you am just curious. because I haven play on that mod.
