### ISSUE TITLE
Botania Solegnolia does't prevent the band of magnetization

### ISSUE THREAD

**Issue by nafftan** [AllTheMods/atm6-sky#191]
Hi

as in Lexica Botania the Solegnolia should prevent the Ring of Magnetization from picking up items.

I'm playing in version 1.0.6 and both versions (floating and directly planted) next to a block where items were dropped don't affect the ring. Also the normal version as the greater version.

best regards

**Comment by Topside08** [comment]
are you giving it mana and a redstone signal probably disables it so if it's next to a pressure plate that could be an issue

**Comment by nafftan** [comment]
thank you! yes it was next to a pressure plate...... 

error between keyboard and chair ;)

please close the issue.
