### ISSUE TITLE
Certus Quartz Seed crafting recipe via Infusion Crafting on the Infusion Altar is incorrect in JEI

### ISSUE THREAD

**Issue by jakeloftis** [AllTheMods/atm6-sky#192]
**Describe the bug**
The Certus Quartz Seed crafting recipe via Infusion Crafting on the Infusion Altar is incorrect in JEI. The recipe states 1 Prosperity Seed on the Infusion Altar with 4 Tertium Essence, one each at the North, South, East and West Infusion Pedestals. The actual recipe requires 4 Certus Quartz Crystals at the Northeast, Northwest, Southeast and Southwest Infusion Pedestals.
.
.
.
The required components to craft a Certus Quartz Seed are as follows:
.
Infusion Altar: Prosperity Seed
.
(Clockwise starting with North)
.
Pedestal North: Tertium Essence
Pedestal Northeast: Certus Quartz Crystal
Pedestal East: Tertium Essence
Pedestal Southeast: Certus Quartz Crystal
Pedestal South: Tertium Essence
Pedestal Southwest: Certus Quartz Crystal
Pedestal West: Tertium Essence
Pedestal Northwest: Certus Quartz Crystal

**Comment by Eugene21040** [comment]
When crafting, I do not adhere to the crafting template, but I just put 1 component on each altar and that's it
So it's not even a bug or a bug.
