### ISSUE TITLE
game quitting

### ISSUE THREAD

**Issue by Xanzibaar** [AllTheMods/atm6-sky#194]
**Describe the bug**
while in the quest book looking at quest the game quits when pressing E key
**To Reproduce**
1. Go to quest book
2. press e key
4. game quits

**Expected behavior**
assumed quest book would behave the same way when escape key pressed

I do have worldedit installed also.

**Comment by MelanX** [comment]
Can't reproduce. Please send latest.log or at least crash report. 
And are you playing on server or singleplayer?

**Comment by Xanzibaar** [comment]
I'm playing single player and using ATLauncher and the pack is unmodified.
It's happend several times, attached are the crash reports and llatest.log zipped up
HTH
Paul
Sent from iCloud

On 11 April 2021 at 20:40, MelanX ***@***.***> wrote:






Can't reproduce. Please send latest.log or at least crash report.
And are you playing on server or singleplayer?

**Comment by MelanX** [comment]
Can’t see the link to the file. Not even a download. 
could you re-send the pastebin link, please?

**Comment by Xanzibaar** [comment]
apologies
[crash-2021-04-08_22.37.18-client.zip](https://github.com/AllTheMods/atm6-sky/files/6299093/crash-2021-04-08_22.37.18-client.zip)

**Comment by MelanX** [comment]
![image](https://user-images.githubusercontent.com/26039509/114458408-7487c800-9bdf-11eb-9bb2-5a392ced77ab.png)
This doesn't look like pastebin. But you closed the issue, so I think, it's all fixed. Cool!
