### ISSUE TITLE
Compact Drawer lag

### ISSUE THREAD

**Issue by ImperialSlayer** [AllTheMods/atm6-sky#196]
I noticed when you use a large amount of compacting drawers (example 50), the game becomes extremely laggy. The framerate when you press F3 is still normal, but when you for example break a block (any block) it will in most cases not break until you have tried 2 or 3 times. The breaking animation occurs briefly, but the block just reappears. Everything with the game just becomes really laggy save for the player movements which remain at normal speed. After reducing my compact drawer count down to a more reasonable amount (~20), this issue completely went away. I played ATM 6 with a large amount of drawers and this was not an issue on that pack. Not sure if this is a bug or I just shouldn't use that many drawers baseline.

**Comment by tyler489** [comment]
Install a mod such as spark and run a profile to see exactly what is causing lag.

**Comment by Eugene21040** [comment]
I created a topic on this issue 2 days ago and posted a photo where you can clearly see a decrease in FPS and this is 100% drawer fault
https://prnt.sc/115owf6 no drawer
https://prnt.sc/115ozel there is a drawer

**Comment by tyler489** [comment]
> I created a topic on this issue 2 days ago and posted a photo where you can clearly see a decrease in FPS and this is 100% drawer fault
> https://prnt.sc/115owf6 no drawer
> https://prnt.sc/115ozel there is a drawer

This issue is different, its not the FPS lagging, its the TPS
