### ISSUE TITLE
Chunk Loading

### ISSUE THREAD

**Issue by D3adCookie** [AllTheMods/atm6-sky#197]
Hello there!

So I tried putting up some teleporters in my over-world but it did not go as planned. Once I go trough the distant teleporter to my main one at base, the other one dies and I think it's because there is no chunk loading. I have it claimed and I tried making a Anchor upgrade but those are disabled. 

Any way for me to enable chunk loading in the pack, on all items? Such as fluxpoints, anchors, chunk claiming, and so on? 

Thanks :)

**Comment by tyler489** [comment]
You can chunkload chunks with FTB

**Comment by Gremkow** [comment]
So there is nothing to enable all of them, but for example for fluxpoints it is possible to change the Flux Networks config to enable chunk loading. Also when shift clicking an already claimed chunk (in FTBChunks) you can load up to 25 chunks.

**Comment by tyler489** [comment]
> So there is nothing to enable all of them, but for example for fluxpoints it is possible to change the Flux Networks config to enable chunk loading. Also when shift clicking an already claimed chunk (in FTBChunks) you can load up to 25 chunks.

Theres a config option, i enabled it for singleplayer

**Comment by Gremkow** [comment]
> 
> 
> > So there is nothing to enable all of them, but for example for fluxpoints it is possible to change the Flux Networks config to enable chunk loading. Also when shift clicking an already claimed chunk (in FTBChunks) you can load up to 25 chunks.
> 
> Theres a config option, i enabled it for singleplayer

Can you share the relative path / the config file name to enable chunkloading in all mods?

**Comment by tyler489** [comment]
oh sorry.. i misread your post... yeah no way to enable them all at once.

**Comment by D3adCookie** [comment]
Awesome! Thanks for the answers
