### ISSUE TITLE
Pedestal functionality not working

### ISSUE THREAD

**Issue by Catandcomparator** [AllTheMods/atm6-sky#198]
When i try to color or add an upgrade to a pedestal, it does not get applied. i can still put items on them, however.

Craft a pedestal, and try to apply an upgrade/color.

I expected it to just allow me to mess with the pedestal, but it wont allow me.

**Comment by kaischuett** [comment]
Same for me.
It works if you put the Upgrade in the Offhand slot

**Comment by tyler489** [comment]
This Is intended #190 #181 #176 #174 #158

**Comment by Catandcomparator** [comment]
thank you!

**Comment by Catandcomparator** [comment]
its not intended
