### ISSUE TITLE
Anyone else lose all their saves with the most recent update?

### ISSUE THREAD

**Issue by servireettueri** [AllTheMods/atm6-sky#200]
The one time I forget to make a back-up lmao. The last 3 updates I made updates and didnt even need to. This time I did and everything is gone. I have the automatic backups but idk how to use those.
EDIT: Never mind even the backups got deleted. Even the backups I made manually by copy pasting the folder to a seperate hard drive. How is this even possible?

**Comment by leyxcx** [comment]
My inventory keeps resetting to hours before I've saved and quit the game, so I just lose heaps of progression. Done with the pack tbh lmao.

**Comment by servireettueri** [comment]
I restarted, just cheated in cobblestone generator and a auto hammer/sieve to get a head start.
