### ISSUE TITLE
How can you breed with the lava bee?

### ISSUE THREAD

**Issue by Gremkow** [AllTheMods/atm6-sky#201]
When using the Apiary Breeder from Resourceful Bees to breed Stoned Bee with Lava Bee and Cobbee you need 5 Lava Crystals.
But Lava Crystals dont stack so you can only put a single crystal into the Breeder. Not sure if this is a broken recipe or if I am doing something wrong.

**Comment by servireettueri** [comment]
do it manually if all else fails.

**Comment by Mightylight** [comment]
How do you even get started with bees? i haven't been able to find a beginning in bees

**Comment by Pdiddy973** [comment]
Look in the ATM6s general chat for the breeding chart, it shows what ones can be crafted, what ones a breed, and what ones need mutations

**Comment by Gremkow** [comment]
For anyone else looking for the chart: https://miro.com/app/board/o9J_lLqaxQ4=/
