### ISSUE TITLE
FPS issues 

### ISSUE THREAD

**Issue by AUDIO179** [AllTheMods/atm6-sky#202]
5-8 FPS??? Im running an 8G GPU card and 32G of Ram - I play most games 7D2D/Valheim/Fortnite on epic settings and all Minecraft packs on max settings with ease.
Anyone else having FPS issues?
Currently unplayable..sad face.

**Comment by Esconomics** [comment]
A couple of players had this on my server as well. Optifine fixed it for them all. One went from 2fps to 150

**Comment by AUDIO179** [comment]
Cheers will give it a go.

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
