### ISSUE TITLE
Solidification Chamber not working?

### ISSUE THREAD

**Issue by UnburnedToast** [AllTheMods/atm6-sky#204]
I'm trying to use the solidification chamber to make Menril saplings, and i have everything i need for it, the 2 berries, spruce sapling, the slime, and power. is there something im missing to start it?

**Comment by tyler489** [comment]
Fix your brackets 
We can't see the post

**Comment by MelanX** [comment]
![image](https://user-images.githubusercontent.com/26039509/114318064-7a13de00-9b0b-11eb-8a21-81b4f9de46da.png)
It needs to be exactly this order. Top and bottom the berry, middle the sapling.
