### ISSUE TITLE
is:open label:"Help wanted" my game freezing when trying to load into my world

### ISSUE THREAD

**Issue by npersaud0505** [AllTheMods/atm6-sky#205]
:"Help wanted" my game freezing when trying to load into my world

**Comment by Garueri** [comment]
I read in one of the update things that its currently a forge issue, so does mine, and it eventually loads
open your task manager and check if there isn't something else eating your processing power
For some reason, a strange chrome eats my CPU unless I close him in the task manager
Beyond that, I have no further intel

**Comment by MelanX** [comment]
A log is always helpful.
