### ISSUE TITLE
Compacting Drawers

### ISSUE THREAD

**Issue by mgreco98** [AllTheMods/atm6-sky#206]
**Describe the bug**
Are not working at all. Are acting like a normal drawer. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by mgreco98** [comment]
Did some testing, works with most blocks but the ore pieces are not working with them. I do not know if this is 1.6 or if this is a bug or if this is disabled.

**Comment by Pdiddy973** [comment]
Ore pieces can't be un crafted so they dont work, nothing is wrong
