### ISSUE TITLE
ftb chunk claimer

### ISSUE THREAD

**Issue by Eugene21040** [AllTheMods/atm6-sky#209]
I use item user from cyclic to automate sieves, but after updating the assembly, item user does not do his job in the clam chunk
I checked the breaker block, but it works in the chunk, it might be malfunctioning
It's like not letting machines do work in a locked chunk.

**Comment by geeee785** [comment]
ally the item user

**Comment by MelanX** [comment]
![image](https://user-images.githubusercontent.com/26039509/114317933-c90d4380-9b0a-11eb-8e85-306e33306ac7.png)
You need to accept the Fake Player.
This list can be found here: 
![image](https://user-images.githubusercontent.com/26039509/114317952-dfb39a80-9b0a-11eb-9759-961a548fb9b0.png)
