### ISSUE TITLE
Enderium's Induction Smelter Crafting not automatable

### ISSUE THREAD

**Issue by albyalex96** [AllTheMods/atm6-sky#210]
Crafters don't insert the items required in the smelter . Crafting monitor reports " No machine found ". Other Thermal Series's recipes are still working. Items can be manually inserted in the machine.

**Comment by MelanX** [comment]
Did you configure the side configs correctly?

**Comment by albyalex96** [comment]
yes i did. all other recipies that require induction smelter processing are working.

**Comment by bloodscon** [comment]
Thermal's induction smelter can now be overfilled with the third slot and as such it can lock the machine
found that out when crafting invar and steel when i checked the smelter found it had coal dust, iron, and nickel on the input slots i ended up using seperate smelters for each of the alloys
