### ISSUE TITLE
The mod is becoming unplayable my world got deleted (both the save and back-up) yesterday and today my world is corrupted.

### ISSUE THREAD

**Issue by servireettueri** [AllTheMods/atm6-sky#212]
![image](https://user-images.githubusercontent.com/76633423/114185032-7cefb280-9902-11eb-8cb2-f4ac82b3d247.png)

This is what I loaded up today wtf is happening.

**Comment by MelanX** [comment]
Looks like your world didn't save or load correctly. 
You sure that you didn't start the wrong pack? Where should the backups be? Did you update the pack? Maybe this caused data loss.

**Comment by servireettueri** [comment]
The backups are in the curseforge instances folder. The delete was after an
update (which I did post in that original bug report) but the world
corruption wasn't an updated world or anything. It was the same version.
