### ISSUE TITLE
Rock Crystal Seeds recipe

### ISSUE THREAD

**Issue by DrWKool** [AllTheMods/atm6-sky#214]
**Describe the bug**
Mystical Agriculture Rock crystal seeds recipe is not working

**To Reproduce**
1. used 4 rock crystals created from the ore (created ore via astral sorcery)
2. used 4 supremium essence and a base crafting seed as per JEI recipe
3. No craft happening when giving the pedistal a redstone signal
4. all other recipies are working as it should be

**Expected behavior**
Rock crystal seed should be made

**Additional context**  FIX/work arround
The issue is the NBT data of the rock crystals. The stats are changing when creating. Figured out, when you have 4 crystals with exactly the same stats, the craft works and seed is created. Problem is to duplicate the crystals to get the same stats. I used creative mode to test this out.

**Comment by MelanX** [comment]
I don't know why but it works with only Mystical Agriculture and Astral Sorcery with the same versions as in the pack. And I can't find any recipe change.
But I couldn't even craft it in creative.
