### ISSUE TITLE
What are the dimensions supposed to look like?

### ISSUE THREAD

**Issue by Vertigo81** [AllTheMods/atm6-sky#215]
So now that the Other is fixed, I reset it again.  And I realized I don't know what the intended version of the nether or end is.  Mine are complete voids, no ground or structures.  But from what I see/hear, many have a ground or structures (nether fortress, end city, etc)

So I made a new world to test it out, and it came up with the Nether still being a void, but the End had ground.  No vegetation or Ore gen, No cities, but the islands were all there.  

So is this intended?  Or is it supposed to be a void like my original world?  Or supposed to have structures in the void like others have?

**Comment by servireettueri** [comment]
nether is a void you can still find the structures if you look around though. Just make sure to mark where your portal is on your map. You're going to want some kind of flight as well. IDK about the end though.

**Comment by tyler489** [comment]
Nether is not supposed to have structures.

**Comment by servireettueri** [comment]
Yeah nether fortresses still spawn. The 3 youtubers I watch all say it's intentional.

**Comment by Vertigo81** [comment]
This is what I'm talking about though ^

That confusion.  The lets plays I've seen all have them too, but if you make a new game (at least when I did) there are no fortresses.  I double checked with console, they don't spawn.  Yet clearly some have them and say they are intentional.  So... What the hell?

**Comment by tyler489** [comment]
The devs have said they are only suppost to spawn in the other. but I cannot find that quote... I know there s a bug in skyblock builder apparently that stops things in the other dimention from generating.

**Comment by MelanX** [comment]
The bug is fixed. 
But the config says that fortresses are allowed to be generated. https://github.com/AllTheMods/atm6-sky/blob/master/config/skyblockbuilder/config.toml#L11-L13
However, this is an old config. They should re-generate it. And then remove the fortresses from the whitelist if they really don't want fortresses. So much S's.

**Comment by MushuPlatypus** [comment]
My Nether is a complete void.  When I do locate bastion or fortress I get a coord like this: -592 ~ -96, but when I go there there is nothing
