### ISSUE TITLE
HDPE Pellet

### ISSUE THREAD

**Issue by D3adCookie** [AllTheMods/atm6-sky#216]
So this was working fine the suddenly it stopped and I can't for the life of me figure out why. Anyone has any ideas? Everything is correct for the recipe of HDPE Pellet but it does not seem to go. 

![HDPEpellet](https://user-images.githubusercontent.com/40703368/114223185-caeecf80-996f-11eb-9454-34f439a969e3.PNG)

**Comment by MelanX** [comment]
Did you try to turn it off and on again?
And maybe you should consider visiting the ATM Discord server: https://discord.gg/K5FBPYa 
That way you'll get your answer faster. If your issue is already fixed (2 days are long), please close this :)

**Comment by jamest23** [comment]
Had the same issue. Turned out that if you have speed upgrades in there without energy upgrades it can't keep up. Putting 6/7 energy upgrades in allowed it to work for me.
