### ISSUE TITLE
Wither Builder - Industrial Foregoing

### ISSUE THREAD

**Issue by ImperialSlayer** [AllTheMods/atm6-sky#218]
Is the wither builder machine not supposed to work in claimed chunks? If I claim and/or force load a chunk, the builder just places the soul sand and not the wither skulls. As soon as claim/force load is removed from the chunk everything goes back to normal, and the builder places everything normally.
![Picture1](https://user-images.githubusercontent.com/82126799/114258202-d1824480-9979-11eb-9248-1d2cb1743ba2.png)

**Comment by tyler489** [comment]
does this occur outside a compact machine?

**Comment by Jan-aka-q0** [comment]
I think this is because the builder doesn't have permissions, make sure to ally it in the FTB teams menu

**Comment by MelanX** [comment]
If that fixed your issue, please close this. @ImperialSlayer

**Comment by ImperialSlayer** [comment]
Adding them as an ally got things working.
