### ISSUE TITLE
Some MA seed recipes missing ingridients from corners

### ISSUE THREAD

**Issue by minecrafterseppe** [AllTheMods/atm6-sky#22]
**Describe the bug**
certus quartz seeds have an invalid recipy
(see image)

**Expected behavior**
a certus quartz seed

![image](https://user-images.githubusercontent.com/13523046/110608151-418b8800-818c-11eb-8a8c-30694f2e14b6.png)

**Comment by WhitePhant0m** [comment]
https://github.com/AllTheMods/ATM-6/issues/775

**Comment by WhitePhant0m** [comment]
Seems like a newer version of MA fixes this issue, we will be including it in the next update :)
