### ISSUE TITLE
HDPE Pallets

### ISSUE THREAD

**Issue by D3adCookie** [AllTheMods/atm6-sky#220]
Upon putting 2 or more speed upgrades in a pressurized reaction chamber, it stops the production of HDPE Pallets. I don't know if this is supposed to happen or if it's a bug. 

**Steps to reproduce the behavior:**
1. Make a Pressurized Reaction Chamber
2. Put 2 or more speed upgrades in it
3. Try to make HDPE Pallets 

**Expected behavior**
I expected it to work with speed upgrades but perhaps it doesn't? 

**Screenshots**
![HDPEpalletspeed](https://user-images.githubusercontent.com/40703368/114265182-b5b98580-99ef-11eb-9a27-54576600cef4.PNG)
![HDPEpellet](https://user-images.githubusercontent.com/40703368/114265191-c23dde00-99ef-11eb-91a4-031e818f84d5.PNG)

**Additional context**
As I said before. I don't know if this is a intended feature or a bug

**Comment by D3adCookie** [comment]
I put in some Energy upgrades and now it works with all the speed upgrades. I have elite Universal Cable attached to the machine, shouldn't that be enough energy for it?

**Comment by tyler489** [comment]
Most likely the machine consumes more than it's buffer holds when sped up.

**Comment by D3adCookie** [comment]
> Most likely the machine consumes more than it's buffer holds when sped up.

I guess that's a intended feature?

**Comment by tyler489** [comment]
Indeed. According to their FAQ this intended

**Comment by D3adCookie** [comment]
> Indeed. According to their FAQ this intended

Alright. Thanks for clearing that up
