### ISSUE TITLE
Replace Allthemod Silver with IceandFire Silver

### ISSUE THREAD

**Issue by tyler489** [AllTheMods/atm6-sky#222]
**Is your feature request related to a problem? Please describe.**
Ice and fire villagers ask for Ice and fire silver as a trade and that silver is replaced with allthemodium silver 
**Describe the solution you'd like**
disable allthemod silver
**Describe alternatives you've considered**
Add a conversion for atm silver to IAF silver

**Comment by MelanX** [comment]
You can use the block `mekanism:oredictionificator` to convert ingots to other ingots.
Simply add a new filter, type in `forge:ingots/silver` and choose the ice and fire one. Then click save and drop all your silver ingots in.

**Comment by tyler489** [comment]
I didn't think that would work because the ice and fire silver is disabled (I think)

**Comment by MelanX** [comment]
It worked when I tried it yesterday

**Comment by tyler489** [comment]
huh I'll have to try it again  then
