### ISSUE TITLE
Add a way to obtain lilies from ice and fire.

### ISSUE THREAD

**Issue by tyler489** [AllTheMods/atm6-sky#223]
**Is your feature request related to a problem? Please describe.**
Its is impossible to obtain Lightning and Fire Lilies from ice and fire. you can buy ice lilies from the ice and fire villager but they dont sell lightning or fire lilies

**Describe the solution you'd like**
A custom Recipe or added to botanical miner Or change the ice and fire "stew" recipe you need to breed dragons

**Additional context**
You cant breed dragons without them

**Comment by kts325** [comment]
Is this still an issue?

**Comment by tyler489** [comment]
im not sure but i would assume so.

**Comment by Drunkender** [comment]
In ATM6 - Sky 1.1.8 there is a recipe for all the Ice and Fire lilies, so close issue?
