### ISSUE TITLE
Infinite honeycombs.

### ISSUE THREAD

**Issue by Vany** [AllTheMods/atm6-sky#224]
**Describe the bug**
infinite honeycombs.

**To Reproduce**
1. Put a honeycombs into a multiservo press with compacting dye.
2. uncraft the result.

**Expected behavior**
I think here economical balance will be.

**Screenshots**
https://www.youtube.com/watch?v=BxdQ183pA24

**Additional context**
to the sky 1.0.6.b

**Comment by Pdiddy973** [comment]
should be fixed in 1.0.8
