### ISSUE TITLE
Shift right click (highlighting)

### ISSUE THREAD

**Issue by realmaddawg** [AllTheMods/atm6-sky#225]
**Describe the bug**
since new update when I shift Right click certain things the block is highlighted but desired task will not complete. examples. placing upgrade on pedestal (off hand works) however removing cardboard boxes will not work.

**Comment by acelel** [comment]
I can't seem to upgrade pedestal with my main hand either

**Comment by D3adCookie** [comment]
The update to Pedestals made it so you put on a upgrade with your off hand

Full list of updates to the mod: 
https://www.youtube.com/watch?v=N3Doz6OKjmY&t=109s

**Comment by realmaddawg** [comment]
I also highlight the other portal with empty hands rather than teleporting.
