### ISSUE TITLE
AE2 Pattern Can't set to process some Mekanism recipe

### ISSUE THREAD

**Issue by AlphaP2712** [AllTheMods/atm6-sky#227]
AE2 Pattern Tell That Mekanism recipe Like Redstone to Enriched Redstone

**To Reproduce**
1. Go to AE2 ME Pattern Terminal and set to Processing pattern
2. Click on JEI Enriched Redstone
3. Try to get recipe of  Enriched Redstone use Enriched chember
4. See error That Tell recipe is no output

**Expected behavior**
Get recipe to Make pattern normally.

![image](https://user-images.githubusercontent.com/74948675/114282148-6bc2b500-9a6c-11eb-9374-3ee76d0ea9e5.png)

**Comment by Pdiddy973** [comment]
This is more of a AE issue, you can just make the pattern manually and it will work fine
