### ISSUE TITLE
Wrong recipe for Stoned Bee

### ISSUE THREAD

**Issue by DrMrPotatoe** [AllTheMods/atm6-sky#228]
**Describe the bug**
In JEI, the recipe for the stoned (rocky) bee is listed as cobbee + Lava bee, and it is clearly not working,

**To Reproduce**
1. get both cobbee and Lava bee to their love stage by feeding them the required materials
2. make sure both bees have hearts 
3. nothing happens

**Expected behavior**
both bees should breed and give me a stoned bee.

**Comment by Pdiddy973** [comment]
Stoned bee is properly renamed as stoned, "rocky" should exist any more, breed chance is 60% iirc, it can and probably will fail atleast once

**Comment by DrMrPotatoe** [comment]
I mean that they r not even atracted to each other
