### ISSUE TITLE
Bee Apiary

### ISSUE THREAD

**Issue by ShadySnare** [AllTheMods/atm6-sky#230]
**Describe the bug**
I am trying to build apiary but I dont see the tag for the items I can use. In sky bee you can use glass/ mana glass but when I tried both it rejected it
**To Reproduce**

**Comment by ghingis** [comment]
Glass has the `valid_apiary` tag, mana glass does not, if you can't see the tags, try pressing the F3+h buttons at the same time (when there is nothing open). After that you can press ctrl and you will se the tags.

**Comment by MelanX** [comment]
Mana Glass does have the tag. Every glass has. At least in 1.0.6b.

**Comment by ShadySnare** [comment]
https://prnt.sc/119tbtq
Umm it still says not working

**Comment by ShadySnare** [comment]
I check glass / dark oak and it still says the sides are invaild

**Comment by ghingis** [comment]
> Mana Glass does have the tag. Every glass has. At least in 1.0.6b.
> So this can be closed.

You are right, my bad..

**Comment by ghingis** [comment]
> https://prnt.sc/119tbtq
> Umm it still says not working

Apiary structure should be a 5x5x4 afaik.

**Comment by MelanX** [comment]
I think it's one too high what you built. I counted 7 layers, should only be 6.
