### ISSUE TITLE
I cant play on my saves

### ISSUE THREAD

**Issue by Lolz999** [AllTheMods/atm6-sky#232]
**Describe the bug**
When I create new world it does load but when I restart minecraft after playing for a while I can not play on that save :( 
Anyone can help?
**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by servireettueri** [comment]
My saves and the backups got deleted out of the blue a couple days ago, Then my new world and the backups got corrupted the day before yesterday. This mod pack is just really unstable. I always back up to an a separate hard drive now  to prevent them from being modified.
