### ISSUE TITLE
Items popping out of inventory when loggin on

### ISSUE THREAD

**Issue by DavUp7** [AllTheMods/atm6-sky#233]
Whenever I log into my own server, all of the items in my inventory have been ejected out around me, it has even made me lose some items in the void.

I play with one of my friend and it never happened to him.

I always have the last version available of the mod pack.

I'd like if you could find a fix to this.

**Comment by MelanX** [comment]
Can you provide your level.dat and you data/skyblock_builder.dat in the world file?
Also all player names or uuids. 
Did you create a team? If yes, which name?

**Comment by DavUp7** [comment]
> Can you provide your level.dat and you data/skyblock_builder.dat in the world file?
> Also all player names or uuids.
> Did you create a team? If yes, which name? And what's the modpack version you started playing?

Thanks for the reply.
I will check and send that out tonight!

**Comment by DavUp7** [comment]
> Can you provide your level.dat and you data/skyblock_builder.dat in the world file?
> Also all player names or uuids.
> Did you create a team? If yes, which name? And what's the modpack version you started playing?


Here are the two files you asked. [files.zip](https://github.com/AllTheMods/atm6-sky/files/6300739/files.zip)
Player name are : DavUp (mine) and Harley48 (my friend).
I think we simply added ourselves as allies, if not well team name must be one of our names.
We started playing in the 1.0.5 version.

**Comment by MelanX** [comment]
[skyblock_builder.zip](https://github.com/AllTheMods/atm6-sky/files/6303436/skyblock_builder.zip)
Try using this. Just replace the current file. It should fix your problem. If yes, please close this issue :) if not, tell me and I try to find another solution!
But it should be fixed now because you wasn't set to team "Spawn". And now you are :)

**Comment by DavUp7** [comment]
> [skyblock_builder.zip](https://github.com/AllTheMods/atm6-sky/files/6303436/skyblock_builder.zip)
> Try using this. Just replace the current file. It should fix your problem. If yes, please close this issue :) if not, tell me and I try to find another solution!
> But it should be fixed now because you wasn't set to team "Spawn". And now you are :)

The file worked ! Thanks a lot for your help.

**Comment by 19175** [comment]
I'm having the same problem, and it appears https://github.com/AllTheMods/atm6-sky/issues/502 https://github.com/AllTheMods/atm6-sky/issues/488 and https://github.com/AllTheMods/atm6-sky/issues/457 are too, could this be fixed or instructions on how to fix be put somewhere?

**Comment by MelanX** [comment]
If no multiplayer server or just for friends: there is a config option to disable dropping the inventory. This should be the easiest fix. I do not exactly know what went wrong but it’s the fault of Skyblock Builder.
