### ISSUE TITLE
game crashes when try to exit the screen in rf tools

### ISSUE THREAD

**Issue by Ddollz** [AllTheMods/atm6-sky#234]
**Describe the bug**
I really don't know what happened. this happened when i was trying to add text screen in rf tool and i accidentally click "`" instead of "exc" i saw my sword in the screen slot instead of the text screen module. i've been trying to restart but still keep crashing when i load my save how do i fix this?

pastebin: [Client](https://controlc.com/4599c817) (I THINK pastebin is down so i used this instead)
pastebin: [Server](https://controlc.com/c385c77b)

**Comment by MelanX** [comment]
could you please use pastebin to send the report? It's aweful to try to read this.

**Comment by Ddollz** [comment]
> could you please use pastebin to send the report? It's aweful to try to read this.

sorry post updated

**Comment by Ddollz** [comment]
Kinda Fixed the crash but i had to remove rf mod from mods folder and load the save then leave the save and then add the rf mod then load again. i just lost my hotbar items.
