### ISSUE TITLE
Industrial Foregoing - baby filter?

### ISSUE THREAD

**Issue by Vertigo81** [AllTheMods/atm6-sky#236]
Trying to automate pink slime, and from what I read everywhere there should be a filter I can put in the mob slaughter factory or baby separator to let them filter for adults.  But it doesn't seem to be in the Pack?

I also notice that like ALL aspects of the IF GUI seem different than all the videos, tutorials and wikis.  What's going on?  Are these features not brought to 1.16 yet?  Or am I missing something.

If they don't exist, anyone got a way to accomplish the same goal without them?  (god I hate IF)

**Comment by MelanX** [comment]
You can use the baby selector to put them in the area for the slaughter factory. When they are adults, they will be killed.

**Comment by Vertigo81** [comment]
It actually kills them immediately as babies.  Which provides much less pink slime than adults.  Im asking about the filter for this exact purpose - it is supposed to prevent them being killed until adulthood.

https://ftb.fandom.com/wiki/Adult_Filter

But it doesn't seem to exist in the pack.

**Comment by MelanX** [comment]
The only way seems to be: use two baby separators. One to put babies in a new area and another one to put adults in the killing area.

**Comment by Vertigo81** [comment]
Tried that too.  The separator doesn't seem to move adults, only babies.  The filter is also used for that purpose (inverting the separator)

**Comment by MelanX** [comment]
Okay, then... I'm out of ideas.

**Comment by Vertigo81** [comment]
Yeah me too >_<. That's why I came here hoping I'd missed something.    Hoping someone at least knows the reason why IF seems to be different in this pack than all the tutorials online.

**Comment by Topside08** [comment]
![image](https://user-images.githubusercontent.com/37430351/114325020-c9eaa900-9afb-11eb-99f7-e92f28746e60.png)
This thing is a toggleable button

**Comment by Vertigo81** [comment]
*facepalm*
Okay.  Well, still curious why all the GUI's are completely different from all the faqs >_<. Thank you.

**Comment by Topside08** [comment]
they changed some stuff in the 1.16 update but they don't seem that different than the 1.12 machines to me maybe I just didn't use them much though
you should close this

**Comment by Vertigo81** [comment]
fair duff
