### ISSUE TITLE
A lot of Mystical Agriculture metal seeds are missing ingredients.

### ISSUE THREAD

**Issue by ashduino101** [AllTheMods/atm6-sky#24]
Some mystical agriculture metallic seeds like zinc seeds do not have a proper recipe, instead, they only have the essence and base seed in the recipes.

![image](https://user-images.githubusercontent.com/67023707/110675820-2dde2280-8188-11eb-9a97-aac773c69317.png)

For example, these silver seeds cannot be crafted.
I believe this is because of AllTheOres.

**Comment by WhitePhant0m** [comment]
duplicate of #22
