### ISSUE TITLE
Compressed Gravel from the Compressium Mod isn't compatible with Auto Compressed Sieve

### ISSUE THREAD

**Issue by Tewt715** [AllTheMods/atm6-sky#243]
**Is your feature request related to a problem? Please describe.**
I made an Auto Compressed Sieve (ACS) so I could make my ore production faster. But the issue I came across is I can't put compressed gravel from the Compressium mod into the ACS. 

**Describe the solution you'd like**
My solution would be to find a way to put compressed gravel from the compressium mod into the container of the ACS. Possibly having the same tags that the compressed gravel does from the Ex Compressum mod.

**Describe alternatives you've considered**
Another solution would be to revert back to Ex Compressum compressed gravel because the ACS is from the same mod.

**Additional context**
I know its not that big of an issue but for the certain use of compressed gravel it is!

**Comment by MelanX** [comment]
You mean the gravel from compressium? It works for me. Which pack version do you use?

**Comment by Tewt715** [comment]
I'm on v1.0.6b, and the compressium gravel isnt going into the container of the Auto Compressed sieve.  It works for the regular Heavy Sieve fine.

**Comment by Tewt715** [comment]
nvm im an idiot, im using a regular sieve LOL.
