### ISSUE TITLE
Creative Crafter Block Interactions

### ISSUE THREAD

**Issue by Veil11** [AllTheMods/atm6-sky#244]
This is all in a singleplayer world, idk if it makes a difference but there you go.

When a creative crafter is facing certain modded machines it either creates lag, slows the machine down significantly, or both. So far I've found it lags and slows down induction smelters from Thermal Series and metallurgic infusers/infusing factories from Mekanism. It does not have this issue with any of the furnaces from Iron Furnaces or the pulverizer from Thermal Series. I have not tested on all machines though

1. Place an induction smelter/infuser
2. Put a creative crafter attached to it with a recipe to autocraft
3. Try to autocraft the recipe

Any tier below creative works fine. Netherite, Diamond, Gold, and Iron crafters work as expected with no issues in my experience. When I replaced the creative crafter on my infusing factories with netherite ones the machines ran at their expected speed and there was no lag.

**Comment by Arnaen** [comment]
I have the same problem on the server.
The server always crashes for me.
I must then download the world and load the world in single player.
Let all crafters finish their work.
And then upload the world back to the server....

**Comment by starforcraft** [comment]
I will soon™ make a Performance fix for Creative Crafter currently I don't have much time and desire to fix that lol
