### ISSUE TITLE
Teleport pad is not working on server.

### ISSUE THREAD

**Issue by Electrofried** [AllTheMods/atm6-sky#247]
At title, running version 1.0.6b of the pack. 
Placed down the portal block in the nether.
Server throws the following error when a player uses the block:
https://pastebin.com/Gmyz3BsL

**Comment by AnassZaki** [comment]
Are you also having problems with compact machines?

**Comment by Electrofried** [comment]
> Are you also having problems with compact machines?

Yes

**Comment by Electrofried** [comment]
To confirm this is still an issue in 1.0.7

**Comment by oly2o6** [comment]
Mods were updated in 1.0.8 as i cannot seem to reproduce either issue, ill close for now
