### ISSUE TITLE
File Integrity crash

### ISSUE THREAD

**Issue by Jumper2512** [AllTheMods/atm6-sky#248]
I started a LAN hamachi server with my friend (he is hosting it), After the 1.0.6 to 1.0.6b update i can't connect to his server because of missing files crash report, We tried going back a version to 1.0.6 even to 1.0.5 but it still sends the same crash report.
We tried dleting the mods from both of our clients and going into the server files to completely delete my player data but it did not help either. New worlds created on 1.0.6b work just fine, its just the one ported from 1.0.6 that has this problem.

![image](https://user-images.githubusercontent.com/82384699/114394173-323c9780-9b9b-11eb-88df-346c16ee04f7.png)

**Comment by Jumper2512** [comment]
Okay some new info, We asked our other friend to join with a fresh instalation of the pack and he gets the same crash log. So is the map just corupted and we wont be able to use it as a server anymore?

**Comment by Jumper2512** [comment]
Update 1.0.7 same problem
![image](https://user-images.githubusercontent.com/82384699/115115898-2d128a80-9f97-11eb-9dca-03bdda0b9c19.png)

**Comment by juniors74335** [comment]
Same error there, happen after 5 days of play on one world, and 2 hours after the second world.

**Comment by Jumper2512** [comment]
I hope somebody can whip up a solution soon....

**Comment by Jumper2512** [comment]
1.0.8 Still the same issue with worlds created on 1.0.7 as well as older ones.

**Comment by oly2o6** [comment]
i have not seen the issue apart from the 2 of you above, ill look into it further and try to reproduce but ill be closing it for now
