### ISSUE TITLE
Overgrowth Seed ,Tier 4,5 Dragons Not Spawning And Bees

### ISSUE THREAD

**Issue by Mifwiin** [AllTheMods/atm6-sky#249]
Why there is no crafting recipe for overgrowth seed. I know i have to find it in dungeons or something but there is none. Is there a anyway to get it 

I searched The Other for hours but i think tier 4 or 5 dragons are not spawning. I searched underground and surface but theres none i could find.

I obtained the craftable bees and i want to progress to the allthemodium bee but there is no breeding recipe how do i get one and i think lava and cobee are bugged cuz they dont breed.

**Comment by Vertigo81** [comment]
Did you update this past week and reset your Other?  I don't know how to check their rank, but I've found a bunch with 30k+ health.  Think they're tier 4 or 5 judging by the size and descriptions I've seen.  The biggest ones I've found have been in nests on the surface, mostly in the mountain biome.

**Comment by Mifwiin** [comment]
No i didnt reset my Other, how can i do that ?

**Comment by Vertigo81** [comment]
You delete the dimension folder from your save.  Make a backup first.

**Comment by Mifwiin** [comment]
Okay, thank you.

**Comment by Mightylight** [comment]
overgrowth seeds can be obtained by doing gaia fight tier 2, instead of a terrasteel ingot for start gaia use a gaia spirit ingot

**Comment by Mifwiin** [comment]
What is the drop rate on that beacuse i fighted the tier 2 for at least 6 or 7 times but thanks i will do that
