### ISSUE TITLE
Two recipes for the diamond ring and angel ring

### ISSUE THREAD

**Issue by ashduino101** [AllTheMods/atm6-sky#25]
There are 2 recipes for the diamond ring and angel ring, the KubeJS added ones, and the default ones.
![image](https://user-images.githubusercontent.com/67023707/110676698-19e6f080-8189-11eb-9ac7-91d05a6d95f0.png)
![image](https://user-images.githubusercontent.com/67023707/110676721-24a18580-8189-11eb-882b-02b57ff28acf.png)

**Comment by WhitePhant0m** [comment]
Fixed in commit 0c640ccbcc8a5b6ddddd231a07cb87b3eb4dcd15

**Comment by WhitePhant0m** [comment]
Update to 1.0.2
Fixed in that version.
