### ISSUE TITLE
How to breed obsidian bee

### ISSUE THREAD

**Issue by DrWKool** [AllTheMods/atm6-sky#250]
I am trying to get the bees done
for the obsidian bee I need water and lava bee (both crafted the eggs)
To breed I need 5 rune of water and 5 lava crystals. 
One issue, the lava crystals do not stack, so using the breeder in apiary doesn't work
also breeding the bees outside the apiary doesn't work. They both have hearts, but doesn't want to mate

please help! I need the obsidian bee to get more diamonds

**Comment by Pdiddy973** [comment]
should be fixed in 1.0.8
