### ISSUE TITLE
RAM after 2 hours full

### ISSUE THREAD

**Issue by Knoxxar** [AllTheMods/atm6-sky#251]
After 2 Hours the server run into the RAM Limit of 10GB, but nobody online and i had unloaded all chunks.  
I've tried various of startarguments and java version, always the same result.

My server runs with Pterodactyl and Docker-Container. Java 11 and follwing arguments:

`java -Xms128M -Xmx10000M -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=40 -XX:G1MaxNewSizePercent=50 -XX:G1HeapRegionSize=16M -XX:G1ReservePercent=15 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=20 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -Dfml.readTimeout=90 -Dfml.queryResult=confirm -jar forge-1.16.5-36.1.2.jar`

I added some logs to check.
[2021-04-13-3.log.gz](https://github.com/AllTheMods/atm6-sky/files/6303052/2021-04-13-3.log.gz)
[debug-4.log.gz](https://github.com/AllTheMods/atm6-sky/files/6303058/debug-4.log.gz)

If somebody have an idea whats the problem is, plz post it.
Grz Knoxxar

**Comment by jimbo80008** [comment]
generally memory leaks to this degree happen due to buggy interactions, perhaps concider using java 8, because although older and much less safe, every mod seems to have support for that.
also i could just be a mod bugging out. also forge is a bit uncoöperative a times.

**Comment by swardhagen** [comment]
I haven't tried this on a server, but installing optifine seems to help most people having ram issues on single player.
