### ISSUE TITLE
Resourceful bee, missing Flower

### ISSUE THREAD

**Issue by Arnaen** [AllTheMods/atm6-sky#253]
I play on ATM Sky 1.0.6b.
I was about to start producing bees and found out that many of the bees do not have a flower to create honeycombs (pollination).
If the bees do not produce honey (pollination), they cannot make mutations.

![Bee1](https://user-images.githubusercontent.com/30075335/114589278-cf74fa00-9c87-11eb-8372-97fae58c28db.PNG)
.
.
.
.
.
Attached is a list:
.
.
- Bees with flower:
.
![Bee2](https://user-images.githubusercontent.com/30075335/114589458-f7645d80-9c87-11eb-9692-1252d99ef682.PNG)
.
.
  - Aquamarine
  - Blazing
  - Certus
  - Cropy
  - Ender
  - Fluorite
  - Guardian
  - Icey
  - Lava
  - Magma
  - Mana
  - Mystical
  - Redstone
  - Slimy
  - Soul Lava
  - Spooky
  - Water
.
.
.
.
.
- Bees without flower:
.
![Bee3](https://user-images.githubusercontent.com/30075335/114589691-32669100-9c88-11eb-88ac-adae0fb5c0cb.PNG)
.
.
  - Allthemodium
  - Aluminium
  - Beeper
  - Coal
  - Cobbee
  - Copper
  - Crimson
  - Diamond
  - Draconic
  - Emerald
  - Glowing
  - Gold
  - Gravely
  - Iron
  - (kitten)
  - Lapis
  - Lead
  - Leafy
  - Lumber
  - Masion
  - Netherite
  - Nickel
  - Obsidian
  - (Oreo)
  - Osmium
  - Platinum
  - Quartz
  - RGBee
  - Sandy
  - Silver
  - Spider
  - Stoned
  - Tin
  - Unobtainium
  - Uraninite
  - Uranium
  - Vibranium
  - Wither
  - Withered
  - Zinc
  - Zombee
.
.
.
I hope that there will be an update at some point.

Thanks Arnaen

**Comment by Pdiddy973** [comment]
They do have a flower, it's a sync issue where when I use tags (most of them do) it does not show properly, to fix this join single player first then back to multiplayer

**Comment by Arnaen** [comment]
Ahhhmm...
4 hours of trying out everything possible...
Reinstall server, reinstall client.
all nothing....

The only thing I didn't test was the singleplayer....

In any case thanks for the help.... 

this has solved all problems....
