### ISSUE TITLE
Placing the 4th projector for "compact crafting" causes the game to crash. I've tried the smallest and largest size. I don't want to try the others though it takes forever to reload the game.

### ISSUE THREAD

**Issue by servireettueri** [AllTheMods/atm6-sky#254]
When you place the 4th projector in a formation it will crash the game.

**To Reproduce**
Just place 3 projectors in the correct positions and then try to place the fourth. It instantly crashes the game. Will do it every time. I tried 5 times. 

I forgot to copy the error message and would rather not crash my game again.

**Comment by Jacobus619** [comment]
Compact Machines are craftable in the pack

**Comment by Jacobus619** [comment]
> Compact Machines are craftable in the pack

check through jei

**Comment by kts325** [comment]
Recipes changed since then.
