### ISSUE TITLE
double click on single click

### ISSUE THREAD

**Issue by Malavisto** [AllTheMods/atm6-sky#255]
The Bug
Double click when i try to craft a tool in the tinkers station or when i click on a recipe in the quest book

1. Use a Tinkers station or open a quest with a item requirement e.g Iron chest
2. Click on a recipe

**Expected behavior**
Expect it to click once on a single click

**Comment by Malavisto** [comment]
Only does this when I use left click for action/place block and right click for destroy block

**Comment by oly2o6** [comment]
not reproduceable in my tests (with version 1.0.9) so i will close this for now

**Comment by KodYazanDruid** [comment]
It happens to me. I don't know what couses but it happens only in GUI's.
