### ISSUE TITLE
honey produced in centrifuges can't work to create honey blocks 

### ISSUE THREAD

**Issue by Nightstar10** [AllTheMods/atm6-sky#256]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Nightstar10** [comment]
sorry I didn't clarify the honey from the centrifuges can't be used in the thermal series blast chiller to make honey blocks

**Comment by EnzoBenzo1** [comment]
Its a different type of honey if that's what you are having an issue with. You added the enhancement label so I assume you are asking for it to be compatible?

**Comment by DrWKool** [comment]
yes please, I have the same issue and it would be nice that all honey is oredictionary with each other. I want to use the cyclic machines

**Comment by Pdiddy973** [comment]
should be fixed in 1.0.8
