### ISSUE TITLE
Mystical agriculture watering can disappears in clicker

### ISSUE THREAD

**Issue by MushuPlatypus** [AllTheMods/atm6-sky#257]
Describe the bug
Watering can disapears after a while when placed in an auto clicker

To Reproduce
Place an Imperium watering can in an auto clicker (Cyclic, ClickMachine).
After a while the watering can disappears.

Expected behavior
The watering should not disappear

Versions (please complete the following information):

Minecraft: 1.16.5
ATM 6: To the sky
Mystical Agriculture: 1.16.4-2.1.2

**Comment by MrStatman80** [comment]
Since 1.7.10 and .116.2 mod authors as been disabling watering cans in auto users as it's op

So if they disappearing it's due to using the water and then disappeared due to it

But ask the mod author of mystical thou not on here

**Comment by MrStatman80** [comment]
> Describe the bug
> Watering can disapears after a while when placed in an auto clicker
> 
> To Reproduce
> Place an Imperium watering can in an auto clicker (Cyclic, ClickMachine).
> After a while the watering can disappears.
> 
> Expected behavior
> The watering should not disappear
> 
> Versions (please complete the following information):
> 
> Minecraft: 1.16.5
> ATM 6: To the sky
> Mystical Agriculture: 1.16.4-2.1.2


But to answer you really use Pedestal mod as they got a fast growing upgrade using this modpack
