### ISSUE TITLE
Slope visual bug

### ISSUE THREAD

**Issue by Catandcomparator** [AllTheMods/atm6-sky#258]
for some reason, an upside down framed slope has a wonky side texture.

just place a framed slope upside-down and look at the side.

i expected it to look normal and not buggy

![2021-04-14_12 21 40](https://user-images.githubusercontent.com/75269826/114745038-48be2c80-9d1c-11eb-9886-02e90216842c.png)
![2021-04-14_12 23 25](https://user-images.githubusercontent.com/75269826/114745048-4a87f000-9d1c-11eb-8b28-1c09d07e045d.png)

**Comment by Elpximso** [comment]
I made a post about this on the mods github (This is my post: https://github.com/XFactHD/FramedBlocks/issues/14)

Its a issue with optifine and can be fixed by following these steps: https://github.com/XFactHD/FramedBlocks/issues/5

**Comment by XFactHD** [comment]
@Elpximso I have to correct you here, this issue has nothing to do with the light pipeline settings mentioned in XFactHD/FramedBlocks#5.

@Catandcomparator Please refer to XFactHD/FramedBlocks#6 for how to fix this issue.

**Comment by Elpximso** [comment]
Ohhh right, I don't know why I thought shading issues😅

**Comment by Catandcomparator** [comment]
thanks XFactHD!!!
