### ISSUE TITLE
Add Minecolonies to the pack

### ISSUE THREAD

**Issue by BlackStone5677** [AllTheMods/atm6-sky#259]
**Is your feature request related to a problem? Please describe.**
I wanted to play with minecolonies in ATM6, but when I was gonna do it I felt done with the pack. and now that I wanna play the sky version I saw it as an opportunity that would allow me to play with it and allow the pack to have SKY COLONIES, how cool is that ey

**Comment by Elpximso** [comment]
You can just add the mod yourself, i dont personally think playing with mine colonies on a skyblock would be fun, but adding it shouldnt be hard :)

**Comment by bloodscon** [comment]
lol how many villages can you send to the void :)

**Comment by oly2o6** [comment]
this wont be added, i just dont feel it fits the pack
