### ISSUE TITLE
Remove AE2 cable facades from JEI

### ISSUE THREAD

**Issue by nddragoon** [AllTheMods/atm6-sky#26]
**Is your feature request related to a problem? Please describe.**
It's kind of really annoying to have hundreds upon hundreds of facades spamming the item list when looking for a specific item

**Describe the solution you'd like**
Hide `appliedenergistics2:facade` from the items list in JEI

**Comment by DaveJK** [comment]
`@appliedenergistics -facade` in JEI

**Comment by nddragoon** [comment]
I know i can exclude them from searches manually, but the issue isn't just when searching AE2. they show up when looking for builkding blocks, they show up when searching for cables, they show up when just scrolling through JEI, and i dont wanna have to constantly manually exclude them from searches. Also they're already hidden from JEI in the non-skyblock version

**Comment by WhitePhant0m** [comment]
they should already be hidden, tho might be broken in the release since it had some broken scripts, works in the dev version at least

**Comment by WhitePhant0m** [comment]
should be hidden again in 1.0.2
