### ISSUE TITLE
Placer issues

### ISSUE THREAD

**Issue by Catandcomparator** [AllTheMods/atm6-sky#260]
for some reason, certain block placing machines are not working for me. the wither builder cannot place skulls but can place soul sand, and deployers cannot place spruce saplings. i have not experienced placing issues with the cyclic placers and pedestal placing upgrades, however.

**Comment by mkleiman312** [comment]
If this is happening in claimed chunks, then you need to go into the FTB Chunks menu and "ally" the placing/breaking machines. It is sometimes necessary to redo this on restart as well.
