### ISSUE TITLE
Bees are a lot broken

### ISSUE THREAD

**Issue by Merthew** [AllTheMods/atm6-sky#263]
Just wanna point out a few issues with bees and wondering if they were intentional. First, bees that use unstackable items as their breeding thing. Was that intentional? Cause if it was it sucks. You can't breed them in the apiary breeder and most of the time when you finally get both bees to eat all five individual stacks the other bee has lost the love hearts, then specifically in the case of the lava and water bee, they never actually found each other. Was that intentional?

Other thing here, I noticed there is no way to get the wither bee, which is required for getting stuff like the allthemodium, vibranium, and unobtainium bees. I am assuming this is just not implemented yet?

**Comment by Pdiddy973** [comment]
should be fixed in 1.0.8
