### ISSUE TITLE
Basalz not spawning in other

### ISSUE THREAD

**Issue by Catandcomparator** [AllTheMods/atm6-sky#264]
basalz from thermal series do not seem to be spawning in the other.

go to a mountainous biome in the other, according to the thermalpedia, basalz should spawn there, but they do not.

**Comment by swardhagen** [comment]
I've seen many of them in the other while flying. They are rarer than blaze, though, so I think you'll just have to look around a bit more.

**Comment by Catandcomparator** [comment]
blaze are everywhere, and i have seen blizz and blitz occasionally. but not
a single basalz.

**Comment by swardhagen** [comment]
I just popped back in and realized you're absolutely right. I confused them with the blizz mob, I haven't seen a single basalz either when I think about it. Is there another dimension that we haven't checked in, maybe?

**Comment by Catandcomparator** [comment]
no. the nether and end are not supposed to have them, and the mining
dimension is inaccessible. basalz CAN spawn, but only ridiculously
rarely in the overworld.

**Comment by oly2o6** [comment]
might review the spawn rates but for now ill close
