### ISSUE TITLE
Compacting Drawers Doesn't recognizes Aluminum Block/Ingot

### ISSUE THREAD

**Issue by SwarabRaul** [AllTheMods/atm6-sky#268]
**Describe the bug**
If we insert an Aluminum Block or ingot into an empty compacting drawer, it doesn't recognize the recipe related to the item(Block>Ingot>Nugget or Ingot>Nugget). This is not an issue when we insert an Aluminum nugget first into the compacting drawer.

**To Reproduce**
1. Take an Aluminum ingot
2. Right-Click on an empty compacting drawer
3. You will find that only the recipe for the block will be shown.
4. Nugget recipe is not visible.
5. The same thing can be reproduced with an Aluminum block as well. The only difference is that neither the ingot nor the nugget recipe will be shown.

**Expected behavior**
When we insert an Aluminum Block or Ingot, I want the compacting drawer to show all recipes to it.

**Screenshots**

1. When we insert an Aluminum Block First: 
![image](https://user-images.githubusercontent.com/80309831/115037695-5f1ae280-9eec-11eb-9a49-7d75441490a5.png)

2. When we insert an Aluminum Ingot First:
![image](https://user-images.githubusercontent.com/80309831/115037523-2d098080-9eec-11eb-999e-87338bebb446.png)

3. When we insert an Aluminum Nugget First(**This is the expected result needed**):
![image](https://user-images.githubusercontent.com/80309831/115037734-680bb400-9eec-11eb-947b-7b11f25727c9.png)

**Comment by mkleiman312** [comment]
It's worked this way forever in packs with complex/overlapping ore recipes. Just put the nuggets in first, then lock the drawer. Problem solved.

**Comment by SwarabRaul** [comment]
Aha... I see, I just started playing with modded Minecraft recently, so I had no idea about it. Thanks a lot though!!
