### ISSUE TITLE
Extra Storage (Refined Storage Add on) Iron-Netherite Crafters not showing redstone toggle on server only.

### ISSUE THREAD

**Issue by Karan-Sidhu** [AllTheMods/atm6-sky#270]
While playing on 1.06b the crafters worked up until I moved one with the redstone toggle switched to insert on next pulse. The button's no longer worked but were still there. I had deemed it a bug and luckily there was the 1.07 update so I thought I could update to fix, but now the crafter's buttons are gone but once going into a singleplayer world they reappear. The normal crafter still works but I need bulk botania auto crafting so the upgraded crafters are necessary.

**Comment by oly2o6** [comment]
would recommend reporting this to the respective author/s if not fixed in 1.0.8
