### ISSUE TITLE
@enviomantal tech

### ISSUE THREAD

**Issue by Rapchor** [AllTheMods/atm6-sky#271]
Try to built the litherite void miner form @enviromental tech - auto build didn' t finish the build, when fishes manual the structure does't work

**Comment by geeee785** [comment]
you're doing it wrong then, I just built one an hour ago, the only part that doesn't finish on auto build is it doesn't recognize the extra frames to replace the extra input/output.  if you go with an fe input and item output, you need to have 2 extra frames to go in the spots that are missing.
