### ISSUE TITLE
the end dimension not generating the main island 

### ISSUE THREAD

**Issue by khaled9782** [AllTheMods/atm6-sky#272]
I wanted to go the the end and after looking through the jei, I saw that I had to craft an ender cake. After eating the cake,I was teleported to the end dimension on an obsidian platform. I did not spawn in the island so I used the jetpack to fly around and look for the end island but the only thing that was there were the obsidian pillars. No island, no ender dragon and no portal to go back to the overworld. since there was no portal I cheated and used the `/spawn` command to go back the overworld

**To Reproduce**
1) create a world 
2) craft an ender cake 
3) eat it and you will be teleported to an obsidian platform 
4) the main island will not be around 

**Expected behavior**
after eating the cake I spawned in an obsidian platform without the main Island anywhere close

**Screenshots**
https://imgur.com/a/hatXwvV   
I took this screenshot with night vision active and removed HUD with f1

**Comment by GalacticTurtle01** [comment]
I had the same problem my end island is just the towers to end portal and no dragon just end towers

**Comment by khaled9782** [comment]
> I had the same problem my end island is just the towers to end portal and no dragon just end towers

this is the same thing that happened to me just the obsidian towers. no dragon and no portal to go back to the overworld. so for now I just use the `/spawn` command to go back to the overworld

**Comment by GalacticTurtle01** [comment]
Is there supposed to be a fix or how do we get quark dragon scales

**Comment by Mightylight** [comment]
i don't think there's a fix. I think it's just because it is an old world. i've not seen anyone anymore that have this problem. so the only fix would be a new world i guess
