### ISSUE TITLE
1.0.7 - Create Crafting Bug

### ISSUE THREAD

**Issue by Merthew** [AllTheMods/atm6-sky#276]
**Describe the bug**
Tried crafting a Create Furnace engine, got reliquary storm shot.

**To Reproduce**
![image](https://user-images.githubusercontent.com/23420800/115135643-f022b400-9fe7-11eb-80d2-cbf7b7675d99.png)
Had my setup like this since the furnace recipe is only a 3x3 but I needed the star shape for the ATM star.
Put in the ingredients for a furnace engine: 
![image](https://user-images.githubusercontent.com/23420800/115135685-3aa43080-9fe8-11eb-91d7-00f9f5709be4.png)
Then got storm shot:
![image](https://user-images.githubusercontent.com/23420800/115135692-4e4f9700-9fe8-11eb-98c7-8be106c518dd.png)

**Additional context**
Playing on 1.0.7, not had really any other big bugs so far, besides Bee mutations not working in the slightest.

**Logs**
No crash so not sure what to tell you here.

**Comment by kts325** [comment]
Seems to be an issue with create itself that has seemingly worked itself out since then
