### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by Pawerny** [AllTheMods/atm6-sky#278]
Hello, can you help me with this? We just can join the 1st time and if we relog we get this error, we change java and not work.
![Screenshot_3](https://user-images.githubusercontent.com/21323634/115305500-53ceed80-a15e-11eb-9809-9dd7c69a0e8d.png)

**Comment by leku451** [comment]
several of us having same issue as well

**Comment by oly2o6** [comment]
reupload configs from client to server (or use a fresh install)
