### ISSUE TITLE
XP Tap bug crashes world

### ISSUE THREAD

**Issue by kaotte2** [AllTheMods/atm6-sky#279]
I placed an xp tap from mob grinding utils on an enchantment factory to get the rest essence out, this crashed my game with exit code 0. after restarting the game it loads the world to 100% then crashes again with exit code 0 

-- every crash report i have with atm 6 sky -- 

[crash-2021-04-18_20.09.33-server.txt](https://github.com/AllTheMods/atm6-sky/files/6339199/crash-2021-04-18_20.09.33-server.txt)
[crash-2021-04-18_20.12.05-server.txt](https://github.com/AllTheMods/atm6-sky/files/6339200/crash-2021-04-18_20.12.05-server.txt)
[crash-2021-04-18_20.14.30-server.txt](https://github.com/AllTheMods/atm6-sky/files/6339201/crash-2021-04-18_20.14.30-server.txt)
[crash-2021-04-18_20.28.00-server.txt](https://github.com/AllTheMods/atm6-sky/files/6339202/crash-2021-04-18_20.28.00-server.txt)
[crash-2021-04-19_20.59.30-server.txt](https://github.com/AllTheMods/atm6-sky/files/6339203/crash-2021-04-19_20.59.30-server.txt)
[crash-2021-04-19_22.21.53-server.txt](https://github.com/AllTheMods/atm6-sky/files/6339204/crash-2021-04-19_22.21.53-server.txt)

-- saves --
i have attached 2 world "Skyblock" is the gliched one and "test" is where i tried to reproduce the bug 
[worlds.zip](https://github.com/AllTheMods/atm6-sky/files/6339262/worlds.zip)

**Comment by bloodscon** [comment]
I thought the xp taps from mob grinding utils could only be attached to the xp tanks from mob grinding.  Would be much easier if mods that use liquid xp would set a standard or a in mod way to convert to and from minecraft xp orbs

**Comment by oly2o6** [comment]
try removing mob grinding utils, loading up and then adding it back

**Comment by oly2o6** [comment]
but the mod was updated since this and apparently fixed it
