### ISSUE TITLE
Easy Villagers & Shift Clickability 

### ISSUE THREAD

**Issue by ChosenArchitect** [AllTheMods/atm6-sky#280]
**Issue**
The Easy Villagers Mod allows you to Shift right-click to pick up. This breaks every mod that allows you to pick them up. This breaks the ability for you to use them in a Mob duplicator and or make a Spawn egg from them with Mob Grinding Utils.

**To Reproduce**
1. Place Villager
2. Shift Right-Click Villager with Mob Imprisonment tool.
3. Be rewarded with a Crash or it will just ghost the items and you will still only get an Easy villager as an Item.

**Pack Version**
1.0.7

**Comment by ArcheTypeY** [comment]
You might be able to get a villager spawn egg by killing them using the “capture” enchantment.

**Comment by Karan-Sidhu** [comment]
Switch mob swab into offhand for functionality for swabbing. Love ya Chosen!

**Comment by Zagam1337** [comment]
Go to "Instances\All the Mods 6 - To the Sky - ATM6S\config" find the file "easy_villagers-client.toml" edit with notepad++ and change "#If villagers should be able to be picked up by sneaking and right-clicking sneak_pick_up" from true to false. After that, all will be good. Cheers

**Comment by oly2o6** [comment]
fixed in 1.0.9

**Comment by tzuzn** [comment]
I have the same Problem on the 1.0.9 and the solution Zagan1337 commented already tested (Playing on a Server)
