### ISSUE TITLE
All my chiselandbits blocks got scrambled randomly after updating

### ISSUE THREAD

**Issue by ArcheTypeY** [AllTheMods/atm6-sky#281]
After updating the pack from 1.0.6 to 1.0.7 all my chiselandbits blocks got replaced with seemingly randomly chosen textures of other blocks.

1. Create any chiselandbits block on 1.0.6
2. Place it down
3. Update to 1.0.7

**Comment by ArcheTypeY** [comment]
Also does anyone know a fix? I do not want to manually replace every block.

**Comment by oly2o6** [comment]
this would have been an unfortunate conflict with a mod update, unfortunately i have no idea how to fix unless you have a backup
