### ISSUE TITLE
Missing structures in Nether

### ISSUE THREAD

**Issue by MushuPlatypus** [AllTheMods/atm6-sky#282]
**Describe the bug**
When going to the Nether there are no structures with blazes or wither skeletons.  It is a complete void

**To Reproduce**
1. Build portal and go through

**Expected behavior**
I would expect a void dimension with structures with blaze spawners and wither skeletons

**Additional context**
If I do a /locate fortress and go to the supplied coordinates, nothing is there but air

**Comment by inspiiree** [comment]
You need to go to the other (Place a teleport pad in the nether)

This is fully intended.

**Comment by MushuPlatypus** [comment]
Thanks for clearing that up
