### ISSUE TITLE
The Material Stonework Factory should crush sand into dust instead of silicon

### ISSUE THREAD

**Issue by TheBigBuns27** [AllTheMods/atm6-sky#283]
Title says it. This is for the latest version (creative items update).

I'm fairly sure this is an overlooked recipe but if it isn't then there are other options for crushing.

**Comment by oly2o6** [comment]
You are correct that it was overlooked but i dont think it would be something that I would want to change (even if i could which i am unsure of), i feel if one machine on its own could go from nothing to dust (especially with speed upgrades) then the recipe for it would have to be changed for that one reason and then it would negate all the other materials that the machine can do
