### ISSUE TITLE
Ice&Fire Dragon Breath Break Compact Machine Blocks

### ISSUE THREAD

**Issue by Krum26** [AllTheMods/atm6-sky#284]
I dont think this is intended since compact block should be unbreakable
![image](https://user-images.githubusercontent.com/81198837/115449266-876b4f80-a212-11eb-9b97-8331f6165dc5.png)

**Comment by oly2o6** [comment]
this would be one to report to the mod authors unfortunately! Don't believe there is anything we can do on our side but thank you for letting us know!
