### ISSUE TITLE
fire and ice

### ISSUE THREAD

**Issue by moonwatcher17** [AllTheMods/atm6-sky#285]
how rare are fire, ice, and lightning lilies for dragon breeding?

**Comment by Attila1616** [comment]
They're quite rare, I found 2 ice dragons right next to eachother after about 10-15 minutes of searching. I suggest you to capture one as soon as you find one with the mob imprisonment tool or use the mob swab to be able to duplicate them.

**Comment by moonwatcher17** [comment]
well using the mob imprisonment tool in the duplicater only will give us red eggs.

**Comment by oly2o6** [comment]
Question answered, closing
