### ISSUE TITLE
Sleeping In The Other Dim

### ISSUE THREAD

**Issue by ChosenArchitect** [AllTheMods/atm6-sky#287]
**Describe the bug**
When you sleep in The Other Dim with a  Sleeping Mat (I didn't have time to test a regular bed) you will be stuck in the Sleeping window and cant cancel it. You either have to /kill (kinda sucks but works) or Alt+F4 :P

**To Reproduce**
1. Sleep in The Other Dim with a Sleeping Mat

**Comment by Pdiddy973** [comment]
this seems to be an issue with just the sleeping mat....you are not supposed to be able to sleep in the other either. the bed explodes like in the nether
