### ISSUE TITLE
Uncrafting grinder multiplies output by 16 (itemdupe).

### ISSUE THREAD

**Issue by powerfarmer98** [AllTheMods/atm6-sky#29]
**Describe the bug**
Uncrafting grinder (craftable in survival) from cyclic multiplies its output by 16.

**To Reproduce**
1. Place armorpiece of X metal in uncrafting grinder.
2. Recieve 16x the materials it required to make said armorpiece.
3. Profit.

**Expected behavior**
Placing for example a diamond block in the uncrafting grinder giving me back 9 diamonds instead of 144.

**Screenshots**
![image](https://user-images.githubusercontent.com/77217445/110987220-11e8a580-836f-11eb-9eba-4f9dde6b6a1d.png)

**Additional context**
Works for all outputs, so iron pick gives 48 iron instead of 3.

**Comment by WhitePhant0m** [comment]
the uncrafter is disabled for a reason...

**Comment by powerfarmer98** [comment]
well its not disabled tho

**Comment by powerfarmer98** [comment]
as said in my issue in the first place
