### ISSUE TITLE
Mob Duplicator Crash - Update Industrial Foregoing

### ISSUE THREAD

**Issue by devmattrick** [AllTheMods/atm6-sky#291]
**Describe the bug**
Currently, putting a Mob Imprisonment Tool inside the Industrial Foregoing Mob duplicating machine crashes the server and corrupts the world.

**To Reproduce**
1. Place a Mob Imprisonment Tool inside a Mob Duplicator

**Expected behavior**
Server doesn't crash :P

**Screenshots**
N/A

**Additional context**
It can be fixed by manually editing the world NBT and removing the tile entity and the palette entry for the mob imprisonment tool itself, so if anyone else happens to have this issue, your world _is_ fixable!

As for fixing this issue in the future, it seems Industrial Foregoing has already patched this in the latest version, so the fix seems as simple as updating Industrial Foregoing: InnovativeOnlineIndustries/Industrial-Foregoing#1055.

**Comment by oly2o6** [comment]
fixed in 1.0.8
