### ISSUE TITLE
FPS Issue

### ISSUE THREAD

**Issue by Mifwiin** [AllTheMods/atm6-sky#292]
I allocated 11 GB RAM to the modpack but lag spikes still occure. I have 7 or 8 compact machines and they are chunk loaded is that the problem. It become so frustrating lately its imposibble to play.

**Comment by swardhagen** [comment]
A lot have had the same issue, many (including me) have found that installing Optifine really helps.

**Comment by Mifwiin** [comment]
I will try that thanks.
