### ISSUE TITLE
Failed to synchronize registry data from server, closing connection

### ISSUE THREAD

**Issue by DanijelPlays** [AllTheMods/atm6-sky#294]
I opened a "Open to LAN" server. And I wanted to play with someone (who is on the same WIFI as I), the person logs in and then the message in the title shows. Please help.

Thanks! :)

EDIT: Number of characters of player that is trying to join is 13.

**Comment by DanijelPlays** [comment]
Okay I found the issue. I updated my ATM6 to the sky.

**Comment by DanijelPlays** [comment]
I don't want to make a new issue 'cause I just closed it. but now when the players wants to join he gets this message in the title.

Please help again?

Thanks =D

**Comment by Jumper2512** [comment]
Posted the same issue 2 weeks ago got no reply. Hope someone will see yours bcs i have the same problem :/

**Comment by Pdiddy973** [comment]
LAN servers dont play well with modded MC, its better to run a separate server with our server files

**Comment by Jkosio23** [comment]
> 
> 
> LAN servers dont play well with modded MC, its better to run a separate server with our server files

I'm having the same issue on 1.1.6 using the simple server files. Resourceful bees is the cause of mine, but i did see another issue where the offending mod is crayfish's furniture mod.

here is the relevant section of my logs https://hastebin.com/ducevahube.css

#403 #462 seen here, this needs to be reopened
