### ISSUE TITLE
wanted to know if this was meant to even exist

### ISSUE THREAD

**Issue by AblazeAura918** [AllTheMods/atm6-sky#295]
So I killed a lot of dragons and ended up with a couple drops I didn't see apparently I got a spawn egg for every Dragon type not the one to get the pet the spawn egg with the capturing enchant you can then make a dragon spawner of the type you want should this be a thing it is kind of broken cause atleaste with the mob duplicator it cost something to spawn them.

**Comment by Attila1616** [comment]
I guess it's meant to be there, I got some spawn eggs as well...

**Comment by jimbo80008** [comment]
check the enchants on your sword, apoptheosis adds a enchantment which gives a chance of dropping a spawn egg, perhaps that is what happend. as for the baby dragon, you'll need to kill a stage 4 or 5 dragon for one, perhaps that is the cause

**Comment by AblazeAura918** [comment]
> check the enchants on your sword, apoptheosis adds a enchantment which gives a chance of dropping a spawn egg, perhaps that is what happend. as for the baby dragon, you'll need to kill a stage 4 or 5 dragon for one, perhaps that is the cause

yeah i know that it just seems broken
