### ISSUE TITLE
Mesh disappearing in auto sieve when sorting with an item(s) in the top slot

### ISSUE THREAD

**Issue by Toasty-O** [AllTheMods/atm6-sky#296]
**Describe the bug**
Whenever I sort the auto-sieve "inventory" with items and a mesh, the items go into the mesh slot and i lose the mesh itself, it doesn't go into my inventory and it doesn't drop on the ground

**To Reproduce**
1. Open up an auto-sieve
2. Add a mesh and items
3. Give it power
4. Sort the auto-sieve "inventory"
5. See items replace the mesh

**Additional Information**
1. I've only tried this with a regular auto-sieve, not a heavy auto-sieve. 
2. I've only tried this with a string, iron, and emerald mesh

I'm assuming this would also happen with the heavy auto-sieve and other mesh types

**Comment by Pdiddy973** [comment]
https://github.com/blay09/ExCompressum/issues/309
