### ISSUE TITLE
Why on single player world I'm limited on how many chunks I can claim?

### ISSUE THREAD

**Issue by leopupin** [AllTheMods/atm6-sky#297]
I would like to remove, or set the maximum, the limit of chunks I can claim on my own game.

**Comment by T3line** [comment]
You're limited on chunks in multiplayer too, except owners increase/decrease that limit via config file or commands.

Change with config:  **modpack directory**/saves/world/serverconfig/ftbchunks-server.toml
Edit the max_force_loaded_chunks = _123456789_

Change with commands:
/ftbchunks admin extra_force_load_chunks _nickname_ set _123465789_
