### ISSUE TITLE
I am having troubles with nether fortresses not spawning.  

### ISSUE THREAD

**Issue by BajanLuke** [AllTheMods/atm6-sky#298]
I would go into the nether and use the /locate command to see if there are any fortresses.  It would show that there is one there but when I teleport to it there is no structure of one.

**Comment by jeremiahwinsley** [comment]
Not a bug, fortresses spawn in The Other.

**Comment by OceanRift** [comment]
I don't have a fortress in my world, does somebody know what is wrong?

**Comment by Mightylight** [comment]
foretresses spawn in the other underground. If it's really the case that they don't spawn (try a different world for example) it's probaly best to make a seperate issue then posting a comment on an already close issue
