### ISSUE TITLE
[1.0.7] Have to restart pack everytime I leave a server.

### ISSUE THREAD

**Issue by TrainzCS** [AllTheMods/atm6-sky#299]
Everytime I leave the server I play on I have to relaunch the pack otherwise I get the error: Internal Error: java.lang.NullPointerException after encryption has passed on the screen.

Multiple people have experienced this issue as I am playing on a Twitch Sub server. I have also encountered this issue on my own server that I test stuff on.

It is very annoying to have to wait 20+ mins each time I disconnect from either server for the pack to reload.

I have the newest java version and have changed it to the newest in curseforge settings.

**Comment by TrainerSnow** [comment]
Can validate this, it happens everytime i leave my own localhosted server.

**Comment by jeremiahwinsley** [comment]
Remove Crash Utilities from the server, or update it to 3.10.0.

**Comment by Deragonis** [comment]
for those still having this issue, removing crash utilities from the client worked for me
