### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by Joprebond** [AllTheMods/atm6-sky#30]
I installed the pack (version 1.0.2) from curseforge into MultiMC as a new instance. When i launch the pack from MultiMC the game crashes

**To Reproduce**
Install the latest version from the development branch of multi-mc and launch it

**Expected behavior**
For the game not to crash on startup

**Additional context**
Crash logs are attached.

[crash-2021-03-12_16.53.25-client.txt](https://github.com/AllTheMods/atm6-sky/files/6133308/crash-2021-03-12_16.53.25-client.txt)
[crash-2021-03-12_20.12.27-client.txt](https://github.com/AllTheMods/atm6-sky/files/6133309/crash-2021-03-12_20.12.27-client.txt)

**Comment by WhitePhant0m** [comment]
Line 29: Caused by: `java.nio.file.FileSystemException: E:\Minecraft\MultiMC\instances\All-the-Mods-6-Sky-1.0.2\minecraft\config\appliedenergistics2-common.toml: The process cannot access the file because it is being used by another process.`
Do you have the file open somewhere?

**Comment by WhitePhant0m** [comment]
If not, try with just multimc open, or another launcher like [GDLauncher](https://gdevs.io/)

**Comment by Joprebond** [comment]
i didn't have the file open at all.  I've been trying it on and off for a few days and i cannot seem to reproduce it.
