### ISSUE TITLE
Mahou Tsukai Caliburn

### ISSUE THREAD

**Issue by lendog132** [AllTheMods/atm6-sky#300]
I can not make a Caliburn in creative or survival.
When I throw a diamond sword in my power consolidation pool nothing happens, I have the required amount of mana.
Another issue I have is I can not see how to get any resourceful bees spawn eggs, if that helps diagnose the problem.
Thank you

**Comment by stepsword** [comment]
sword has to be enchanted and thrown using the Q keybind

**Comment by Pdiddy973** [comment]
The bees you need to start with are crafted, look at the spawn eggs. Our discord has a breeding chart to make it easier.

**Comment by lendog132** [comment]
> The bees you need to start with are crafted, look at the spawn eggs. Our discord has a breeding chart to make it easier.

what is your discord?

**Comment by Pdiddy973** [comment]
https://discord.gg/K5FBPYa

**Comment by lendog132** [comment]
> https://discord.gg/K5FBPYa

got it to work, thank you!
