### ISSUE TITLE
Using a media button while loading up a single player world causes it to instantly crash

### ISSUE THREAD

**Issue by jimbo80008** [AllTheMods/atm6-sky#301]
**Describe the bug**

**To Reproduce**
Start up a existing single player world while playing some music and then pause it using a media button, it will crash.

**Expected behavior**
See above

**Screenshots**
Super easy to reproduce, so maybe screenshot not necessary

**Additional context**
I only used the spotify desktop app, maybe it has to do with that but I thought that it might be better to just report it.

**Comment by oly2o6** [comment]
this has to be the weirdest issue ive even seen in 2 years, i just tried to reproduce it (I also use spotify myself) and it didn't happen and i am honestly flabbergasted, but i would guess the best thing to do is just not pause with a media key? lmao honestly no clue
