### ISSUE TITLE
TConstruct 3

### ISSUE THREAD

**Issue by christianbutnot** [AllTheMods/atm6-sky#304]
**Describe the bug**
So, in essence, the ALPHA version of TConstruct 3 currently in use has many bugged recipes. The version "Tinkers' Construct 3.0.3.111 for 1.16.5" has this fixed from my own testing. 

**To Reproduce**
1. For a quick example, just try and make gold blocks in the smeltery. Smelt gold ore or gold chunks in the smeltery.
2. Pour the molten gold into a casting basin
3. Watch the gold block change from molten gold to coagulated blood blocks.

**Expected behavior**
Gold to create gold blocks

**Comment by stragulus** [comment]
Other way around (ish) works too: casting blood from melting rotten flesh in casting basing yields block of iron.

**Comment by TechieJunk** [comment]
If you have Performant installed, uninstall it. it conflicts with TiCon.

**Comment by Pdiddy973** [comment]
should be fixed in 1.0.8
