### ISSUE TITLE
Pipez don't work with Thermal Redstone Flux Cells

### ISSUE THREAD

**Issue by Naddox** [AllTheMods/atm6-sky#306]
The Pipez mod seems to be the primary focus of the pack for items, energy, liquid, and gas. The Energy Pipe nor the Universal Pipe will pull power from a Thermal Redstone Flux Cell. They will transport power from dynamo's or generators and add it the the Redstone Flux Cell, but they will not pull the power back out. This is not a new issue as of latest update, just finally frustrated me enough to post this report.

**To Reproduce**
1. Place a redstone flux cell from the Thermal Series mod
2. Add energy to the cell in whatever manner you desire
3. Configure the cell to output energy from a desired side
4. place either a energy pipe or universal pipe next to the side configured to output energy
5. Shift Right click the pipe with the Pipez wrench to connect to the cell for extraction mode
6. Connect the pipe to any machine in need of power or even another cell that has no power

**Expected behavior**
The pipe should transfer power from the cell to whatever it is connected to.

**Screenshots**
![2021-04-25_21 32 13](https://user-images.githubusercontent.com/845312/116004975-c08a3200-a60d-11eb-97c7-4a53becc026e.png)

**Additional context**
Would prefer a different transport system be added to replace the pipez mod.

**Comment by mpavkovic** [comment]
Bug was already reported to mod author and fixed: https://github.com/henkelmax/pipez/issues/16

For now you can manually update Pipez to latest alpha release: https://www.curseforge.com/minecraft/mc-mods/pipez/files/all
