### ISSUE TITLE
AllTheMobs bee mutations prevent them to be in the same apiary

### ISSUE THREAD

**Issue by NicolasDuboisToulouse** [AllTheMods/atm6-sky#307]
If you put the Allthemodium, Vibranium and Unobtainium bees in the same apiary, they will mutate the "flower block" of the upper tier to the associated bee egg. So you cannot use only one apiary to get these 3 ingots. (At least 2 apiaries are needed: you can put Allthemodium and Unobtainium bees in the same one)

Regarding the cost of a tier 4 apiary, it will be great if we can put theses tree bees in the same one.

I suggest to modify the way to obtain the higher bee tier. Breeding with 5 ingots ? (Block might be too expensive)

**Comment by Pdiddy973** [comment]
You can put the allthemodium and unobtaniam bee in the same apiary, with how the mutations and flowers work you are just going to need multiple apiaries for all 3. That said you likely will already have multiple apiaries any way so I don't see this as a issue

**Comment by NicolasDuboisToulouse** [comment]
Ok, that was just a suggestion.
Thank you for your job!
