### ISSUE TITLE
Sound Engine Crashing game at launch

### ISSUE THREAD

**Issue by Mrbroggle** [AllTheMods/atm6-sky#309]
**Describe the bug**
When I launch the game it crashed when I have my headphones on, this may be due to using Xbox wireless adapter for pc 

**To Reproduce**
It happens at launch when the mojang logo pops up and after Atlas (I think it's atlas) "Freezes data"

**Additional context**
Logs say Sound engine starting at time of crash
Works perfectly fine when headphones are off

**Comment by DarkEyeDragon** [comment]
Gotta ask this: does it happen on vanilla?

Also a crash log might be helpful. 
But yeah as you said it might just not play nicely with your drivers and adapters.

**Comment by Mrbroggle** [comment]
Never happened on vanilla will send crash logs tomorrow :)

**Comment by Mrbroggle** [comment]
It's no longer crashing, might have been a ram issue or something.
