### ISSUE TITLE
Heavy sieves currently useless

### ISSUE THREAD

**Issue by dlhawkins94** [AllTheMods/atm6-sky#31]
Heavy sieves are added by ex compressum, separate from ex nihilo. At the moment they're worse than normal sieves because they work on compressed gravel/sand/dust, but the output amounts per block is the same as an ex nihilo sieve. In other words, you spend 9x the gravel in a heavy sieve to get 1x the iron , relative to using a regular sieve.

To make the heavy sieve useful in a balanced way, I think you could make it much faster than a regular sieve & keep the terrible output ratio, or you could make it much slower (9x slower if you really want to keep the balance), and bring the output ratio up to par with the regular sieve.

**Comment by WhitePhant0m** [comment]
I've done some testing with the sieves, and they seem to do the 9x rolls for loot they are supposed to do, so I'm not sure what you mean by them doing 1x?

**Comment by tyler489** [comment]
> I've done some testing with the sieves, and they seem to do the 9x rolls for loot they are supposed to do, so I'm not sure what you mean by them doing 1x?
> If you meant straight up 9x loot, no they aren't supposed to give you 9 of the same item each time it gives drops, it does multiple rolls at once for loot.

Im not sure what you tested but they definitly do not do 9x loot roles .
Using 6 stacks of compressed gravel (54 stacks of gravel)
Vs
54 Stacks of gravel in a regular sieve.

**Comment by WhitePhant0m** [comment]
I made a test recipe for the sieve that uses glass and drops bedrock with a 100% chance, made a heavy sieve recipe that rolls it 9x, and it works fine, you just might be on the list of unluckiest people on the planet ¯\\_(ツ)\_/¯
[![Image from Gyazo](https://i.gyazo.com/657d13ee2be293bd5af9aa2d4c878216.gif)](https://gyazo.com/657d13ee2be293bd5af9aa2d4c878216)(i recommend clicking the gif for a better quality one)

**Comment by tyler489** [comment]
> I made a test recipe for the sieve that uses glass and drops bedrock with a 100% chance, made a heavy sieve recipe that rolls it 9x, and it works fine, you just might be on the list of unluckiest people on the planet ¯\_(ツ)_/¯
> [![Image from Gyazo](https://camo.githubusercontent.com/fbe7fc14bfcfb4cc386411207829b9205a5ce477307bb96b611ab694f9e76886/68747470733a2f2f692e6779617a6f2e636f6d2f36353764313365653262653239336264356166396161326434633837383231362e676966)](https://gyazo.com/657d13ee2be293bd5af9aa2d4c878216)(i recommend clicking the gif for a better quality one)

you added a custom recipe that rolls 9 times that's why... default heavy sieve rolls FIVE times per compressed block

**Comment by tyler489** [comment]
https://github.com/blay09/ExCompressum/issues/311 leaving this here
