### ISSUE TITLE
weird game crash

### ISSUE THREAD

**Issue by BaconLord-code** [AllTheMods/atm6-sky#310]
I have had a crash bug where I play the mod pack fine with minimal lag (while adjusting performance settings) but after 1 hour to 20 minutes consistently I would get a big lag spike where it would run again but my screen would still be frozen (as in I could still hear and interact with the world). I have tried breaking blocked reloging and see that the block was broken, I have tried switching mod loaders and have updated to the latest version as well.  I really don't know what is going on

**Comment by Attila1616** [comment]
did you try giving it more ram? try to look at the F3 menu and see if your ram maxes out when it lags..

**Comment by oly2o6** [comment]
some mem leaks were fixed in the recent update, let me know if the issue persists
