### ISSUE TITLE
Tinkers Smeltery Block vs Ingot Outputs

### ISSUE THREAD

**Issue by TheDankBurrito** [AllTheMods/atm6-sky#311]
**Describe the bug**

When using the Tinker's Construct Smeltery you get 2 different versions of the same material depending on if you pour the materials into the basin or an ingot cast.

**To Reproduce**

1. Build Tinker's Smeltery
2. Put Ores into Smeltery
3. Pour molten ingots into a basin or ingot cast on a casting table
4. Craft the block form back into ingots
5. See that the ingots given from the block form are not the same as poured directly from an ingot cast

**Expected behavior**

Would expect to see the ingots from the casting basin and ingot cast casting table to be ore dictionaried to give the same ingot form

**Screenshots**

![image](https://user-images.githubusercontent.com/83256927/116170603-fd146700-a6bb-11eb-9d03-67cdf658c700.png)
![image](https://user-images.githubusercontent.com/83256927/116170656-16b5ae80-a6bc-11eb-82b1-a800a71df27b.png)
![image](https://user-images.githubusercontent.com/83256927/116170664-1f0de980-a6bc-11eb-8e9a-afffdf8129e7.png)
![image](https://user-images.githubusercontent.com/83256927/116170690-259c6100-a6bc-11eb-8640-ed42d0f6916a.png)

**Additional context**

Seems to default to "AllTheOres" in most cases for ingots when breaking down blocks created in the smeltery

**Comment by Pdiddy973** [comment]
waiting for proper kubejs control of tinkers before we can edit the recipes to make them all work properly
