### ISSUE TITLE
Creative Energy Cube eats Energy.

### ISSUE THREAD

**Issue by Puddel** [AllTheMods/atm6-sky#312]
**Describe the bug**
The Empty Creative Energy Cube from Mekanism eats all of the Energy it receives and stays at "0 FE/Infinite".

**To Reproduce**
1. Place down a Empty Creative Energy Cube from Mekanism.
2. Connect it to some sort of Generator and try to insert Energy (I used Solar Panel VIII from Solarflux).
3. You will see that the Energysource is extracting all its Energy.
4. Right click the Creative Energy Cube and hover over the Energy tank and it will say "Empty".

**Expected behavior**
Creative Energy Cube should fill up with Energy to an Infinite/ near Infinite amount.

**Screenshots**
![image](https://user-images.githubusercontent.com/37541868/116256502-876bd200-a773-11eb-97d9-4c621a7f176f.png)
![image](https://user-images.githubusercontent.com/37541868/116256540-92266700-a773-11eb-9c3a-2f9777fcf7c2.png)
![image](https://user-images.githubusercontent.com/37541868/116256606-a23e4680-a773-11eb-9ea7-33cb27951472.png)

**Comment by JustPie-U** [comment]
The energy cube by default will just eat energy, you need to use an ATM Star to have it be unlimited energy, this isn't a bug.
