### ISSUE TITLE
AS Constellation Papers Unobtainable 

### ISSUE THREAD

**Issue by ChosenArchitect** [AllTheMods/atm6-sky#313]
**Describe the bug**
You can craft a Constellation paper but after crafting your first one it will default to Vicio (or any other) but will only drop that vr from that point on.

**To Reproduce**
1. Craft a Constellation Paper
2. Craft another one and see if you get the other types. (In my world I crafted 6 papers at a time and they were all Vicio)

**Expected behavior**
You need a way to get all of the base Papers so you can attune yourself and things.

**Screenshots**
![2021-04-27_18 55 51](https://user-images.githubusercontent.com/35053440/116326796-ea1c9800-a78a-11eb-990c-cde5117214ba.png)
![2021-04-27_18 55 54](https://user-images.githubusercontent.com/35053440/116326798-eb4dc500-a78a-11eb-9523-3853c4c90218.png)

**Comment by Pdiddy973** [comment]
You need to be attnued first, then you should be able to craft them.

**Comment by ladylexxie** [comment]
You unlock the ability to understand higher tier papers by attuning. I always recommend people to go with Discidia because its the best one for raw damage. I have a perk tree image here, if you need it: https://imgur.com/a/eg9tlPn

**Comment by memyselfandcj** [comment]
Done samething.....in JEI there should be a 1/5 for recipes. Each one crafts a different constellation.
![2021-04-28_00 01 55](https://user-images.githubusercontent.com/40968814/116344868-07665c00-a7b5-11eb-805c-39ccff212c52.png)

**Comment by ladylexxie** [comment]
> Done samething.....in JEI there should be a 1/5 for recipes. Each one crafts a different constellation.
> ![2021-04-28_00 01 55](https://user-images.githubusercontent.com/40968814/116344868-07665c00-a7b5-11eb-805c-39ccff212c52.png)

Those are the initial 5 you start off with, the one's you find randomly with exploration. The rest 11 have to be crafted with the Iridescent Altar. That's the case in normal gameplay. He was asking about the other 11 you need to craft.

**Comment by Catandcomparator** [comment]
it worked fine for me. i crafted the first few in a basic way, attuned myself, and got a sweet horologum paper.

**Comment by ladylexxie** [comment]
> it worked fine for me. i crafted the first few in a basic way, attuned myself, and got a sweet horologum paper.

That's because you followed the instructions. That's what we explained you have to do, so obviously it worked :P

**Comment by Pdiddy973** [comment]
Going to close this as it seems to not be an issue
