### ISSUE TITLE
Weird arrow bug

### ISSUE THREAD

**Issue by True-Galaxy** [AllTheMods/atm6-sky#314]
**Describe the bug**
Many random arrows won't go away and are just stuck twitching in the ground. I tried to /kill them, (kill @e[type=arrow]) but it says "No entity was found"

**To Reproduce**
1. Let a skeleton shoot an arrow
2. Try to remove it
3. See bug

**Expected behavior**
For the arrow to either despawn or be removed
**Screenshots**
![2021-04-27_16 21 28](https://user-images.githubusercontent.com/76611592/116336706-b9c9ff00-a774-11eb-816b-03e04b273e18.png)

**Comment by oly2o6** [comment]
this isnt an "issue" issue, more of an annoyance but ill keep it in mind and keep my eye out for a fix as i have no idea about how to even find a fix for this as i would assume its either a vanilla bug or an issue with a mod doing it by accident
