### ISSUE TITLE
Resourcegen issues.

### ISSUE THREAD

**Issue by Catandcomparator** [AllTheMods/atm6-sky#315]
this is actually 2 issues, zombees cannot breed, and i cannot craft rock crystal seeds.

**Comment by DrWKool** [comment]
rock crystal seeds can be crafted using 4 identical crystals (same stats)
maybe you can split them with the stone cutter to get 4 size 1 (for instance)

**Comment by Zuko49** [comment]
Another way to get Rock Crystal Ore is to create a Laser Drill from Industrial Foregoing and put a Gray Lens. lots of Stella Arcanum and Rock Crystal Ore.
