### ISSUE TITLE
Can't start a server, "String too big"

### ISSUE THREAD

**Issue by Attila1616** [AllTheMods/atm6-sky#317]
I've been having issues starting a server to play with my friend, I'm trying to use my world since I progressed quite a lot and don't want to start over but when the server loads the spawn chunks as soon as I try to refresh the multiplayer page it says "Can't connect to server" with a red "X" and on the console it gives me the "io.netty.handler.codec.EncoderException: String too big (was 33564 bytes encoded, max 32767)".

There must be something in my world but I'm not sure what it could cause it, starting a clean world works perfectly.

The logs: https://pastebin.com/eWmLWfCn

**Comment by Attila1616** [comment]
Apparently even if it says the server is not open I can still join? Weird.

**Comment by Pdiddy973** [comment]
If you copied the world from a SP save, remove the icon.png and see if it's fixed
