### ISSUE TITLE
Fix  performance !!!

### ISSUE THREAD

**Issue by G4mer0815** [AllTheMods/atm6-sky#318]
Fix  performance,  update to 1.0.8 not Playable, 2 min played and hard laggs. 
1.0.7 hard fps drops

Can't keep up! Is the server overloaded? Running 7177ms or 55 ticks behind
########## GL ERROR ##########
@ Render
65539: Invalid key -1

**Comment by starforcraft** [comment]
How much RAM did you give sky?

**Comment by G4mer0815** [comment]
6gb

**Comment by ToxicToast** [comment]
i gave it 10 and it wasnt better either...

**Comment by G4mer0815** [comment]
hm ok i have 16gb,

**Comment by bloodscon** [comment]
i had same problem after update found one of my pipe from pipez mod had disconnected from my sieve system and sieves where throwing stuff all over found they also don't like mekanism multiblock. Make a brine tower use pipez to pipe out log the server off and when you log it back on the pipe will have disconnected

**Comment by oly2o6** [comment]
pipez will be updated in 1.0.9
