### ISSUE TITLE
Cyclic Uncrafting Grinder Item Sixteenuplication

### ISSUE THREAD

**Issue by Seegras** [AllTheMods/atm6-sky#32]
The Cyclic Uncrafting Grinder returns not the items an item is made of (uncraft) but only the item that was in the first filled crafting slot, but that in every slot of the output, which means 16 times. 

So for 7 redstone blocks, you would get 63x16 redstone. For a bow or fishing rod, you'd get 3x16 sticks instead, but no string.

**Comment by WhitePhant0m** [comment]
#29
