### ISSUE TITLE
Infinite Item/Fulid Storage visual bug

### ISSUE THREAD

**Issue by Puddel** [AllTheMods/atm6-sky#321]
**Describe the bug**
*Infinite Item Storage Block from Refined Storage has a huge blue bar that goes to the top of the screen
*Infinite Fluid Storage Block isn't displaying mb

**To Reproduce**
1. Place down a Infinite Item/Fluid Storage Block from Refined Storage
2. Fill your system with items/liquids
3. Infinite Item Storage Block has a huge blue bar (picture) and the Fluid Storage Block is displaying 0 mb even though it has fluids in it.

**Expected behavior**
The Infinite Storage Block should not have a blue bar at all since it is always "0% Full"
The Infinite Fluid Storage Block should display an amount of mb in the system

**Screenshots**
![image](https://user-images.githubusercontent.com/37541868/116539773-970d2700-a8e9-11eb-8c7f-c7da22214685.png)
The huge blue bar in the Item Storage Block

![image](https://user-images.githubusercontent.com/37541868/116539841-aab88d80-a8e9-11eb-99df-4ea0c7c57e0d.png)
The Infinite Fluid Storage Block not displaying mb

![image](https://user-images.githubusercontent.com/37541868/116539690-7775fe80-a8e9-11eb-955d-f0d58d049cb8.png)
Just to prove that there are Fluids in the system

**Comment by oly2o6** [comment]
hi it appears this is not a bug on our side but actually would be a good one to report directly to the mod author
