### ISSUE TITLE
[1.0.8] World generating floating structures all around

### ISSUE THREAD

**Issue by jaceee** [AllTheMods/atm6-sky#323]
When I start a new world it generates floating structures all around.

**To Reproduce**
1. Create a new world
2. See error

**Expected behavior**
The world should generate with only the main island.

**Screenshots**
![2021-04-29_08 06 12](https://user-images.githubusercontent.com/5000478/116582453-00d20480-a8db-11eb-80df-548fa7014026.png)
![2021-04-29_11 02 27](https://user-images.githubusercontent.com/5000478/116582459-02033180-a8db-11eb-8b94-2384ae892c1f.png)
![2021-04-29_11 02 30](https://user-images.githubusercontent.com/5000478/116582462-029bc800-a8db-11eb-8611-d69ba605d2b8.png)

**Comment by jaceee** [comment]
I thought it was a server issue because i updated my single player world from 1.0.7, but after creating a new single player world i noticed it has the same issue. Updated the issue.

**Comment by lootf777** [comment]
I have this same issue on 1.0.8 In both a new server and a singleplayer world updated from 1.0.6, generating new chunks in this world also creates these structures.

**Comment by VoidStoneDev** [comment]
Should be fixed in #334

**Comment by VoidStoneDev** [comment]
Looks like it is a bug in [MelanX/SkyblockBuilder](https://github.com/MelanX/SkyblockBuilder/)

**Comment by MelanX** [comment]
I don’t know which version ATM6S is using, so.. maybe it’s already fixed, maybe not. I hope it is.

**Comment by MelanX** [comment]
So.. I looked in the manifest.json file. It seems that it’s using 1.4.3.
1.4.4 fixes that some structures and features ignore the whitelist. (Released on 24.4.2021)
This should be the important version. 1.4.7 fixes That strongholds are spawning, even if not whitelisted but this isn’t the thing. ATM6S just need to update the mod next time :D

**Comment by VoidStoneDev** [comment]
Any idea on what could've caused it to stop working in 1.0.8 while it worked fine in 1.0.7 using the same SkyblockBuilder version

**Comment by MelanX** [comment]
On server? idk.. did Forge update? Maybe this changed something.. idk lol
