### ISSUE TITLE
Resourceful Bees: Bees won't go into Hive.

### ISSUE THREAD

**Issue by Zuko49** [AllTheMods/atm6-sky#325]
Bees won't go into hive
I have 4 Cobbees and 4 Lava Bees, when I place them down they don't go into hive no matter what time it is.

**To Reproduce**
1. Go to Minecraft
2. Get any bee from Resourceful Bees
3. Place down Bees and Hive
4. Bees don't go into Hive

**Expected behavior**
Bees are supposed to go into hive

**Screenshots**

**Additional context**
Am Following ChosenArchitects Resourceful Bees playthrough in ATM6 To the Sky. Copied what he did for bees, mine doesn't work.

**Comment by starforcraft** [comment]
Do you have a Flower?

**Comment by Zuko49** [comment]
> > Do you have a Flower?
> 
> Yes I do, for 4 Cobbees I have 6 Blocks of CobbleStone, and for 4 Lava Bees, I have 6 Sources of Lava.
> 
> I also noticed that if I break a hive and replace it, it changes from a Tier 1 to a Tier 0? I will send screenshots asap.

![beehivesAtm6Sky](https://user-images.githubusercontent.com/83432932/116704354-eb1f1680-a990-11eb-8017-51833a0d747c.png)
![tier0Hive](https://user-images.githubusercontent.com/83432932/116704395-f40fe800-a990-11eb-9e36-9d7b6c485f66.png)

**Comment by starforcraft** [comment]
Did you add any extra mods?

**Comment by Zuko49** [comment]
just optifine

**Comment by Zuko49** [comment]
Wait A second. I updated forge to 1.16.5-forge-36.1.9 from 36.1.6 and it now allows the bees to go inside the hive. However, I haven't noticed any combs, but I will close this thread, as the problem has been solved.
