### ISSUE TITLE
Ex Nihilio Barrels Won't Accept Lava

### ISSUE THREAD

**Issue by hotguyeric** [AllTheMods/atm6-sky#326]
**Describe the bug**
When I right click on the stone or wood barrel with a bucket of lava, it isn't added to the barrel. This issue does not occur with water.

**Comment by zacharian1036** [comment]
This issue also occurs with witch water and sea water

**Comment by Armed-Mob** [comment]
I was able to get lava into the barrel using the pipez fluid pipe from a mekanism tank.

**Comment by hotguyeric** [comment]
Yes, I believe it is a bug with right clicking on the barrel rather than the barrel's ability to accept the fluid.

**Comment by VoidStoneDev** [comment]
One question, are you using a shield?
I have found that having a shield in off-hand breaks alot of right-click actions

**Comment by Armed-Mob** [comment]
No shields, not able to just right click the pedestals to add charm thing either, must put in off hand then right click, need to see if that works for lava in barrel.  Will update.

**Comment by Armed-Mob** [comment]
No luck on the bucket in the off hand either.  Does work for pedestals as stated before. Do I need to make a separate thread for the pedestals needing to be in offhand?

**Comment by oly2o6** [comment]
Pedestals for offhand was a feature change from the mod, ill sort the ex nihilio issue though

**Comment by Armed-Mob** [comment]
Thanks for the updates!  Loving the pack!
