### ISSUE TITLE
Speeding up Bee Breeding in an Apiary Breeder results in extremely heavy lag.

### ISSUE THREAD

**Issue by Zuko49** [AllTheMods/atm6-sky#328]
Speeding up Bee Breeding in an Apiary Breeder results in extremely heavy lag, even after the Time in A Bottle Effect is Done.
**To Reproduce**
1. Get Apiary
2. Use Breeder with any 2 bees
3. Speed up the breeder

**Expected behavior**
Bees breeding normally but faster.

**Comment by oly2o6** [comment]
hi it appears this is not a bug on our side but actually would be a good one to report directly to the mod author
