### ISSUE TITLE
Server generating as normal world and not a skyblock

### ISSUE THREAD

**Issue by ItsPureFrenzy** [AllTheMods/atm6-sky#329]
Hi,

so me and my friends are trying to make a private server and no matter what settings we change it keeps spawning as a normal world, just wondering if its bugged or if i can get some help to set it up correctly

**Comment by oly2o6** [comment]
you need to make sure the world type in server-properties is set to custom-skyblock

**Comment by oly2o6** [comment]
reopen if this does not fix

**Comment by MelanX** [comment]
No that isn't recommended anymore and removed in newer versions because of a bug. You should use "skyblockbuilder\:custom_skyblock".
