### ISSUE TITLE
Mystical Agriculture - Tinkering Table

### ISSUE THREAD

**Issue by RobertLSnead** [AllTheMods/atm6-sky#336]
**Describe the bug**
Mystical Agriculture Tinkering Table does not work!
Unable to use augments.

**To Reproduce**
1. Open Tinkering Table
2. All Slots are Locked
3. Unable to add armor or augment

**Expected behavior**
Apply augment to armor

**Comment by MrStatman80** [comment]
When you use the tinker table you need the right armour piece for the item you just crafted with the alter.

So leggings speed you need to put them on leggings and so on


But remember you don't get all the slots in tinker table as you only have one

**Comment by RobertLSnead** [comment]
I'm not sure what I am doing wrong then, there is no jei showing what does or does not work.
I tried doing the quest with the flight augment and the superium chest plate (red), when opening the tinkering table all slots are locked except the output.

**Comment by DevilMayCryIfrit** [comment]
Normally you would think to place the armor in one of the slots to the left in the table but you need to place the armor or what you plan to modify in the center then insert the augment. That is what I did and it worked please give it a try and get back to me.

**Comment by DevilMayCryIfrit** [comment]
Ps you need to take out the item from the table into your inventory to equip the augment onto the item

**Comment by RobertLSnead** [comment]
that seem to do the trick, would have never thought to put the armor in the middle
going to close this as it is no longer needed
-thanks for the help
