### ISSUE TITLE
1.07 to 1.08 Update breaking flux networks in compact machines

### ISSUE THREAD

**Issue by BugParticle** [AllTheMods/atm6-sky#337]
**Describe the bug**
I updated the pack to the newest version, after backing up of course. After changing my keybinds and back to normal, everything worked fine. Until apparently my RF buffer ran out. I have a magmatic dynamo setup producing RF inside of a compact machine. The magmatic dynamos are outputting to a flux plug (from Flux Networks) and they are connected via Pipez energy pipes. After the update, flux plug would no longer send power to my main network, which is controlled in the overworld. I tried moving the controller, buffer, into and out of the compact machine, but nothing works. I'm currently running off of a BiggerReactor's reactor, which does work using a plug for the same main network. 

**Expected behavior**
The magmatic dynamo setup within the compact machine should produce power (it is) and it should send it wirelessly to my main network via the Flux Networks mod.

**Screenshots**
![Buffer](https://user-images.githubusercontent.com/83516510/116794354-67e9e780-aa9a-11eb-81c6-187de38296d2.png)
![FluxPlug NoTransfer](https://user-images.githubusercontent.com/83516510/116794355-68827e00-aa9a-11eb-948d-f46fd4e7c9cc.png)
![Magmatic Dynamos](https://user-images.githubusercontent.com/83516510/116794356-68827e00-aa9a-11eb-848e-ea354a3fa1c9.png)
![NoTransfer](https://user-images.githubusercontent.com/83516510/116794357-691b1480-aa9a-11eb-8ac9-4af08a82bddc.png)
![ReactorFluxPlug WithTransfer](https://user-images.githubusercontent.com/83516510/116794358-69b3ab00-aa9a-11eb-9733-5837619c3e63.png)

**Additional context**
This system worked fine up until this update, and it works in other modpacks with cross dimensional energy transfer too. My BiggerReactor's reactor is also in the overworld, not a compact machine. The modpack is ATM6 To The Sky

**Comment by oly2o6** [comment]
try breaking and replacing the pipez? Ive seen this a little and even though annoying, usually fixes it

**Comment by BugParticle** [comment]
Breaking and replacing the pipez didn't work, so I swapped them out for Mekanism energy cables. Those worked so I don't know why the pipez just didnt.
