### ISSUE TITLE
Cantrip book is missing

### ISSUE THREAD

**Issue by Strange-Account** [AllTheMods/atm6-sky#339]
**Describe the bug**
There is no recipe to craft a cantrip book.

**To Reproduce**
-

**Expected behavior**
There should be a recipe for the manaweaving altar with:
- 2 Vellum
- 1 Book
- 1 Vinteum dust
- 1 Quadratum
- 1 Orbeus

**Screenshots**

**Additional context**
Modpack version 1.0.8

**Comment by DrMrPotatoe** [comment]
control left click the manaweaver wand.
