### ISSUE TITLE
ATM Sky 1.0.2 - Shift-right clicking grass gives pebbles on normal worlds.

### ISSUE THREAD

**Issue by ariosos** [AllTheMods/atm6-sky#34]
1 - Create a new world with default settings.
2. After vein-mining the tree, shift-right click the ground.

Despite the world _not_ being the Garden of Glass, it still gives pebbles. (Could there be a dimension ID conflict?)

![image](https://user-images.githubusercontent.com/7917753/111387166-ad398d80-8683-11eb-88cf-fdab309a0807.png)

![image](https://user-images.githubusercontent.com/7917753/111387082-9004bf00-8683-11eb-90fa-ab5a3d45e18c.png)

**Comment by WhitePhant0m** [comment]
This is something entirely on GoG, and we can't fix this unless we remove the mod from the pack, or we remove a certain tag that allows those pebbles to be gotten via shift clicking, but, there is no way of detecting world type in KubeJS that I know of, so, until that is possible, it can't be fixed on our end.
