### ISSUE TITLE
Pedestal not working

### ISSUE THREAD

**Issue by MrStatman80** [AllTheMods/atm6-sky#341]
I'm using the latest version of the modpack 1.0.8 and trying to use Pedestals mod

When I try to use it the upgrade only goes onto the pedestal and not on the shaft like it should.

I tried using a hopper and it takes the upgrade out

So If this is meant to be a new feature you should have let us know... but if not then it's a serious bug since a quest

**Comment by DrMrPotatoe** [comment]
Have you tried using you offhand? On a side note, ask these kind of questions on the Discord

**Comment by MrStatman80** [comment]
> Have you tried using you offhand? On a side note, ask these kind of questions on the Discord

But it's a bug thou

And i tried on hand and off hand and even used my foot

**Comment by MrStatman80** [comment]
but off hand is good but before you justed clicked on it and no document for it and so bug for them to fix

and Thank you DrMrPotatoe

**Comment by MrStatman80** [comment]
So closing
