### ISSUE TITLE
JEI Recipes Completely Missing

### ISSUE THREAD

**Issue by minsterxev** [AllTheMods/atm6-sky#345]
I run ATM6: To The Sky v. 1.08 on a server and recently all the recipes from JEI have disappeared.  This is experienced by everyone on the server and it is persistent.  JEI does show villager trades, enchantments, etc...  but all recipes seem to have been removed.

**To Reproduce**
1. Go to JEI
2. Search for item to craft.
3. Click on item to see recipe.
4. Recipe missing

**Expected behavior**
Recipe should be show for items that are craftable.

**Screenshots**
![image](https://user-images.githubusercontent.com/4157786/117027388-a5cd5280-acca-11eb-81d8-3a32fc48ff3f.png)

Logs:
[latest.log](https://github.com/AllTheMods/atm6-sky/files/6422788/latest.log)
[debug-1.log.gz](https://github.com/AllTheMods/atm6-sky/files/6422789/debug-1.log.gz)
[2021-05-04-1.log.gz](https://github.com/AllTheMods/atm6-sky/files/6422790/2021-05-04-1.log.gz)

**Comment by starforcraft** [comment]
You can't craft Enchanted Books.

**Comment by minsterxev** [comment]
I clicked on the book not the enchanted books.  I am being shown that I can enchant a book but I am not being show the recipe for book.  Yes, I know it is one leather and 3 paper.... the issue is this is the case with every item.   Here is another example for reference.  I click on stone sword to see the recipe and it shows me anvil enchants and smithing table uses but no recipe.
![image](https://user-images.githubusercontent.com/4157786/117029369-93541880-accc-11eb-89ad-a02cf3084c79.png)

**Comment by starforcraft** [comment]
> 
> 
> I clicked on the book not the enchanted books. I am being shown that I can enchant a book but I am not being show the recipe for book. Yes, I know it is one leather and 3 paper.... the issue is this is the case with every item. Here is another example for reference. I click on stone sword to see the recipe and it shows me anvil enchants and smithing table uses but no recipe.
> ![image](https://user-images.githubusercontent.com/4157786/117029369-93541880-accc-11eb-89ad-a02cf3084c79.png)

Show your server log

**Comment by minsterxev** [comment]
[latest.log](https://github.com/AllTheMods/atm6-sky/files/6422220/latest.log)

**Comment by starforcraft** [comment]
I need the server log.

**Comment by minsterxev** [comment]
These are all off the server including the last one posted.

[debug-1.log.gz](https://github.com/AllTheMods/atm6-sky/files/6422273/debug-1.log.gz)
[2021-05-04-1.log.gz](https://github.com/AllTheMods/atm6-sky/files/6422274/2021-05-04-1.log.gz)

**Comment by minsterxev** [comment]
Issue fixed by updating to pack 1.09
