### ISSUE TITLE
Refined Storage crash

### ISSUE THREAD

**Issue by MrStatman80** [AllTheMods/atm6-sky#347]
My world crashes when leaving the area with refined storage import bus for fluids using the lastest modpack 1.0.8
 
1. Step 1 import fluids into refined storage using import bus
2. Step 2 leave the area
3. Step 3 crash

Also something you have done makes me not responsive every few blocks with version 1.0.8 but wasn't on 1.0.7

**Comment by Zuko49** [comment]
I don't know about the glitch itself but the no response thing happened to me as well after updating. Try to change your Forge and update Java. I had a windows notif about updating Java, and I went from 36.1.12 Forge into 36.1.9 and I don't have any lag anymore.
