### ISSUE TITLE
Creosote Oil creation

### ISSUE THREAD

**Issue by GamerXD8991** [AllTheMods/atm6-sky#35]
Pack version: 1.0.2

Creosote Oil only comes from the IE coke oven but the coke brick is missing in JEI. Or am I missing some alternative way?

**Comment by adammbaker** [comment]
Pack version: 1.0.2

Came here to comment this. You can still make the coke bricks from the recipe in the Engineers Manual to make the oven but neither IE coke or the bricks are listed in JEI.
