### ISSUE TITLE
Woot Exotic Modifier

### ISSUE THREAD

**Issue by GiaruDK** [AllTheMods/atm6-sky#350]
Please add recipe for **Enochian Key**, just this is item spawn in ender cities, but how say admin on server you delete end generation. Please this is very cool stuff for woot )
![2021-05-06_23 40 00](https://user-images.githubusercontent.com/49821276/117362875-7eda7080-aec4-11eb-8838-6f5f788c8cde.png)

**Comment by Veritera** [comment]
Why is this closed? Its still a thing.
