### ISSUE TITLE
Villager trades not swapping

### ISSUE THREAD

**Issue by Hodge48** [AllTheMods/atm6-sky#351]
Villagers not able to be changed from original trade assigned to them. Even when placing villagers in world the are still unable to swap their trades through normal methods. 

Only with librarians. Not sure if this is intentional.

**Comment by AppleMangoOrange** [comment]
I think it's intentional, if it were implemented I feel it would be imbalanced.

**Comment by Hodge48** [comment]
> I think it's intentional, if it were implemented I feel it would be imbalanced.

I could see it being imbalanced. I but I dont want to have to remove the mod from the pack even to swap them the vanilla way
