### ISSUE TITLE
server not spawning void world with skyblock

### ISSUE THREAD

**Issue by remidog77** [AllTheMods/atm6-sky#354]
**Describe the bug**
im trying to make a small skyblock server. every time i try to make a world with the type skyblock, it creates the overworld and a few blocks away will be a skyblock island just floating above the ground. ive tried 3 different times with the same results

is there a workaround or some specific command i have to run on the server console or setting i have to enable/disable?

**Comment by starforcraft** [comment]
Use the Type that gave Sky.
