### ISSUE TITLE
Cardboard Box and Netherite Barrel Dupe

### ISSUE THREAD

**Issue by cloudbrownie** [AllTheMods/atm6-sky#359]
**Describe the bug**
Using a cardboard box on a netherite barrel with certain items in the barrel causes those items to pop out onto the ground while also keeping those items in the barrel, effectively duping those items. So far rock crystals, attuned crystals, starmetal, constellation paper, and fluix crystals were found to have this behavior. Not sure if it works with other metal barrel tiers and not sure how many other items it affects.

**To Reproduce**

1. Place a netherite barrel down and place one of the listed items above into the netherite barrel. Ex. Rock Crystals
2. Use a cardboard box on the barrel.
3. Those specific items should pop out of the barrel once the cardboard box has been used.
4. Remove the cardboard box.
5. The inside of the barrel will have the same items that had just popped out.

**Expected behavior**
Contents of the barrel should stay in the barrel without duping while cardboard box is able to be picked up and used as intended.

**Screenshots**
![image](https://user-images.githubusercontent.com/58234071/117890876-f3762c00-b283-11eb-96c8-563ae1b6597b.png)
![image](https://user-images.githubusercontent.com/58234071/117890900-fffa8480-b283-11eb-9005-449770be42ce.png)
![image](https://user-images.githubusercontent.com/58234071/117890955-10aafa80-b284-11eb-9770-de01d98ddb59.png)
![image](https://user-images.githubusercontent.com/58234071/117891052-3d5f1200-b284-11eb-8bc9-2a0e0c30197e.png)

**Additional context**

**Comment by Mightylight** [comment]
i'm assuming this works for all barrels, or is it only netherite barrels

**Comment by kts325** [comment]
This is a known issue and afaik it's being fixed for next update
