### ISSUE TITLE
Silent Gear shears not taking damage when shearing Botania flowers

### ISSUE THREAD

**Issue by adammbaker** [AllTheMods/atm6-sky#36]
**Bug Description**
Silent Gear shears do not take damage when shearing Botania flowers.

**To Reproduce**
1. Pair of flint shears from Silent Gear.
2. Grow tall Botania flowers
3. Shear the flowers
4. Shears do not take damage

**Expected behavior**
I would expect that gear that should otherwise take damage should take damage when used.

**Additional context**
Pack: 1.0.2

**Comment by oly2o6** [comment]
need to report this to the mod developer instead of us unfortunately
