### ISSUE TITLE
1.09 Glowing Bee not producing Glowing Honeycomb

### ISSUE THREAD

**Issue by DeltaFifty** [AllTheMods/atm6-sky#360]
When looking at JEI, if you right-click on the Glowing Bee, it doesn't show a Bee Flower.  I've tried Compressed Cobble (x3), Glowstone, Lapis Lazuli Blox, etc..., but can't get any to work.

**Comment by starforcraft** [comment]
Will be fixed in the next Version.

**Comment by starforcraft** [comment]
> When looking at JEI, if you right-click on the Glowing Bee, it doesn't show a Bee Flower. I've tried Compressed Cobble (x3), Glowstone, Lapis Lazuli Blox, etc..., but can't get any to work.

Fixed in newest Version
