### ISSUE TITLE
1.09 Beepedia Glowing Bee Crash

### ISSUE THREAD

**Issue by DeltaFifty** [AllTheMods/atm6-sky#361]
**Describe the bug**
When using the Beepedia to try to figure out what flower (block) type to use for the Glowing Bee honeycomb production, I get a crash when clicking on the Breeding icon.  It does not appear to crash when clicking on the Breeding icon for other bees.

**To Reproduce**
1. Go to 'Right click Beepedia to open its interface'
2. Scroll down to 'Glowing Bee'
3. Click on the 'Breeding (flower) icon'
4. Crash

**Expected behavior**
Expected to see flower (block) type required for breeding to hopefully get a hint as to what type of flower (block) the Glowing Bee requires to produce honeycombs.  Although, this should be shown on the Info icon, but isn't.

**Error**
The game crashed whilst rendering screen
Error: java.lang.IndexOutOfBoundsException: Index: 0
Exit Code: -1

[crash-2021-05-12_00.23.42-client.txt](https://github.com/AllTheMods/atm6-sky/files/6463927/crash-2021-05-12_00.23.42-client.txt)

**Comment by starforcraft** [comment]
Fixed in newest Version
