### ISSUE TITLE
Rock crystal seed craft doesn't work 

### ISSUE THREAD

**Issue by JaviGamesHD** [AllTheMods/atm6-sky#362]
Pack version: 1.0.7
**Describe the bug**
When you try to craft rock crystal seeds from mystical agriculture it didn't work, even if you have 4 of the same crystals

**To Reproduce**
1. Place the prosperity seed in the middle altar
2. place the 4 supremium and 4 rock crystals in the other infusion altars
3. Give the middle altar a redstone signal

**Expected behavior**
Craft all the ingredients down to the rock crystal seed

**Comment by Mightylight** [comment]
i heard that all the rock crystals have to be the excact same. you have to have 4 crystals that all have shape 1 for example

**Comment by JaviGamesHD** [comment]
> i heard that all the rock crystals have to be the excact same. you have to have 4 crystals that all have shape 1 for example

I already do that. It didn't work aswell.
