### ISSUE TITLE
Bug on server: payload too big

### ISSUE THREAD

**Issue by GiacomoCorti** [AllTheMods/atm6-sky#365]
I made a selfhosted modded server and the first time when i entered the server, everything was OK. But then, the day after when i tried to login to the server i got the error: payload may not be larger than 1048576 bytes

**Comment by memyselfandcj** [comment]
I got this error and it was from having to many single stack items in my refined storage system. I was able to get on the server by changing max tick time and slowly delete said items by exporting into a trash can.
