### ISSUE TITLE
Mahou tsukai gets stuck in me system

### ISSUE THREAD

**Issue by Spikesx** [AllTheMods/atm6-sky#366]
So I was in the middle of upgrading my sword and I put it in my ME system not meaning too and now I cant get it out for the life of me I tried everything to pull it out I even made a new sword to try that and it still isn't working I also pulled the drive out that has it to add it to a me chest. The server I'm on is still on version 1.0.8 to the sky atm6

**Comment by stepsword** [comment]
maybe someone else can elaborate, but in the past someone said they were able to get it out using some sort of "filter" on the ME system. idk how to fix this on my end though as the logs dont say anything helpful to help me resolve it

**Comment by Spikesx** [comment]
I actually found one way to pull it out, I had to hook a fuzzy card to the export bus and she came right out
