### ISSUE TITLE
Garden of Glass Island Spawning reward generates errors in single player

### ISSUE THREAD

**Issue by MirrorImageQS** [AllTheMods/atm6-sky#368]
Just downloaded the pack. When I try to use the Garden of Glass Island Spawning quest, I get errors. If Allow Cheats is disabled, I get the message "Selector not allowed." If Allow Cheats is enabled, I instead get "The command cannot be used in a non-skyblock dimension." There are no additional messages in log file surrounding those messages that provide any more insight as to what's failing.

In either case, I seem to be left with the default skyblock island (with a lava bucket and block of ice).

This is on modpack version 1.0.9.

**Comment by oly2o6** [comment]
should be using skyblock world type
