### ISSUE TITLE
Tinker's construct manuals not allowed to be added to the Akashic tome

### ISSUE THREAD

**Issue by Glich440** [AllTheMods/atm6-sky#369]
**Description of the bug**
Tinker's construct manuals not allowed to be added to the Akashic tome

**To Reproduce**
1. Create an akashic tome and any of the tinker's construct manuals
2. Try to craft them toghether to get the manual inside the tome
3. See error

**Expected behavior**
Akashic tome with the book it was crafted with as an output for the craft

**Screenshots**
![imagen](https://user-images.githubusercontent.com/76230780/118358018-39c9d480-b57d-11eb-89cd-2018d64dffce.png)

**Comment by oly2o6** [comment]
report to tinkers
