### ISSUE TITLE
Destructive failure upon middle-clicking in Excompressum Auto Sieve

### ISSUE THREAD

**Issue by adammbaker** [AllTheMods/atm6-sky#37]
**Describe the bug**
Middle-clicking in an Excompressum Auto Sieve to sort the inventory 1) does not sort the inventory, 2) moves the item being sieved (gravel, in my case) to the center inventory, and 3) deletes the mesh (emerald mesh). Neither relogging nor breaking the Auto Sieve allow you to recover the mesh.

**To Reproduce**
1. Put gravel into a powered Auto Sieve from Excompressum.
2. Put an emerald mesh from Ex Nihilo: Sequentia into the correct spot in the Auto Sieve.
3. Middle-click the Auto Sieve's main inventory to use Inventory Tweaks Renewed's "sort inventory under cursor" functionality"
4. You'll see that the gravel is moved into the main inventory, presumable the mesh too, but the mesh disappears completely.

**Expected behavior**
If an inventory doesn't support "sort inventory under cursor" then it should non-destructively respond.

**Additional context**
Pack: 1.0.2

**Comment by Pdiddy973** [comment]
Already made a bug report with ExCompressum

https://github.com/blay09/ExCompressum/issues/309

**Comment by ariosos** [comment]
I saw this too - wasn't sure if it was the sorting button that did it, or some other mod  interaction (maybe sorting the mesh to the trashcan?)
