### ISSUE TITLE
spawning in overworld when joining newly installed server

### ISSUE THREAD

**Issue by funcle69** [AllTheMods/atm6-sky#370]
set up a server to play with friends with an online hosting company and we are all spawning in the overworld and not the sky, if i try single player i spawn in the sky. can anyone help pls

**Comment by funcle69** [comment]
nobody know what we need to do?

**Comment by Mightylight** [comment]
Not alot of people are on the github. What always works for me is make a singleplayer world and transfer that into the server as the new "world". If you want, try this. For these kind of questions in the future, join the discord. you'll probably get faster responses :)

**Comment by ArbitraryHubris** [comment]
level-type=skyblockbuilder\:custom_skyblock 

Replace your level-type line in your server.properties file on the server with the above and you'll have an island at spawn, as intended
