### ISSUE TITLE
Inventory Tweaks Organizing key deletes mesh inside of auto sieve

### ISSUE THREAD

**Issue by 23kswenson** [AllTheMods/atm6-sky#371]
When using the organize key Inventory Tweaks in the Auto Sieve from Ex Compressum the mesh is deleted from the Autosieve. From what I can tell it does this on all of the crushed materials/gravel.

**To Reproduce**
1. Have Auto Sieve
2.  Have Mesh in Autosieve (noticed mostly with Netherite Mesh)
3.  Activate the Sieve
4. Use the organize key

**Expected behavior**
Usually when I do this I expect for the inventory to be somewhat organized. If it doesn't organize thats fine but the mesh vanishes into the ether.

**Comment by starforcraft** [comment]
This is a issue from ExCompressum and not ATM 6 sky. See https://github.com/blay09/ExCompressum/issues/309
