### ISSUE TITLE
Fix to Skyblock Commands Quest

### ISSUE THREAD

**Issue by DrMrPotatoe** [AllTheMods/atm6-sky#372]
At the moment, the Discord is flooded with people asking what happened to thier island when the claim this quest, so i recommend adding a line to the top of the description to avoid any more confusion.
 {
            title: "Skyblock World Commands",
            icon: "astralsorcery:tree_beacon",
            x: -2.8d,
            y: -8.45d,
            shape: "gear",
            description: [
		"THIS QUEST WILL TELEPORT YOU TO A NEW ISLAND. IF CLAIMED ACCIDENTALLY, DO /skyblock spawn."
                "This world gen provides a semi-classic Skyblock island provided with a tree, a chest with lava and ice, and grass.",
                "",
                "Creating skyblock (provided by checking here)",
                "&c/skyblock create",
                "",
                "Teleporting to your island",
                "&c/skyblock home",
                "",
                "Seeing Teams (seeing all the names in the team if you add the team name)",
                "&c/skyblock list",
                "",
                "Visiting other islands",
                "&c/skyblock visit <team>",
                "",
                "Renaming Team",
                "&c/skyblock <new name>",
                "",
                "Inviting Players",
                "&c/skyblock invite <player>",
                "",
                "Accepting or Declining invite",
                "&c/skyblock accept/decline <team>",
                "",
                "Sending Join Request",
                "&c/skyblock join <team>",
                "",
                "Accept/Deny Request",
                "&c/skyblock tean accept/deny <player>",
                "",
                "Disabling requests",
                "&c/skyblock team allowRequests true/false"
            ],
            dependencies: ["3E01A250909FFC9A"],
            size: 1.5d,
            id: "05CBE9E9C9898250",
            tasks: [{
                id: "6C05E568E67A6C7A",
                type: "checkmark"
            }],
            rewards: [{
                id: "2DBF52D6FA12240A",
                type: "command",
                title: "/skyblock create",
                icon: "astralsorcery:tree_beacon",
                auto: "no_toast",
                command: "/skyblock create",
                player_command: true
            }]
        },

**Comment by starforcraft** [comment]
A PR would be **much** better

**Comment by Slaymeister** [comment]
I just ran into this one.  How would /skyblock spawn have fixed the issue?
