### ISSUE TITLE
specialised projectiles blueprint immersive engineering

### ISSUE THREAD

**Issue by cafelargo** [AllTheMods/atm6-sky#375]
it appears in JEI that the specialised projectiles engineers blueprint does not have a crafting recipe? is this on purpose?

**Comment by memyselfandcj** [comment]
You can get it from trading with an Immersive Engineering Gunsmith villager. 
![2021-05-23_23 00 54](https://user-images.githubusercontent.com/40968814/119290606-d2fe8800-bc1a-11eb-944e-0cacf2377441.png)

**Comment by cafelargo** [comment]
ty my dude
