### ISSUE TITLE
AllTheMods6 To The Sky v1.0.9 Resourceful Bees.

### ISSUE THREAD

**Issue by MikeThunder308** [AllTheMods/atm6-sky#379]
So I've started the Resourceful Bees mod. Ive got the original minecraft bees, but thats it. There is no crafting recipes for any of the bees except for breeding and block to block or block to item mutations. I cant get any of the other bees, am I doing something wrong?

**Comment by Mightylight** [comment]
the bees themselves are nog craftable, you can craft the spawn eggs. there's even a chart for it in the discord. https://miro.com/app/board/o9J_lLqaxQ4=/

**Comment by MikeThunder308** [comment]
Thats what Im saying none of the spawn eggs are craftable. All I get is an Information Tab that says, the capturing enchantment gives monsters a chance to drop their spawn egg. +0.4% chance per level (This is when I left click the Cobbee Spawn Egg in JEI. The other tab is the Block To Item Mutations With it saying that the Cobbee Bee mutates a Compressed Cobble X3 to a Cobbee Spawn Egg with a 25% chance of success. There is no crafting option.

**Comment by Mightylight** [comment]
are you maybe in a different version then 1.0.9? cause when i click on the cobbee i shows me the crafting recipe in the infusion altar

**Comment by MikeThunder308** [comment]
It say version 1.0.9 on the Profile and when I check the versions it says, Select Modpack Version - All the Mods 6 Sky-1.0.9 - (Release) - (current)

**Comment by MikeThunder308** [comment]
So I've found the problem, it was with kubejs. I had uninstalled that mod as it had combined all the ingots from several mods, and I prefer to have the ingots from different mods separate.

**Comment by Mightylight** [comment]
ok. not a good idea to remove that mod, as it is required to make the atm star

**Comment by MikeThunder308** [comment]
damn, when I try to change it so I dont have AllTheOres it freaks out, is there anyway to change this?
