### ISSUE TITLE
Infinity dirt production bug

### ISSUE THREAD

**Issue by Uginsecond** [AllTheMods/atm6-sky#38]
Hey! 
Seems, automated dirt production multiply the output ...
At least from one half-full single chest I got over the 3000 dirt.
![2021-03-17_07 52 21](https://user-images.githubusercontent.com/34199861/111421530-d561d480-86f5-11eb-82c7-069beae6b6d5.png)

UPD:
I found a problem - then oak leaves taken from the chest - they fill the barrel - and in same quantities back to chest ...

**Comment by Uginsecond** [comment]
UPD 2:
Any item, usable for dirt production do same...
So - is a bug.

**Comment by DizzyDJW** [comment]
Needs a better title so others with the same issue can find this easier
