### ISSUE TITLE
Sorting inside smeltery 

### ISSUE THREAD

**Issue by NemmieDragon** [AllTheMods/atm6-sky#383]
**Describe the bug**
When inside the smeltery inventory if you middle-click to sort inventory everything disappears. 

**To Reproduce**
1. Place items inside the smeltery
2. Middle click to sort inventory
3. Items disapear

**Expected behavior**
items to be sorted

**Screenshots**
![2021-05-20_15-29-36](https://user-images.githubusercontent.com/21026070/119041754-032cf900-b985-11eb-9651-9463a5723665.gif)

**Comment by oly2o6** [comment]
mod bug
