### ISSUE TITLE
bug when try to repair exchangers

### ISSUE THREAD

**Issue by ByArchery** [AllTheMods/atm6-sky#385]
**Describe the bug**
When u try to repair a exchanger in an anvil, if u put more than 1 item in my case iron to repair an iron exchanger, it use all items and dont recover more durability.

**To Reproduce**
1. go to the anvil
2. put the exchanger and material to repair
3. put more than 1 material
4. try to repair and it use all the material.

**Expected behavior**
like normal anvil works.

**Video**
https://user-images.githubusercontent.com/14233929/119044085-61ef7400-b97f-11eb-8cc7-918e2675d820.mp4

**Comment by starforcraft** [comment]
Report to Mod Author.
