### ISSUE TITLE
Easy villager lag

### ISSUE THREAD

**Issue by yutoe** [AllTheMods/atm6-sky#386]
Not really a bug but it seems that if you have a little too many easy villagers then it will start to lag the world as i had 42 easy villager farmers and it was making fps go from 50 down to 20 unless this is just a hardware problem and i just got a shitty pc and server

Thinking that if you have a server of 10 people and they each have 4 easy villager farmers then thats gonna be bad for the server

**Comment by Mightylight** [comment]
isn't this more something to adress on the issue page of the easy villagers mod? this doesn't have anything to do with the modpack, cause it's a singular mod that is causing this
