### ISSUE TITLE
pack name too long for GDLauncher. 

### ISSUE THREAD

**Issue by demethan** [AllTheMods/atm6-sky#387]
![image](https://user-images.githubusercontent.com/5810363/119067623-84e64c00-b9b0-11eb-8c15-ba1f61c7d0db.png)

FYI!

the pack name is too long and won't download on GDLauncher.  I will post that issue with them but thought you might want to know if you don't get as many downloads.

**Comment by DAmNRelentless** [comment]
We are aware of the but the pack name follows your pack naming conventions and therefor won't be changed.
Just rename the profile when installing the pack, no big deal.
