### ISSUE TITLE
Pedestal Upgrades are not working

### ISSUE THREAD

**Issue by Onebayishi** [AllTheMods/atm6-sky#388]
Pedestal Upgrades are not working
I'm using the 1.0.9 verison of the game and i cant use pedestal upgrades for generating netherrack & endstone

![image](https://user-images.githubusercontent.com/84566102/119109623-01694100-ba2a-11eb-8ea7-8a6b0c1a2079.png)

**Comment by Mightylight** [comment]
put the upgrade in your offhand and right click. it's a new feature to the pedestals mod

**Comment by Onebayishi** [comment]
> put the upgrade in your offhand and right click. it's a new feature to the pedestals mod

oh my god that was fast thank you <3

**Comment by Mightylight** [comment]
np. #githubfeedFTW
