### ISSUE TITLE
Spooky bee and magma bee not attempting to breed

### ISSUE THREAD

**Issue by SimenHus** [AllTheMods/atm6-sky#395]
Magma bee and Spooky bee do not initiate breeding after given their "flowers", even though both bees get heart animation.

Have a Spooky bee and Magma bee in an enclosed room and giving them respectively 5 Bone blocks and 5 Magma blocks. No combination of access to flowers and hive seem to work.

Expected behavior:
Step 1: Oolaalaa
Step 2: Maybe blazing bee
Step 3: Hearts disappears

Screenshots:
![2021-05-27_20 25 16](https://user-images.githubusercontent.com/84506051/119877954-eca91380-bf29-11eb-8b23-92638004ccb2.png)

On the screenshot the bees show no intrest in eachother, even though they should.

Additional context:
I am playing on singleplayer world with version 1.0.9

**Comment by SimenHus** [comment]
The problem seems to bee with the Resourceful Bees mod, as explained here:
https://github.com/Resourceful-Bees/ResourcefulBees/issues/239

A workaround is to use the apiary breeder (which works as inteded).
I'll close the thread, since it is already covered in the correct place.

**Comment by masakitenchi** [comment]
https://imgur.com/a/uhqNzFq
It seems that even tier 1 bees need to be **breedable** for them to actually breed higher tier bees. I have confirmed that after set lavabee and cobbee's _isBreedable_ parameter to true they now can breed stoned bee normally. Others still remain testing but I guess that's all.
