### ISSUE TITLE
Pedestals Harvesting Upgrade not giving extra Mystical Agriculture seeds

### ISSUE THREAD

**Issue by SimenHus** [AllTheMods/atm6-sky#396]
Describe the bug:
After using the Pedestals Harvester Upgrade to farm Mystical Agriculture for some time, I have noticed that i haven't recieved any extra seed drops other than the ones I already crafted

Have a Harvesting Upgrade (not advanced) break Mystical Agriculture seeds and then suck them up using Magnet enchantment.

Expected behavior:
After some time see an increase in the amount of seeds I have.

Screenshots:
![2021-05-27_20 32 53](https://user-images.githubusercontent.com/84506051/119879215-48c06780-bf2b-11eb-96b2-91c12553661b.png)

![2021-05-27_20 37 16](https://user-images.githubusercontent.com/84506051/119879305-6097eb80-bf2b-11eb-8853-48e31a07569c.png)

This is my farm. 

Additional context:
Playing singleplayer on 1.0.9

**Comment by DrMrPotatoe** [comment]
AFAIK, you only receive extra seeds if the farmland the seed is on is the same level or higher as the seed

**Comment by SimenHus** [comment]
> AFAIK, you only receive extra seeds if the farmland the seed is on is the same level or higher as the seed

I tried it and you are absolutely correct sir, thank you.
I'll close the thread.
