### ISSUE TITLE
ExtraStorage Crafters no button for redstone control

### ISSUE THREAD

**Issue by Thogro15** [AllTheMods/atm6-sky#398]
Crafters from ExtraStorage mod (Iron, Gold, Diamond, Netherite) does not have a button for redstone control when playing on a server. This is in version 1.0.9 of ATM 6 - To the Sky. When playing singleplayer the redstone control button is there. 

The Creative and normal crafters has the button for redstone control in both multiplayer and singleplayer.

**Comment by starforcraft** [comment]
Thats a issue from Extra Storage and not because of the pack. Please Report the bug [here](https://github.com/Edivad99/ExtraStorage) :)
