### ISSUE TITLE
Current Server (1.1.0) does not install correctly

### ISSUE THREAD

**Issue by jsuelwald** [AllTheMods/atm6-sky#399]
**Describe the bug**
Installation of Server (1.1.0) fails

Error message: "Error: Invalid or corrupt jarfile /home/mcserver/instances/atm6/atm6_tts_current/installer.jar"

**To Reproduce**
1. Downloaded and unpacked SIMPLE-SERVER-FILES-1.1.0.zip into an empty directory
2. chmod +x startserver.sh
3. ./startserver.sh 

**Expected behavior**
Server should be installed

**Screenshots**
![image](https://user-images.githubusercontent.com/2499585/120060819-4ad51400-c05a-11eb-8b0f-d4e868f60663.png)
![image](https://user-images.githubusercontent.com/2499585/120060848-5fb1a780-c05a-11eb-97f0-6dc38028a728.png)
![image](https://user-images.githubusercontent.com/2499585/120060852-68a27900-c05a-11eb-91b3-dc89f368c879.png)

Edit:
Server in running Ubuntu 20.04 LTS, SIMPLE-Server 1.0.9 unpacked and installed correctly 3 weeks ago.

**Comment by xCRABSTICKx** [comment]
Same as on Windows10....

**Comment by Pdiddy973** [comment]
use this .yaml file to fix, update to curse should be soon

[yaml fix.zip](https://github.com/AllTheMods/atm6-sky/files/6564228/yaml.fix.zip)

**Comment by jsuelwald** [comment]
Thanks for the quick fix :)
