### ISSUE TITLE
Crash when trying to start server on 1.0.2

### ISSUE THREAD

**Issue by LavaMunkee** [AllTheMods/atm6-sky#40]
When trying to create a server I run startserver.sh to create a serverstarter jar and then run startserver.bat, upon doing so I am given the error "Error: Invalid or corrupt jarfile serverstarter-1.2.7.jar" I have tried installing multiple times and have made sure to rename "new world" to "world" and get the same error each time.

**Comment by Qu3m** [comment]
How did you fix this issue?
