### ISSUE TITLE
Failed to Synchronize registry data from server - From version 1.0.9 to 1.1.0 (LAN WORLD)

### ISSUE THREAD

**Issue by RodrigoZXMota** [AllTheMods/atm6-sky#403]
**Description**
After the 1.1.0 update my friends are getting a data synchronization error similar to what happened in this issue here: https://github.com/AllTheMods/atm6-sky/issues/63.

We updated from 1.0,9 to the new 1.1.0 and are getting sync error when trying to join the my map via LAN (RadminVPN)

**To Reproduce**
1. Create a world in 1.0.9 and host it to LAN
2. Ask friends to join (Works fine)
3. Open same world in 1.1.0 and ask them to join
4. See error regarding synchronization data

**Expected behavior**
Friends joining as normal

**Extra Mods**
OptiFine_1.16.5_HD_U_G8.jar
AI_Improvements-1.16.2-0.3.0.jar
(Both versions are suited for 1.16.5 and were working in version 1.0.9)

**Screenshots**
![image](https://user-images.githubusercontent.com/72361609/120085166-31f54e80-c0ac-11eb-897a-ea582b7fa25f.png)

**Additional context**
We tried deleting the "data" folder from the save, as well as the "serverconfig" and "playerdata", none of them seemed to solve anything.

**Comment by Crewking** [comment]
I have the EXACT same problem!

**Comment by RodrigoZXMota** [comment]
> 
> 
> I have the EXACT same problem!

I imagined more people were having this problem, so I tried everything to gather information to help the devs fix this, for now we are just playing on 1.0.9 and waiting (I know this is the worst response but it is what it is)

**Comment by Crewking** [comment]
Ye, For us it dosent work on the old version either anymore so guess we will wait :)

**Comment by RodrigoZXMota** [comment]
You can try getting a backup of your world from the backup folder in you instance folder, i will be a .zip probably

**Comment by Crewking** [comment]
Hehe, We tried delete it and install it again so i dont have those left but i have our world saved.

**Comment by RodrigoZXMota** [comment]
If you deleted its still on the trash bin, check there

**Comment by Crewking** [comment]
I found a error in the logs when my friends tried to join.

Skipping config sync, No mods have registered a syncable config.

**Comment by tuantran1632001** [comment]
I have the same problem. Looking at the log found this:

`[17:22:02] [Render thread/INFO] [Astral Sorcery/]: Client cache cleared!
[17:22:02] [Render thread/INFO] [minecraft/ConnectingScreen]: Connecting to 192.168.100.18, 53882
[17:22:03] [Render thread/INFO] [Astral Sorcery/]: Built PerkTree with 417 perks!
[17:22:03] [Netty Epoll Client IO #2/INFO] [Silent Gear/]: Read 73 traits from server
[17:22:03] [Netty Epoll Client IO #2/INFO] [Silent Gear/]: Read 45 parts from server
[17:22:04] [Netty Epoll Client IO #2/INFO] [Silent Gear/]: Read 130 materials from server
[17:22:06] [Render thread/ERROR] [ne.mi.fm.ne.FMLHandshakeHandler/FMLHANDSHAKE]: Missing registry data for network connection:
	minecraft:block: cfm:black_trampoline
	minecraft:block: cfm:blue_trampoline
	minecraft:block: cfm:brown_trampoline
	minecraft:block: cfm:cyan_trampoline
	minecraft:block: cfm:gray_trampoline
	minecraft:block: cfm:green_trampoline
	minecraft:block: cfm:light_blue_trampoline
	minecraft:block: cfm:light_gray_trampoline
	minecraft:block: cfm:lime_trampoline
	minecraft:block: cfm:magenta_trampoline
	minecraft:block: cfm:orange_trampoline
	minecraft:block: cfm:pink_trampoline
	minecraft:block: cfm:purple_trampoline
	minecraft:block: cfm:red_trampoline
	minecraft:block: cfm:white_trampoline
	minecraft:block: cfm:yellow_trampoline

[17:22:06] [Netty Epoll Client IO #2/ERROR] [ne.mi.fm.ne.FMLHandshakeHandler/FMLHANDSHAKE]: Failed to load registry, closing connection.
[17:22:06] [Netty Epoll Client IO #2/ERROR] [ne.mi.fm.ne.FMLHandshakeHandler/FMLHANDSHAKE]: Connection closed, not continuing handshake`

Copying config files from the host does not solve the issue. The last time this happened we have to start a new world.

**Comment by oly2o6** [comment]
failed to sync is usually a server-client mismatch, you and your friends need a fresh install, a completely fresh one with the world transferred over to the new instance
