### ISSUE TITLE
Other Dimension Files

### ISSUE THREAD

**Issue by tonyvans** [AllTheMods/atm6-sky#405]
Hello, Just wanted to ask how I wipe the other dimension, without disturbing everything else.
what files do I need to delete from the server?
Thanks

**Comment by Pdiddy973** [comment]
/world/dimension/allthemodium/the_other
you need to stop the game/server before you delete the folder

**Comment by tonyvans** [comment]
my bad, I did see the allthemodium folder but did not realize it was in there

Thank you, that was exactly what I needed.
