### ISSUE TITLE
Missing recipe for quark - "Weather Detector"

### ISSUE THREAD

**Issue by WannesDC** [AllTheMods/atm6-sky#408]
I seem to have found a missing recipe for the weather detector by Quark. I ended up spawning one in, and throwing away the resources some wiki said they usually cost (x3 obsidian or x3 ender biotite, x3 purpur slabs, x3 glass). Tested it, and it seems to work perfectly fine, as when it rained it output a redstone signal, feeding my teru teru bozu, in turn clearing the weather:

https://gyazo.com/afaebb8275f37e403c0e1b81a1236f4b

**Comment by DAmNRelentless** [comment]
This is related to https://github.com/AllTheMods/atm6-sky/issues/377
The detector has no recipe because it's disabled in Quark config.
