### ISSUE TITLE
ATM:Sky 1.1.0 - Enrichment Chamber has two Certus Quartz Dust recipes

### ISSUE THREAD

**Issue by ariosos** [AllTheMods/atm6-sky#409]
1 - Look at the uses (U) for Certus Quartz Dust
2 - Go to the Enrichment Chamber tag. 

There are two crystal types (the top one is done by default).
![image](https://user-images.githubusercontent.com/7917753/120568869-ca5c3d80-c3e2-11eb-9783-afe7907fc2c9.png)

**Comment by ArbitraryHubris** [comment]
The recipe for pure certus quartz crystal should be removed since we already haved a recipe to create those by enriching certus quartz seeds.
