### ISSUE TITLE
Blackstone unobtainable

### ISSUE THREAD

**Issue by Catandcomparator** [AllTheMods/atm6-sky#41]
Blackstone seems to be unobtainable.

I tried bartering with piglins using MULTPLE STACKS of gold ingots, and i did not get any Blackstone. Someone must have deleted it from the loot table. and i cannot use pedestals, because that requires gilded Blackstone, which requires Blackstone.

**Comment by legitadimc** [comment]
You can find blackstone in the other, like in the other basalt deltas

**Comment by DarkBreaker09** [comment]
You can get Blackstone with Mystical Agriculture.

You need Nether Essence surrounding Stone Essence.
Took me a while to find it myself.
