### ISSUE TITLE
Making a Simple Machine Frame, JEI Move Items does not move 2 Plastic only 1 Plastic.

### ISSUE THREAD

**Issue by rolsch8026** [AllTheMods/atm6-sky#413]
**Describe the bug**
When making a Simple Machine Frame, JEI Move Items does not move 2 Plastic only 1 Plastic.
Same thing happens when making an Advanced Machine Frame, a Supreme Machine Frame & a Mycelial Reactor.

**To Reproduce**
1. Right Click a Simple Machine Frame in JEI.
2. Right Click Move Items.
3. Only one Plastic is moved to Crafting Grid.

**Expected behavior**
Two Plastic should be moved to Crafting Grid.

**Additional context**
Java Edition
Modpack Version: 1.16.5
Updated: May 28, 2021
MD5: 267f1f6b75f3c366dc8b7ee68cf9a41c

**Comment by oly2o6** [comment]
jei bug
