### ISSUE TITLE
PNC drones drop inferium essence

### ISSUE THREAD

**Issue by masakitenchi** [AllTheMods/atm6-sky#416]
**Describe the question**
When you disassemble PNC's drones they have a chance to drop Mystic Agriculture's inferium essence, which shouldn't(?) drop from non-mobs.

**To Reproduce**
1. Place a drone on the ground.
2. Use PNC's wrench to disassemble the drone.
3. If it doesn't drop a essence, go back to step 1.

**Screenshots**
![image](https://user-images.githubusercontent.com/11086210/120922284-38667480-c703-11eb-8308-faf3c43762d1.png)

**Expected behavior**
Shouldn't man-made artifacts not drop anything that comes from mobs since that's not balanced?

**Comment by kts325** [comment]
This would seem to be an issue with pneumaticraft themselves. If it's really an issue to you ask on the pneumaticraft github
