### ISSUE TITLE
Cant complete Spice of Life

### ISSUE THREAD

**Issue by HannaLarmore** [AllTheMods/atm6-sky#417]
There are tinkers jerky in the book that count to hearts and they are not there in the actual game some how in book additionally unsure how to obtain gelatinous Ichor drop since I cant find slimy dirt and cant find any mineshafts for suspicious stew.

1. Go to 'Food book' by spice of life
2. Click right until uneaten section 

**Expected behavior**
Either ways to obtain food; or the various tinkers construct jerkys, gelatinous Ichor, and suspicious stew (with suspicious stew in edelwood bucket) gone from spice of life book.

**Screenshots**
![food](https://user-images.githubusercontent.com/70218434/120957823-ff86c980-c71b-11eb-8924-132871528991.JPG)

![food hearts](https://user-images.githubusercontent.com/70218434/120957835-06154100-c71c-11eb-902d-ce365aca3bbd.JPG)

![image](https://user-images.githubusercontent.com/70218434/120957915-29d88700-c71c-11eb-8176-df20426efa34.png)

**Comment by clmurphy74** [comment]
I tried the very little known way of getting a brown Mooshroom, and they are supposed to give a bowl of suspicious stew, however, they do not.... :(  Sad that is not the way to be honest, as it's awesome!

**Comment by kts325** [comment]
I will be working on recipes for the unattainable foods as well as ways to get the harder to get foods

**Comment by T-Smith01** [comment]
@kts325 Is the recipe for the edelwood suspicious stew meant to be visible now? I'm still not seeing it in one of the latest versions of ATM6: To The Sky.
