### ISSUE TITLE
Getting 5 fps on ATM 6 sky

### ISSUE THREAD

**Issue by RkKai97** [AllTheMods/atm6-sky#418]
Just installed 1.16.5 ATM6-Skyblock and end with 5-7 fps on Ryzen 5 3500x and RX 470 (only allocating 4 GB RAM)
![2021-06-07_23 41 37](https://user-images.githubusercontent.com/81402938/121050269-03cde800-c7eb-11eb-9da3-7af16a07480a.png)

**Comment by Mightylight** [comment]
may i remind you that this pack has a reccomended of 8 gb's? So half that you should expect to not run smoothly, second i don't think this is a bug xD

**Comment by RkKai97** [comment]
Now, i installed optifine and it run around 40
