### ISSUE TITLE
Energy Pipe from Pipez doesn't work with Coal Generator from RFTools

### ISSUE THREAD

**Issue by its5Q** [AllTheMods/atm6-sky#419]
**Describe the bug**
Energy pipe can't extract power from Rftoolspower Coal Generator

**To Reproduce**
1. Place down the Coal Generator from Rftoolspower
2. Place a pipe on the coal generator and set it to extract with a wrench
3. The energy isn't being transmitted to other machines

**Expected behavior**
I expect it to be able to extract energy from the coal generator

**Additional context**
The latest alpha of Pipez doesn't have this problem

**Comment by kts325** [comment]
We tend to shy away from alphas of mods for official releases as they can cause problems. If you wish in your own to install the alpha, this is a pipez issue, and can be fixed as such.
