### ISSUE TITLE
No rewards showing in Questbook (ATM6-SKY v1.02)

### ISSUE THREAD

**Issue by JohnColling** [AllTheMods/atm6-sky#42]
**To Reproduce**
When clicking on any completed task in the quest book..no rewards are showing

**Screenshots**
![ATM6-Sky](https://user-images.githubusercontent.com/80932260/111719425-92476300-88a7-11eb-8ab4-f080e0cad9c2.PNG)

**Comment by WhitePhant0m** [comment]
They just aren't implemented yet
