### ISSUE TITLE
Can not make Silky Cobble Gen

### ISSUE THREAD

**Issue by rolsch8026** [AllTheMods/atm6-sky#421]
**Describe the bug**
Not able to make a Silky Cobble Gen.

**To Reproduce**
1. Right-Click on an Anvil.
2. Add a Pedestal Upgrade Cobble Generator Upgrade to left box of Anvil.
3. Add a Enchanted Book Silk Touch to center box of Anvil.

**Expected behavior**
An Enchanted Pedestal Upgrade Cobble Generator Upgrade with Silk Touch.

**Screenshots**

![2021-06-09_09 30 11](https://user-images.githubusercontent.com/82458985/121367121-0a05b680-c908-11eb-884f-96c82d191cc8.png)

![2021-06-09_09 31 27](https://user-images.githubusercontent.com/82458985/121367174-1558e200-c908-11eb-8393-2f1e660438a6.png)

**Additional context**
Java Edition
Modpack Version: 1.16.5
Updated: May 28, 2021
MD5: 267f1f6b75f3c366dc8b7ee68cf9a41c

**Comment by RobuxShooters** [comment]
The Silk Touch enchantment must be applied onto the Cobble Gen using the Pedestals Anvil.
