### ISSUE TITLE
Mystical Agriculture Essence 

### ISSUE THREAD

**Issue by tenshiamon** [AllTheMods/atm6-sky#43]
I have played the normal world of ATM6, but love Sky Block, but was surprised when ALLTHEMEDIUM / VIBRANIUM / UNOBTAINUIM essence seed recipes were missing. These items are already ridiculous to obtain and yes a grind, but if possible would like to see the recipes added like on original ATM6 modpack.

**Comment by davethwave** [comment]
There are also a variety of different essence seed types that are missing as well such as uranium and the like

**Comment by MelanX** [comment]
Can be closed, the seeds are in now
