### ISSUE TITLE
Magical Soil broken in 1.1.1

### ISSUE THREAD

**Issue by incomingnerd** [AllTheMods/atm6-sky#431]
**Describe the bug**
AllTheModium, Unobtainium and Vibranium seeds are no longer plantable on Magical Soil in release 1.1.1.

**To Reproduce**
Attempt to plant any of the magical tier seeds on magical soil. Fails to work in-world or botany pots.

**Expected behavior**
Under release 1.1.0 the seeds were plantable on magical soil, as expected.

**Versions**
Tested under a fresh instance of 1.1.1.

**Comment by incomingnerd** [comment]
Perhaps this was a bug introduced during the KubeJS refactor?

**Comment by DAmNRelentless** [comment]
Those seeds were also not place-able in v1.1.0 in-world.
The botany pot issue has been fixed in this pull request and will be released with the next update: https://github.com/AllTheMods/atm6-sky/pull/433
