### ISSUE TITLE
Infusion Crafting of a RGBee Spawn Egg does not work

### ISSUE THREAD

**Issue by rolsch8026** [AllTheMods/atm6-sky#435]
**Describe the bug**
Infusion Crafting of a RGBee Spawn Egg does not work.

**To Reproduce**
1. Place four Compressed Block of Lapis (3x) on four Infusion Pedestals.
2. Place four Dye Agglomeratio on four Infusion Pedestals.
3. Place a Dragon Scale on Infusion Altar.
4. Activate with a Redstone Signal using a lever.

**Expected behavior**
A RGBee Spawn Egg is created.

**Screenshots**
![2021-06-12_09 05 31](https://user-images.githubusercontent.com/82458985/121777018-f94e7e00-cb5d-11eb-8eb7-b241221c1ed9.png)
![2021-06-12_09 05 49](https://user-images.githubusercontent.com/82458985/121777022-fd7a9b80-cb5d-11eb-8e12-55699c3381cb.png)

**Additional context**
Java Edition
Modpack Version: All the Mods 6 - To the Sky-1.1.3
MD5: 40689010aedc55222c99ab1cc39c4d19

**Comment by kts325** [comment]
Can confirm this recipe works in the latest version
