### ISSUE TITLE
Wither Builder not consuming input items

### ISSUE THREAD

**Issue by predundant** [AllTheMods/atm6-sky#437]
**Describe the bug**
My wither builder setup doesn't run out of input items.  

**To Reproduce**
1. Set up industrial foregoing wither builder.  Set to "Run with Redstone", and place a lever on the front of the machine
2. Place diamond chest and put in wither skulls and soul sand
3. Use one piece of pipez item pipe to extract from the diamond chest and into the wither builder
4. Supply with power (I used a basic universal cable), and turn on the lever

**Expected behavior**
Wither builder should use 3 wither skulls and 4 soul sand each time it builds a wither.

**Screenshots**
![image](https://user-images.githubusercontent.com/32441423/121793230-4c561e80-cbba-11eb-934e-db1a887ffefc.png)
![image](https://user-images.githubusercontent.com/32441423/121793258-917a5080-cbba-11eb-8f5d-c4f0b7042630.png)

**Additional context**
Using version 1.14 of the pack and on single player.   I set this up and afk'd for a while, and came back to discover 1400 nether stars in storage, and the same amount of input items that I started with.

**Comment by kts325** [comment]
Will be looking into this

**Comment by kts325** [comment]
Fixed in upcoming update
