### ISSUE TITLE
[MP] Skyblock without tree or chest

### ISSUE THREAD

**Issue by Kazuto** [AllTheMods/atm6-sky#44]
**Describe the bug**
Skyblock without tree or chest after pressing the button.

**To Reproduce**
1. Download server pack v1.0.2
2. Rename `new world` to `world`
3. Start and join server
4. Press the button

**Expected behavior**
A world with tree and chest to get properly started.

**Screenshots**
![2021-03-19_22 35 21](https://user-images.githubusercontent.com/25435034/111844565-9012f200-8903-11eb-8276-ab3a318189ef.png)

**Comment by KazKazath** [comment]
I don't want to call you an idiot, but you're an idiot. The premade world in the server pack is default garden of glass, meaning you need to use the living wood roots under the sky block to get started. Did you even try and check what those mysterious blocks under the dirt even was? All you needed to do was break them and use an easy JEI search to know you can do botania stuff to get a sapling with it. smh

**Comment by KazKazath** [comment]
You were so quick to make a GitHub "bug report" that you didn't even bother to ask the discord either. There's just so much wrong here ngl.

**Comment by Kazuto** [comment]
I was excepting to get a regular skyblock world just like in single-player, especially because the notes of the server pack explicitly state  `(forge issues messing with botania's void creation for multiplayer, this world fixes it!)`. It should be noted that the default world type is "Garden of Glass" and differs from the default world type of SP worlds and how to change it to the regular SP world.

**Comment by KazKazath** [comment]
If you want a regular sky block world generation delete the world folder from your server when it's off and then on the next boot up it'll generate its own new world with the normal pack default of Skyblock and not garden of glass. And well whatever you do just don't go around slapping bug on am issue that was just you being misinformed

**Comment by KazKazath** [comment]
And also note that you created the server with the server pack made for servers, so the premade world with the special button was made so that you could have access to the gog commands, or at least I assume so. But yeah just delete the premade world that comes with the pack then boom.

**Comment by Kazuto** [comment]
Does not work as it just generates a completely regular Minecraft world. Before you ask: It's the default `server.properties` generated by the modpack with `level-type=default`.

![2021-03-19_23 10 50](https://user-images.githubusercontent.com/25435034/111847096-745e1a80-8908-11eb-8711-865ab7c6c499.png)

FIY: You can edit comments instead of creating new ones.

**Comment by oly2o6** [comment]
fixed in 1.0.2+ using the custom-skyblock world type instead of gog
