### ISSUE TITLE
Creative apiary interface broken

### ISSUE THREAD

**Issue by Godomos** [AllTheMods/atm6-sky#441]
**Describe the bug**
Unlocking a bee for activity in the creative apiary does not unlock the correct bee, but one in a seemingly random position in the list.
You also cannot export bees via the interface.
ATM6 Sky 1.1.5

**To Reproduce**
1. Create and populate a valid creative apiary
2. Import several bee species, more than 3
3. Try to unlock a specific bee, or export one.

**Expected behavior**
Targeted bee should be the one unlocked, or bees should export.

**Comment by starforcraft** [comment]
Can you maybe send your latest.log?

**Comment by Godomos** [comment]
it doesn't crash, just doesn't work properly.

**Comment by starforcraft** [comment]
> it doesn't crash, just doesn't work properly.

Yeah but maybe there is happening an error.

**Comment by Godomos** [comment]
Gotcha, it seemed to throw an error during export, but not during "unlocking".

https://paste.ubuntu.com/p/HsvnKKKqSh/

**Comment by kts325** [comment]
Should be fixed soon enough
