### ISSUE TITLE
AE2 Encoded patterns not showing recipes correctly

### ISSUE THREAD

**Issue by masakitenchi** [AllTheMods/atm6-sky#442]
**Describe the bug**
When you insert encoded patterns into the interface terminal, the encoded pattern is expected to show the output item rather than showing the icon of "encoded pattern". While this works correctly in ATM6, the skyblock version seems to break this and something here is causing this to happen.

**To Reproduce**
1. Open the pattern terminal and encode any recipe into it
2. Put that encoded pattern in a ME interface
3. Open the interface terminal

**Expected behavior**
What should be shown (ATM6)
![image](https://user-images.githubusercontent.com/11086210/121855777-b099ef00-cd2e-11eb-816d-c27378a8611b.png)

**Screenshots**
What shows in skyblock version(Showing the "encoded pattern" icon)
![image](https://user-images.githubusercontent.com/11086210/121855680-98c26b00-cd2e-11eb-86e7-26935b99ea01.png)

**Additional context**
I also found that some patterns show nothing when pressing shift. Is this related to some sort of loss of models?
![image](https://user-images.githubusercontent.com/11086210/121855879-cd362700-cd2e-11eb-9782-391c3cfcfd59.png)

**Comment by kts325** [comment]
This I beleive is an intended feature from ae2 to prevent lag when accesing the interface terminal as rendering all the blocks causes lag

**Comment by kts325** [comment]
If this in unintended it would be the fault of ae2, nothing we can do about ot

**Comment by shartte** [comment]
Nah, we switch to the pattern output in the terminal, but something seems to be interfering with slot rendering.

However. I've been testing with ATM6:S a few weeks back, but didn't have this issue. I _did_ have issues with patterns rendering garbage when holding shift though.... Weird stuff.
