### ISSUE TITLE
ver 1.1.5 Island creation problem

### ISSUE THREAD

**Issue by AhSchoo** [AllTheMods/atm6-sky#443]
**Describe the bug**
New player on a server, tries to /skyblock create and fails with "you are already a member of a team"
/skyblock leave appears to work but then the issue persists with the /skyblock create anyway.
trying to invite the player to an existing team gives an error? " is already in a team" without their name.

**To Reproduce**
with a brand new player.
/skyblock create

**Expected behavior**
Expected to teleport to a new island.

**Screenshots**

**Additional context**

**Comment by Trinium12** [comment]
if its single player u gota have cheats enabled and if its a server u gota have op to fix the problem do /skyblock manage teams delete spawn

**Comment by bribri69** [comment]
Hello,

Some more informations : 
On server we've delete the "spawn" team and players created their own island.
But, when someone leave his team, the "spawn" team is automaticaly recreated... (a new island is created and break our beautiful spawn T_T )

**Comment by kts325** [comment]
This issue has been reported to the dev and should be fixed in the next update
