### ISSUE TITLE
Item Duping with Auto Clicker

### ISSUE THREAD

**Issue by Madman899PB** [AllTheMods/atm6-sky#451]
**Describe the bug**
You can duplicate items in the auto clicker from the auto clicker mod by rotating it with any wrench type item (tried with Engineer's Hammer and Wooden Wrench).

**To Reproduce**
1. Place item in auto clicker
2. Right click with wrench 
3. Block rotates and item pops out but also stays in the clicker

**Expected behavior**
Only wanted block to rotate.

**Comment by kts325** [comment]
Known bug. Afaik nothing we can do to fix it but will try to find out something
