### ISSUE TITLE
Compact Machine Chunk Loading

### ISSUE THREAD

**Issue by YAGYREVMAI** [AllTheMods/atm6-sky#452]
Is chunk loading in compact machine disable? Cause compact machine originally has chunk loading feature but now it doesn't load ,  i have to chunk load it with ftb chunk loader and its limiting the given chunk loader. Any solution?

**Comment by Mightylight** [comment]
There's no solution, just increase the max chunks lpaded in the config for FTBchunks

**Comment by DAmNRelentless** [comment]
The config was not edited. This means the default configuration for Compact Machines is used.
Since you can just chunkload the machines with FTB Chunks, I don't see a reason to overwrite the setting for it.
