### ISSUE TITLE
Item dupe Bug, creative constructor drop item mode, 

### ISSUE THREAD

**Issue by EnrichedDragon** [AllTheMods/atm6-sky#458]
Creative Constructer, Refined storage. When used dupes what ever item is set to be dropped, to the point of reaching 1 fps, 1 stack of dirt becomes 13 

To reproduce  power a creative constructor in drop block mode

**Comment by starforcraft** [comment]
Fixed: https://www.curseforge.com/minecraft/mc-mods/cable-tiers/files/3355337
