### ISSUE TITLE
End on Skyblock World doesn't generate end cities

### ISSUE THREAD

**Issue by Jimbopanda** [AllTheMods/atm6-sky#46]
**Describe the bug**
When using the World Type: Skyblock, end cities do not spawn in the end. 
When using the World Type: Garden Of Glass, end cities do spawn

**To Reproduce**
1. Launch version 1.0.2
2. Change "World Type" to "World Type: Skyblock"
3. Enter End
4. Do `/locate endcity`

**Expected behavior**
Expected end cities to spawn for obtaining elytra and other materials but instead none generate. When `/locate` is run on regular worlds and on the GoG world type, the command returns the location of the nearest end city, wheras nothing is returned using the Skyblock world type

**Additional context**
Tested in 4 different worlds. 2 GoG worlds spawned end cities. 2 Skyblock worlds didn't generate end cities.

**Comment by jeremiahwinsley** [comment]
This is the intended behavior for the Skyblock world type.

**Comment by koopa02** [comment]
how would one enable them should they want one

**Comment by jeremiahwinsley** [comment]
Edit config/skyblockbuilder/common-config.json5 and:

Add `minecraft:endcity` to this list:
```
    "generationStructures": {
      "whitelist": true,
      "elements": [
        "minecraft:fortress"
      ]
    }
```

like this:

```
    "generationStructures": {
      "whitelist": true,
      "elements": [
        "minecraft:fortress",
        "minecraft:endcity"
      ]
    }
```
This should work on existing worlds, you may need to regenerate the end dimension.


If you want the end islands too, change false to true here:
```
    "End": {
    
      // Should end generate as in default world type? [default: false]
      "Default": false,
```

This only works on new worlds, or if you edit the level.dat to fix it manually.
