### ISSUE TITLE
Red stone control button for Refined Storage, Extra Storage, and Creative Crafters not working or not showing

### ISSUE THREAD

**Issue by Ratomas** [AllTheMods/atm6-sky#461]
Redstone control buttons for Refined Storage, Extra Storage, and Creative Crafters either not working or not showing up in ATM 6 To the Sky v1.1.6. I am not sure yet weither this is a Refined Storage issue or a ATM issue. I am going to trying upgrading Refined Storage or downgrading depending on the current version, but any input would be appreciated.

**Comment by Ratomas** [comment]
Upgraded Refined Storage to 1.9.13 and still having nonfunctional or not existent redstone control button.

**Comment by DAmNRelentless** [comment]
Did you try to reproduce this with just Refined Storage in another instance? If you are not sure whether this comes from RS or ATM, the option option would be to test it without the modpack.

**Comment by Ratomas** [comment]
Yeah tried that. It is not RS, also it is affecting Extra Storage and Creative crafter.

**Comment by kts325** [comment]
Then it has to be an issue with whatever api for redstone control is shared across addons

**Comment by Ratomas** [comment]
Anyone know what API that is?

**Comment by kts325** [comment]
I'm currently using the latest release of the pack and can't reproduce the redstone control not working... And I have no idea, you'd have to ask the refined storage dev

**Comment by Ratomas** [comment]
Ok I am going to try reinstalling the server and the client to see if maybe during the last upgrade something went wrong.

**Comment by Ratomas** [comment]
Never mind. After reinstall of server and restore of my world, world became corrupt. So problem gone.
