### ISSUE TITLE
Failed to sync registry data

### ISSUE THREAD

**Issue by JokerXiPu** [AllTheMods/atm6-sky#462]
I host a skyblock via LAN with hamachi for my friend and I. We started playing ATM6 sky on 1.1.3 and updated to 1.1.5 with no problem. Recently, we have updated to 1.1.6 and then came across an issue where my friend can no longer join and the message he gets says failed to sync registry data. I have tried these things so far: Both version 1.1.5 and 1.1.6 fresh installs while moving the world over, giving him my config and kubej files, and probably more that i just cant remember at the moment. Ive concluded its the World due to the following reasons, he is able to join on other packs perfectly fine, and ive created a brand new world and he is able to join there as well. I've tried using a backup which i couldve sworn was before i updated but the issue still remains. I have never messed with any configs or anything. Any advice? And just to clarify, i can play just fine. He just cannot join.

**Comment by TheJustice01** [comment]
Same problem for me, but it is in the "normal" pack. With a new world there's no problem, alla mods are the same, same version of the pack, canceled various times config folder as the forums say but nothing. I need help too

**Comment by oly2o6** [comment]
failed to sync means the client and server files are mismatched, try getting a fresh update on the server and/or the client
