### ISSUE TITLE
Bee spawn egg errors

### ISSUE THREAD

**Issue by Slaymeister** [AllTheMods/atm6-sky#464]
All issues can be verified in JEI.

Issue:
Iron bee (resourcefulbees:ironbee) block to item mutation ability transforms a lead honeycomb (resourcefulbees:lead_honeycomb_block) to a (20%) lead bee egg (resourcefulbees:lead_bee_spawn_egg).

Expected Behavior:
(resourcefulbees:ironbee) block to item mutation ability transforms an iron honeycomb (resourcefulbees:iron_honeycomb_block) to (20%) an iron bee egg (resourcefulbees:iron_bee_spawn_egg) or (80%) an iron ingot (minecraft:iron_ingot). Lead bee is obtainable by breeding so the iron bee block transformation to lead bee egg can be left out.

Issue:
Unobtainium bee (resourcefulbees:unobtainium) block to item mutation is from a lava spawn egg (resourcefulbees:lava_bee_spawn_egg) to a bee mob (resourcefulbees:lava_bee) rather than a spawn egg item.  Unobtainium spawn egg formula is missing.

Expected Behavior:
(resourcefulbees:unobtainium) block to item mutation is from an unobtainium honeycomb block (resourcefulbees:unobtainium_honeycomb_block) to (20%) an unobtainium bee egg (resourcefulbees:unobtainium_bee_spawn_egg), (20%) a soul lava bee egg (resourcefulbees:soul_lava_bee_egg), or (60%) and unobtainium nugget (allthemods:unobtainium_nugget). This is the only way I found to get a soul lava bee, so it should not be removed.

Issue:
Obsidian bee (resourcefulbees:obsidian_bee) is missing a spawn egg block to item mutation.

Expected Behavior:
Obsidian bee (resourcefulbees:obsidian_bee) block to item mutation is from an obsidian honeycomb block (resourcefulbees:obsidian_honeycomb_block) to (20%) an obsidian bee spawn egg (resourcefulbees:obsidian_bee_spawn_egg) or (80%) an obsidian block (minecraft:obsidian).

Issue:
Stoned bee (resourcefulbees:stoned_bee) is missing a spawn egg block to item mutation and also Dave, who is not here, man.

Expected Behavior (WARNING: BALANCE CHANGE):
Stoned bee (resourcefulbees:obsidian_bee) block to item mutation is from an stoned honeycomb block (resourcefulbees:stoned_honeycomb_block) to (20%) an obsidian bee spawn egg (resourcefulbees:stoned_bee_spawn_egg) or (80%) a smoker (minecraft:smoker). Trying for the Stoned Bee spawn egg may leave you with more smokers lying around doing nothing, which checks out.

Notes: 
-Oreo, Kitten, Stan bees do not have spawn egg recipes. This looks intentional, though I see the current pull request to add one for kitten. Don't know if this should be part of the bug report or not.

**Comment by Slaymeister** [comment]
Pull request created for the iron, stoned, and obsidian bees.  The issue with unobtanium bees may be a misunderstanding on my part. Will confirm and circle back if it needs a fix.

**Comment by ladylexxie** [comment]
Fixed in #469 and #459
