### ISSUE TITLE
I&F dragon egg doesn't hatching

### ISSUE THREAD

**Issue by Neythi** [AllTheMods/atm6-sky#468]
Hello,

I have a problem with hatching I&F eggs (tested on version 1.1.0 and 1.1.6). I put the fire egg in the fire, but the egg don't want to shake. I've been waiting for an hour and the dragon still doesn't want to hatch. I'm doing something wrong? (Egg is laid in fire on a 3x3 netherack platform). Thank you in advance for your reply.

**Comment by oly2o6** [comment]
worked fine for me so most likely doing something wrong
