### ISSUE TITLE
Creative Crafter

### ISSUE THREAD

**Issue by DropBear28** [AllTheMods/atm6-sky#477]
**Describe the bug**
The creative crafter literally crashes the game when you open the inventory

**To Reproduce**
1. Go to '...' Place a creative crafter
2. Click on '....' Creative crafter
3. Scroll down to '....' Try to place an item inside
4. See error instant game crash

**Expected behavior**
To be able to store patterns in the inventory
**Screenshots**
![image](https://user-images.githubusercontent.com/86392430/123196097-a5904d00-d4ec-11eb-8f58-c34771ce7f3d.png)

**Additional context**

**Comment by kts325** [comment]
Issue with crashing and lag fixed in latest RS and creative crafter update, neither of which are in the pack yet, will be fixed in next update
