### ISSUE TITLE
Ice and Fire Dragon Duplication

### ISSUE THREAD

**Issue by Avalorr** [AllTheMods/atm6-sky#479]
**Describe the bug**
I created 12 ice Dragons with one egg using Time in a Bottle.

**To Reproduce**
1. Create a pool of water
2. place ice dragon egg in water
3. use time in a bottle on the ice created by dragon egg
4. i got 12 dragons from one egg

**Expected behavior**
i was just hoping it would hatch quicker.

**Comment by oly2o6** [comment]
not exactly something we can fix
