### ISSUE TITLE
Auto crafters not working with Mystical Agriculture

### ISSUE THREAD

**Issue by ethanmanb** [AllTheMods/atm6-sky#481]
I have this problem where I want to automate making insanium essence using auto crafting but I can’t get any of the auto crafter to upgrade essence to the next tier of essence

First auto crafter I used was the crafting machine with cyclic and set the recipe inside it. It does any other recipe except upgrading essence to the next tier. It will turn essence into blocks but won’t upgrade the blocks into the next tier either

Second auto crafter I used was crafter tier 3 RFToolsutility. I set the recipe and hit accept. It’s full on power. Wont upgrade to next tier but will turn into blocks but wont upgrade blocks to next tier either. Has space inside its own inventory to circulate all items. 

**Additional context**

on version 1.1.0 and 1.16.5 Minecraft and 36.1.24 forge.

**Comment by oly2o6** [comment]
its to do with the crystal becoming damaged after the first pass, most crafters cannot handle it
