### ISSUE TITLE
The Other - Won't let me back?

### ISSUE THREAD

**Issue by Jreil1981** [AllTheMods/atm6-sky#482]
I have put in Many hours into my world getting strong enough to get to the other and take on the Dragons.
I setup my Nether & Other portals early just to have them established. I have since moved things around my base and took down the nether portal. I did NOT take the "OTHER" portal down when I broke the nether portal. Now that I am strong enough to face the other dimension, I made a new teleport pad, and it doesn't let me do anything. Attempt to shift+right click and nothing. No animation, nothing. PLease any help with debugging this or ideas on how to fix it would be extremely appreciated, I don't want to start all over.

**Comment by Gh3ttoboy** [comment]
Are you by chance holding a shield in your offhand or anything else i know you cant use the teleport pad if you have something in your offhand
