### ISSUE TITLE
server side bug that wont display server on client side and server gives errors stating whats going on

### ISSUE THREAD

**Issue by zxoltari** [AllTheMods/atm6-sky#485]
this is what it says on server everytime a client refreshes there game String too big (was 34353 bytes encoded, max 32767
[latest (1).log](https://github.com/AllTheMods/atm6-sky/files/6759047/latest.1.log)

**Comment by zxoltari** [comment]
server name is gamingnetworks
server host is https://www.minecraft-hosting.pro/

**Comment by zxoltari** [comment]
![Screenshot 2021-07-03 181747](https://user-images.githubusercontent.com/86894631/124368058-13deb900-dc2b-11eb-8a34-5da7dd52e0c3.png)

**Comment by zxoltari** [comment]
![Screenshot 2021-07-03 182041](https://user-images.githubusercontent.com/86894631/124368098-7b950400-dc2b-11eb-98a9-9c78e4cd59c8.png)
![Screenshot 2021-07-03 182107](https://user-images.githubusercontent.com/86894631/124368100-7df75e00-dc2b-11eb-8946-2f5d0254b6f7.png)

**Comment by oly2o6** [comment]
server icon too large, should be fixed with the current forge
