### ISSUE TITLE
Memory leak/Memory usage slowly creeping up, then game freezes repeatedly.

### ISSUE THREAD

**Issue by MaPePeR** [AllTheMods/atm6-sky#486]
After some time playing my game starts to freeze every so often. I have the feeling the time between freezes decreases with playtime as well.
I *assume* this is a memory leak, because when I start the game the memory usage starts at around 3-4GB, but when the freezes occur it is close to the max memory limit of 8GB. I increased that limit to 10GB, but that didn't fix it. When the freeze occurs it also uses all of my CPU power. So I think this is the garbage collector triggering, but not able to free enough space?

Sadly I don't know if this is related to some specific mod or block I started using. Is there any way to find out more details and do you share my assumption, that this is memory leak/garbage collector related?

**Additional context**
Because of the problems I recently updated from 1.1.0 to 1.1.6, but the problem still exists.

**Comment by bribri69** [comment]
Hello,

I recently had lag cause of compact machine. Maybe you can remove the mod for testing?

**Comment by MaPePeR** [comment]
I think I found the culprits:
* I probably had a Resourceful Bee bookmarked in JEI, which caused a lot of entitys being created in its render method. (So: Don't do that right now)
* Then I had an apiary breeder running that also created a lot of Entitys. 
* The Citadel Mod prevents Entitys from being garbage collected, which makes everything worse.

Not using the apiary breeder and not looking at bees in JEI fixed my freeze problems, even though the biggest bug is in Citadel.

Related issues:
* Resourceful-Bees/ResourcefulBees#266
* Alex-the-666/Citadel/issues/38

**Comment by MaPePeR** [comment]
Updating Citadel to 1.7.2 fixed this problem for me.
