### ISSUE TITLE
problem when a player rejoin the server he will lose all his item

### ISSUE THREAD

**Issue by M7MD4e** [AllTheMods/atm6-sky#488]
there is a problem when a player joins the server destroy the previous player and re-spawn the player at spawn and all his item will fall at his previous location
for example when a player logs out of the server at location A the rejoin the server sometime later he should be at location A but he is not. his location become the spawn point and all the item that was in his inventory fell of at location A and he can go the collect them

**To Reproduce**
it happens from time to time 

**Additional context**
I contacted the host and their support team thinks it's a problem with the pack itself 

"It appears to be an issue with a mod specifically not syncing as it says players have not joined for 3 days, I would recommend reaching out to the mod pack developers on this issue to see if they have a fix for this."

04.07 03:52:39 [Server] Timer-0/INFO [co.da.cr.CrashUtils/]: Unloading chunks for players that have not been online in: 3 Days
04.07 03:52:39 [Server] Timer-0/INFO [co.da.cr.CrashUtils/]: [] Player(s) affected 
04.07 04:00:00 [Server] Server thread/INFO [tombstone/]: All players have been successfully backed up
04.07 04:20:00 [Server] Server thread/INFO [tombstone/]: All players have been successfully backed up
04.07 04:40:00 [Server] Server thread/INFO [tombstone/]: All players have been successfully backed up

that what they said

**Comment by radiomike** [comment]
Is your server configured to offline mode?

**Comment by M7MD4e** [comment]
no

**Comment by radiomike** [comment]
So the line `Unloading chunks for players that have not been online in: 3 Days` is just information and if you read the following line, doesn't affect any players. So I don't think it's related to this. 

What pack version are you using?

**Comment by M7MD4e** [comment]
v 1.1.6

**Comment by eternalarc** [comment]
I am experiencing the same problems! My Console looked exactly like OP. I check the server.properties file to see if it can be modified, however there is nothing in there for Unloading Chunks.

**Comment by M7MD4e** [comment]
What are you using ?

**Comment by eternalarc** [comment]
Same version. 1.1.6.

**Comment by M7MD4e** [comment]
Oh I want to write what host you are using ?

**Comment by M7MD4e** [comment]
I'm using pebble host

**Comment by eternalarc** [comment]
I'm using Bisect Hosting.
