### ISSUE TITLE
Nether quartz dust not listed in JEI

### ISSUE THREAD

**Issue by mdereus** [AllTheMods/atm6-sky#489]
**Describe the bug**
Searching for nether quartz dust in JEI does not show the item.

**Expected behavior**
Nether quartz dust appears in the JEI item list.

**Screenshots**
![netherquartzdust](https://user-images.githubusercontent.com/24309572/125215650-aca3b300-e281-11eb-9224-a38bfad48754.JPG)

**Comment by cdgamedev** [comment]
Weird.

How did you make the dust? Because recipes seem to use the Quartz Dust from Thermal Series instead of the Nether Quartz Dust from AE2.

I'm assuming the two are interchangeable?

**Comment by mdereus** [comment]
> How did you make the dust? Because recipes seem to use the Quartz Dust from Thermal Series instead of the Nether Quartz Dust from AE2.
You can get it from sieving dust.
