### ISSUE TITLE
Game crash when adding a bucket to the fluid pump pedestal

### ISSUE THREAD

**Issue by Pivasnik** [AllTheMods/atm6-sky#49]
**Describe the bug**
Found this by accident by missclicking my bucket. 

Okay tried recreating it and found where the issue pops up.

1. 2x2x2 water hole with a pedestal with fluid pump upgrade at the bottom.
2. Pedestal with the fluid tank upgrade (to have fluid storage for water) put anywhere.
3. Pedestal with the fluid extractor (not fluid drain) upgrade which puts fluid 1 block bellow there it is. 
4. Latex processing unit (or what's it called_ which takes liquid latex and water to produce rubber below the pedestal with the fluid extractor upgrade.
5. Link the pump pedestal to put the water into the tank.
6. Link the tank to put the water into the fluid extractor. 
7. Put bucket into the fluid pump pedestal. (doesn't crash with that)
8. Bucket goes to the fluid tank (doesn't crash with that)
9. Bucket goes to the fluid extractor (crashes there)

All in all you could probably remove the tank and get the same outcome by just linking the pump pedestal with the extractor pedestal. But everything I described was my setup when I tried recreating it in a creative world. 

**Expected behavior**

**Screenshots**
Can't put screenshots, impossible to load the world.

**Comment by oly2o6** [comment]
this is a mod issue and should be reported to the author instead of us
