### ISSUE TITLE
Diamond ring not required

### ISSUE THREAD

**Issue by Floppa-8765** [AllTheMods/atm6-sky#493]
**Describe the bug**
you dont need a diamond ring to craft diamond and platinum jetpacks from the Iron Jetpacks mod
**To Reproduce**
1. launch the game
2. enter a world
3. look for platinum/diamond jetpacks in JEI
4. see that they both have two recipes, one of which does not have a diamond ring in it

**Expected behavior**
only one recipe each that requires diamond ring
**Screenshots**

**Additional context**
https://i.imgur.com/g5BhhnU.png
https://i.imgur.com/hfpUKhf.png

**Comment by chadandersen1** [comment]
Why was this closed with no further info? This hasn't been fixed. Which recipe is the correct one?
