### ISSUE TITLE
Unable to put water in barrel

### ISSUE THREAD

**Issue by SimplyRobotic** [AllTheMods/atm6-sky#497]
I just started a new game, but i can't seem to be able to put water in Ex Nihilo barrels from the ceramic buckets. I can pick up water from sources and crucibles, but it just wont put water in the barrels.

Just start a new game, craft a wooden or stone barrel, and  try right-clicking with a ceramic water bucket. It just won't work.

**Expected behavior**
Water should normally appear in the barrel and allow fluid-to-item transforms.

**Comment by BovineShaman** [comment]
Was able to replicate, normal buckets work fine though.

**Comment by JRCLARK25** [comment]
Yes i too can confirm. I just used water bottles until i got iron to make normal bucket. thought is was WAI to make early game push towards Iron

**Comment by oly2o6** [comment]
ill see if its possible to work on from our side, but sounds like something one of the authors isn't checking for
