### ISSUE TITLE
FPS just only 2

### ISSUE THREAD

**Issue by zzs269285304** [AllTheMods/atm6-sky#499]
The load on the graphics card is always 100%，my GPU is AMD RX 580 8GB,The game version number is ATM Mods 6 Sky v1.1.6

**Comment by notFalkon** [comment]
lower mipmapping

**Comment by SeekerCreeper** [comment]
Try installing optifine, and in performance, turning on smart animations. For some reason AMD cards are hit hard by this pack.

**Comment by oly2o6** [comment]
Amd cards are hit hard by 1.16 in general, disabling mipmaps is the number1 thing i do personally too
