### ISSUE TITLE
item drop on the floor when rejoining serveur

### ISSUE THREAD

**Issue by laurie2132** [AllTheMods/atm6-sky#502]
when i login in my server all the item in my inventory are drop on the floor and my player restart a spawn point.

**Comment by Mass1milian0** [comment]
I can confirm this, ill provide a more detailed description:
First of all our whole island is claimed with ftbchunks if that matters
When rejoining, your player disconnects normally,
When riconnectiong, your inventory (only normal inventory, not curious or anything else), gets dropped on the floor on the location the player disconnected, you respawn on the starter island, in our case we made another island as we are all playing in a team (same team on skyblock and ftb), all achievement are reset upon that happening

**Comment by Comeza** [comment]
I have the same issue on my server.
We do not use SkyBlock Builder (everyone is in the Spawn team)

After you log in you drop all items and spawn at the default spawn of Skyblock Builder
