### ISSUE TITLE
Game crashes after quitting and re-entering the same world

### ISSUE THREAD

**Issue by TreeryMAA** [AllTheMods/atm6-sky#508]
**Describe the bug**
After quitting the world and re-entering the same world again, the game crashes. This seems only happened after I used compact machine

**To Reproduce**
1. Quitting the world
2. Re-entering the same world

**Expected behavior**
The world should be loaded normally.

**Screenshots**

**Additional context**
[crash-2021-07-22_19.57.38-server.txt](https://github.com/AllTheMods/atm6-sky/files/6862043/crash-2021-07-22_19.57.38-server.txt)

**Comment by radiomike** [comment]
You seem to have sodium installed, try again without that and see if it makes a difference.

**Comment by TreeryMAA** [comment]
After some debugging, I seems to find out the cause the crash.

I am using external storage in the compact machine and every time I reload the world I need to manually trigger the external in order for it to work.
Thus I set the external storage to "only work with redstone signal" and use redstone transmitter and receiver from RFToolsUtility to trigger it.

After I remove the the redstone transmitter and receiver, the crash no longer occurs.
However I still need to manually trigger the external storage, which is pretty inconvenient.
