### ISSUE TITLE
Bookshelf from Builders Craft won't accept Tinkers' crafted book.

### ISSUE THREAD

**Issue by joelou1** [AllTheMods/atm6-sky#509]
**Describe the bug**
Trying to add Tinkers' crafted books to Builders Craft's Bookshelf won't add them to it. So far, normal books, akashic tome and written books can enter properly.

**To Reproduce**
1. Craft and place any bookshelf from Builders Craft.
2. Place books (Any) into the bookshelf.
3. Notice that some books from Tinkers (So far being Puny/Mighty Smelting, Fantastic Foundry AND Tinker's Gadgetry) won't enter the bookshelf.

**Expected behavior**
Tinkers' books should be able to enter the slots of a Bookshelf, due to them being books.

**Additional context**
Similar to issue #369 I supose?

**Picture:**
![Bookshelf](https://user-images.githubusercontent.com/1740156/126885526-68c0f625-40bd-4a23-b27b-d5d7f5d25b3f.png)

**Comment by oly2o6** [comment]
this unfortunately is something we cannot fix on our end
