### ISSUE TITLE
Datapack Issue Preventing Launching 1.0.3 Worlds SP and on Server

### ISSUE THREAD

**Issue by Slark553** [AllTheMods/atm6-sky#51]
**Describe the bug**
Server start fails, and single player worlds both pre-1.0.3 and created in 1.0.3 will not launch, citing an issue with the datapacks. On the server, I am seeing 
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Missing required tags: minecraft:fluid:minecraft:water
before the server stops and crashes.

**To Reproduce**
1. Launch an existing world in 1.0.3 singleplayer
2. -or- Launch a new world in 1.0.3 singleplayer
3. -or- launch a server running 1.0.3 using the supplied startserver.bat file. 

**Expected behavior**
Expected world to launch as in previous updates.

**Comment by Xplodin** [comment]
Any workaround to this?

**Comment by thevortex** [comment]
can i see a full log? pastebin or gist?

**Comment by Slark553** [comment]
> can i see a full log? pastebin or gist?

[79cabdd11f0aea86c1d9e86910aeaa40-892f40540c13ac9408e8f93ea88e9e0e2df343d1.zip](https://github.com/AllTheMods/atm6-sky/files/6176774/79cabdd11f0aea86c1d9e86910aeaa40-892f40540c13ac9408e8f93ea88e9e0e2df343d1.zip)

**Comment by oly2o6** [comment]
new version coming out shortly
