### ISSUE TITLE
Some of Storage Drawer's upgrade don't work.

### ISSUE THREAD

**Issue by joelou1** [AllTheMods/atm6-sky#510]
**Describe the bug**
Drawers with the Void void upgrade won't accept any more items if it's filled and therefore, won't void "Extras". Drawers with the Conversion upgrade won't accept blocks from other mods despite them being the same thing.

**To Reproduce**
1. Build and place Drawers with Void/Conversion Upgrade.
2. Fill the drawer with desired items. (EG; A metal from AllTheOre)
3. For the Void Drawer, try adding more block manually or automatically from pipes, etc.
4. For conversion drawers, try adding the same block/item but from another mod (EG: A metal from Immersive engineering)
5. Notice that none of the blocks are taken by the Drawers. Neither converted or Voided.

**Expected behavior**
Void upgraded drawers should accept excess of items and successfully void the extra.
Conversion upgraded drawers should accept all the blocks that are of the same nature and type. (EG: AllTheOre metal in a drawers should accept metals from their original mods if they have a counterpart.)

**Screenshots**

Void Upgrade:

![BarreltoDrawer](https://user-images.githubusercontent.com/1740156/126886086-a1ca8143-7945-4e3f-93a3-78e66ca9abb1.png)
![BarreltoDrawer2](https://user-images.githubusercontent.com/1740156/126886087-122b6b44-cd6c-4284-a44e-c89241fa06a2.png)
![VoidDrawer](https://user-images.githubusercontent.com/1740156/126886089-dd270300-7d92-48bb-a7ae-6f471dcd16bd.png)

Conversion Upgrade:

![ConversionDrawer](https://user-images.githubusercontent.com/1740156/126886147-68494079-5459-4b70-b65d-43e1bc0acf14.png)
![ConversionDrawer2](https://user-images.githubusercontent.com/1740156/126886152-7d0540b8-4c8e-4c56-aac9-51aa455b28ac.png)
![ConversionDrawer3](https://user-images.githubusercontent.com/1740156/126886153-5d0fd199-a64a-49c1-a06a-37470dcff730.png)

**Additional context**
Regarding other mods Metals, they can easily be obtained from pourring into casts and blocks using Tinker's Smeltry. Seeing how most of the blocks are replaced in the JEI, this could also be a bug.  See #511 for more info.

**Comment by MasterOfBob777** [comment]
Regarding the conversion upgrade, [it's a widely known issue](https://github.com/jaquadro/StorageDrawers/issues?q=is%3Aissue+is%3Aopen+conversion), and hasn't been fixed for a while.

**Comment by oly2o6** [comment]
![image](https://user-images.githubusercontent.com/29486368/130316991-ad859b41-16a8-4c08-b08e-20f48ba62627.png)
clearing out old issues but only one i could reproduce was the conversion upgrade, everything else works fine so im closing
