### ISSUE TITLE
Cannot deserialize unknown ingredient type: silentgear:exclusion

### ISSUE THREAD

**Issue by AugustoAmaral** [AllTheMods/atm6-sky#514]
**Describe the bug**
Not being able to connect to the server after update.
Same issues [here](https://github.com/SilentChaos512/Silent-Gear/issues/410)

**To Reproduce**
Just run the server latest stable version

**Comment by AugustoAmaral** [comment]
Seems that I'm having some version missmatch between server and client. Also install inscript is not working.
I'll downgrade the server version and wait til next update.

**Comment by Tfreak586** [comment]
Got the same problem

**Comment by JRCLARK25** [comment]
Same issue.
Client shows silent-gear-1.16.5-2.6.30
Server shows silent-gear-1.16.5-2.6.26

**Comment by Nicon4454** [comment]
if it is just the file mismatch copy the file silent-gear-1.16.5-2.6.30 from the client to the server and dont forget to remove silent-gear-1.16.5-2.6.26 from the server.

**Comment by Pdiddy973** [comment]
The server files had issues, I have fixed them now. Should be able to download the new server files and work fine.
