### ISSUE TITLE
No more quest and impossible to complete quests anymore since update !

### ISSUE THREAD

**Issue by dhebert-pro** [AllTheMods/atm6-sky#517]
**Describe the bug**
Update from 1.1.6 to 1.1.7 and I have no more quest and cannot complete even the first one...

**To Reproduce**
1. Open the game
2. Open quest
3. No more quest...
4. Complete quest
5. Quest not completed...

**Expected behavior**
To have my quest like before....

**Screenshots**

**Additional context**

**Comment by jermacalocas** [comment]
im having the same issue, assumed it was a failure to update from 1.1.6 on ftbquests. when i tried to find out how to import from 1.1.6 to 1.1.7 i cant find anything and trying to go through them to manually catch up with forced completion im not getting any rewards on that and cant complete without going into editing mode.

**Comment by thom57696** [comment]
same issue before the update i complete lot of quest but  after update all my quest is lock .

**Comment by radiomike** [comment]
With the update of ftbquests, the file format for quests updated. This means that you need to delete the contents of `<world>/ftbquests` to re-enable quest completions.

**Comment by thom57696** [comment]
thanks
