### ISSUE TITLE
Errors in currently selected datapacks prevented the world from loading. 

### ISSUE THREAD

**Issue by ThatCSquared** [AllTheMods/atm6-sky#52]
**Describe the bug**
After updating the pack to 1.0.3 when I try to load a world, it fails.

Attached is the in-game screen that appears and a text file of what the game output reads.

![ATM6_1](https://user-images.githubusercontent.com/81059882/111891231-6fa86d80-89bf-11eb-916a-2d99139a31b4.PNG)
[ATM6Logs.txt](https://github.com/AllTheMods/atm6-sky/files/6176694/ATM6Logs.txt)

**Comment by oly2o6** [comment]
1.0.3b coming out shortly to fix this
