### ISSUE TITLE
Extra Storage Creative Crafter crashes server when adding patterns for Botania runes

### ISSUE THREAD

**Issue by greyhatter** [AllTheMods/atm6-sky#520]
#Describe the bug:
    Adding RS Patterns for Botania Runes to an Extra Storage Creative Crafter causes server crash. 

#To Reproduce
    Create a pattern for any rune in Botania or Mythic Botany
    Place said pattern into the creative crafter from Extra Storage
    Server Crashes

#Crash Log:
    https://pastebin.com/AW5BiQCi

#Additional context
    Once the server comes back up, the patterns are present in the crafter and function as expected.
    Default Refined Storage crafters don't experience this bug.
    Does not occur with the iron crafter from the Extra Storage mod
    Possibly related to [Issue 495](https://github.com/AllTheMods/atm6-sky/issues/495), though the extra nbt tags mentioned there don't appear here.

**Comment by starforcraft** [comment]
Does this also happen to the other Crafters?

**Comment by starforcraft** [comment]
And you have an old Version of Creative Crafter mod (Creative Crafter is an seperate mod) could you try newest?
