### ISSUE TITLE
Mekanism Creative Energy Cube

### ISSUE THREAD

**Issue by JRCLARK25** [AllTheMods/atm6-sky#524]
The craftable Mek Creative Energy Cube doesnt work.
First thought it was "unlimited" energy like it is in creative mode. Not working that method
Second, thought it was just an infinite storage block. But it doesnt store power. Just consumes and never updates. And doesnt allow pass-thru

**Expected behavior**
Block same as  creative mode. Unlimited power. 

**Other Thought** 
Seems pretty cheap for what it is.

**Comment by radiomike** [comment]
There's 2 versions of the creative energy cube. The first, "empty" one, acts as an energy sink until you fill it. Double check jei, but you'll probably need an atm star and over 2 billion FE.

**Comment by JRCLARK25** [comment]
Yes see that now... *facepalm* 
Thank you for quick reply
