### ISSUE TITLE
full 1.1.7. Mods not working.

### ISSUE THREAD

**Issue by DummyBozo** [AllTheMods/atm6-sky#528]
forge 36.1.66 Minecraft 1.16.5 using cursed forge.
Bigger mods in this mod pack along with easy villagers do not work correctly
bigger mods reactor does now work with any coolant that is listed to work with the mod. I did go into a creative world and try multiple coolants but all of them have resulted in the same way and not cooling the reactor at all. I follow TheChosenArchitect on youtube for all my Minecraft lets plays and its weird to see this happen

Easy villagers mod in this game also does not work when I want to pick up villagers it does not let me. This causes issues when I want to place them into their respected easy villager's block such as a breeder and such. 

I tried redownloading the whole mod pack, using a previous version, and even deleting and restarting each mod into the mod folder individually. nothing has worked. I played in creative mode with the villagers seeing if it's a different type of villager but nothing worked. if you can help me I would appreciate it so much. also a great pack! I love it.

**Comment by RogueLogix** [comment]
Bigger Reactors is working fine, I changed the default config in such a way that the temperatures are significantly higher with the same design, that is on purpose.
