### ISSUE TITLE
Clay Bucket not working on the barrels (oak barrel is the one im using)

### ISSUE THREAD

**Issue by RyuuGaming22** [AllTheMods/atm6-sky#529]
I have a clay bucket filled with water. I attempted to put water in the oak barrel and nothing happened. it worked with the iron bucket filled with water. I don't think this is an actual feature so I assume it's a bug. it isn't game breaking of course but it can be misleading for some when attempting to get clay,

**Comment by oly2o6** [comment]
duplicate issue, but we also cannot fix this, its on the mod devs
