### ISSUE TITLE
After the 1.0.3 update

### ISSUE THREAD

**Issue by wibabe** [AllTheMods/atm6-sky#53]
![111891231-6fa86d80-89bf-11eb-916a-2d99139a31b4](https://user-images.githubusercontent.com/71390305/111891736-09930900-8a06-11eb-8d4f-1ec02f18ff22.png)
Waiting for a fix :)

**Comment by OmegaAlpha83** [comment]
same i can load in gives same message

**Comment by chadw** [comment]
issue is super multi drills mod with old save.

[22:36:00] [Render thread/WARN]: Failed to load datapacks, can't proceed with server load
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Tag supermultidrills:drill_batteries used before it was bound

If you remove that mod and restart it should load without issue

**Comment by oly2o6** [comment]
going to release a 1.0.3b with supermultidrills removed
