### ISSUE TITLE
astral sorcery evershifting fountain broke gravity

### ISSUE THREAD

**Issue by qussaif100** [AllTheMods/atm6-sky#530]
hi, im not sure if this is a bug from astral sorcery or this modpack but i just need a way to fix it,so what happened was i made the evershifting fountain and used a fysallidic prime with it, but then i broke it but something weird started to happen and now all the mobs gravity are broken and most of them just fall in the void, i tried to search up the proplem but i didnt see anything about it.

**Comment by oly2o6** [comment]
would assume an astral bug, should be reported there
