### ISSUE TITLE
Ice and fire Crash dragon breath

### ISSUE THREAD

**Issue by nenec0** [AllTheMods/atm6-sky#532]
as soon as I arrive to kill the ice dragon he lets out his breath as soon as it happens my game just closes, it doesn't crash nothing happens nothing just closes

error that appears when mod crash : https://paste.ee/p/88HVl

platform: MultiMc 
Version: ATM6sky Skyblock-1.1.7

**Comment by notFalkon** [comment]
Downgrading citadel to 1.7.1 will fix this

**Comment by nenec0** [comment]
> Downgrading citadel to 1.7.1 will fix this

1.7.1? doesn't have this version

**Comment by notFalkon** [comment]
I said citadel, the _mod_. Not atm6s, the mod_pack_.
https://www.curseforge.com/minecraft/mc-mods/citadel/files/3346836
