### ISSUE TITLE
Magma Bee Spawn Egg isn't craftable

### ISSUE THREAD

**Issue by voidei** [AllTheMods/atm6-sky#533]
**Describe the bug**
The Magma Bee Spawn Egg recipe isn't viewable in JEI, and when you try crafting it with the pre-determined recipe it doesn't do anything.

**To Reproduce**
1. Click on the Magma Bee Spawn Egg in JEI
2. See that there's no recipe

**Expected behavior**
Well I expected to be able to craft it?

**Screenshots**
![2021-08-15 17_50_08-Greenshot](https://user-images.githubusercontent.com/8062954/129471222-86072c4a-7060-4893-9f21-99d2e4340fae.png)

**Additional context**
None

**Comment by ladylexxie** [comment]
Fixed in #534
