### ISSUE TITLE
Magma Bee Spawn Egg Uncraftable?

### ISSUE THREAD

**Issue by Gdschaf** [AllTheMods/atm6-sky#535]
It seems that something happened with the Magma Bee spawn egg recipe. I tried with the old recipe (4x magma cream bucket, 4x magma bucket, dragon scale) and it doesn't work on 1.1.7. If there's a different way to obtain a Magma Bee or if the recipe is supposed to work, that'd be great to know.

**Comment by Pdiddy973** [comment]
fixed in https://github.com/AllTheMods/atm6-sky/pull/534
