### ISSUE TITLE
Dragon Scales from Mystical Agradditions not dropping

### ISSUE THREAD

**Issue by CobaltDragon666** [AllTheMods/atm6-sky#536]
I need some dragon scales from Mystical Agradditions to make bee eggs, seeds, etc. It dropped only on the first death of the ender dragon but then it doesn't drop again when respawned. Tried with and without the dragon egg siting on it's default spot.
Is it normal ?

Playing on version 1.1.7 of the pack

**Comment by rexionman** [comment]
hello I checked myself they fall well even after having beaten several times they do not fall all the same place you have to look around the pillars and in the center
