### ISSUE TITLE
Game keeps Crashing while starting

### ISSUE THREAD

**Issue by WERTBON1789** [AllTheMods/atm6-sky#538]
I install the pack once then play on a server without any issue, but when I quit the game or it crashes and I try to restart it, it just crashes everytime. Then I reinstall it, it works again...... for one time and crashes again.
I actually had a autoclicker click the start button so when it crashes it try's to start it again runnig for an hour without success
so I would guess there breakes something in the Instance or in the Launcher so it doesn't start anymore.

I'm on Arch Linux using GDLauncher with the automatic Java install, because MultiMC didn't work once for some reason.

Sadly GDLauncher only gives me, I think these are more like Java log files, or I just cant find the others.
[hs_err_pid27908.log](https://github.com/AllTheMods/atm6-sky/files/7002576/hs_err_pid27908.log)

**Comment by radiomike** [comment]
So, those kind of error files usually indicate an issue with java rather than minecraft itself.
my recommendation is to try getting gdlauncher to use the os version of java. If that doesn't work, try going back to multimc. Make sure you are using the git version from aur and try again from there.

**Comment by WERTBON1789** [comment]
I actually used the git version before because of a recommendation. Changing to the "real" java version (openjdk 8 latest)started but now my title screen seems a bit messed up, and now it also doesn't start again. maybe the change to another version messed something up in the configs?
maybe multimc-bin can make some magic stuff.
![grafik](https://user-images.githubusercontent.com/50809022/129808422-4f108197-f147-4349-a1a7-4e3a635d58ec.png)

**Comment by WERTBON1789** [comment]
I copied the folders in the overrides folder in the zip archive into the instance and it started again fixed the broken title screen so thats no issue
