### ISSUE TITLE
Modpack Crash

### ISSUE THREAD

**Issue by abwuge** [AllTheMods/atm6-sky#539]
After playing near 30  minutes, my game always stuck.
And there is 
"[Render thread/FATAL] [minecraft/ThreadTaskExecutor]: Error executing task on Client
java.lang.NullPointerException: null" 
ing the log occupied the vast majority.
The MultiMc asked me to  pepair my mod.
So what can I do for it?

I am a Chinese and my English is terrible. Please forgive my mistake.

**Comment by oly2o6** [comment]
Can you provide the crash log please?

**Comment by oly2o6** [comment]
closing this as it has been over 2 weeks with no response
