### ISSUE TITLE
Ancient spores work on not just dirt

### ISSUE THREAD

**Issue by FOURSPARTA** [AllTheMods/atm6-sky#54]
clicking blocks with Ancient spores will turn it to mycelium not just dirt. have turned cobble and a wooden barrel to mycelium aswell 

**To Reproduce**
1. get Ancient spore seeds
2. Click on a block (that is not dirt)
3. get mycelium 

**Expected behavior**
Only to work on dirt

**Comment by oly2o6** [comment]
this would need to be reported to the devs instead of us
