### ISSUE TITLE
Dock from /dank/null under a water-pumping pedestal crashes 

### ISSUE THREAD

**Issue by Jdawg215** [AllTheMods/atm6-sky#541]
As the title says, placing an empty fluid Dock under a pedestal with fluid pump upgrade crashes my game. Foolishly, I sought to use Amulet to world-edit the Dock out, which worked...until I loaded in, and realized Amulet emptied out ALL of my modded containers (drawers and sieves) within the same chunk the Dock was in.

**Comment by oly2o6** [comment]
Mod related issue, unsure which side it is on, can you provide a crash log? Will be easier for the mod developers to figure out what the issue is and get it fixed alot quicker

**Comment by Jdawg215** [comment]
[crash-2021-08-20_20.39.13-server.txt](https://github.com/AllTheMods/atm6-sky/files/7024875/crash-2021-08-20_20.39.13-server.txt)
