### ISSUE TITLE
Easy villager config is not working 

### ISSUE THREAD

**Issue by RayHell** [AllTheMods/atm6-sky#542]
ATM6 To the Sky 1.1.7 server

Easy villager config is set to " sneak_pick_up = false "  but it's still override the shift right-click rendering mob imprisonment tool and mob swab tool unusable.

**Expected behavior**
When config is set to sneak_pick_up = false, it should not pick up a villager when you shift right-click

**Comment by oly2o6** [comment]
If the config is not working, it should be reported to the easy villager github instead, as this is an issue we have (or thought we have) long ago fixed
