### ISSUE TITLE
wither skull recipe

### ISSUE THREAD

**Issue by DustyThaGoat** [AllTheMods/atm6-sky#546]
The crafting recipe for withe skulls seems to be broken. using 9 wither skull fragments you should be able to make a skull but it doesnt work.
aperently the recipe works in my other world but not in my lets play world

**Comment by DustyThaGoat** [comment]
aperently the recipe works in my other world but not in my lets play world

**Comment by oly2o6** [comment]
try a fresh install of the pack, and transfer your world over to that, there would appear to be some issues with the recipe itself not syncing in your lets play
