### ISSUE TITLE
Teleport Pad Problem

### ISSUE THREAD

**Issue by XiNaru** [AllTheMods/atm6-sky#547]
Hey guys, have a problem.

The teleportpad is not activated in the Allthemodium mod in the Sky Modpack. In other words, if I sneak + right-click with my lerer hand, nothing happens. Is there any way to activate the pad?
I can't find a config for it.

**Comment by adehcby** [comment]
You need to go to the Nether to use it.

**Comment by oly2o6** [comment]
mining dim is disabled in sky, so the only way it works is the nether to go to the other dimension
