### ISSUE TITLE
Screwed up End Frame, Salvagable? 

### ISSUE THREAD

**Issue by Jdawg215** [AllTheMods/atm6-sky#548]
Kinda double-clicked when placing my end frame, but because i cant break that one block, my frame doesnt want to work (Or I'm stupid and am supposed to do it elsewhere.) Is there a way to save this or do i have to redo it from scratch?
Edit: I now realize you get to the End via End Cake, so there's no loss, but still curious if there's a remedy to this
![image](https://user-images.githubusercontent.com/21210898/130552771-c5b7308f-cbdb-456e-aeaa-e3ff15cbde9c.png)

**Comment by bloodscon** [comment]
If your in a single player world press esc to bring up option there is an option to "open to lan" click on that and select creative delete block log out and restart your world as normal
