### ISSUE TITLE
INFINITE XP!

### ISSUE THREAD

**Issue by HKQ889** [AllTheMods/atm6-sky#552]
The (XP Drain Singularity Tank) from (Mob Grinding Utils) gives you more XP when you stand on top of it with an open (XP Tap) attached on the side and you have at least 5 levels + just found out that accelerate them with a (time in a bottle) you get MORE XP!!!

**Comment by Sirttas** [comment]
Don't make titles like this...

**Comment by HKQ889** [comment]
Sorry
