### ISSUE TITLE
Recipe Error - Kubejs Compressium & Allthecompressed

### ISSUE THREAD

**Issue by ifficles** [AllTheMods/atm6-sky#553]
Hello,

  Migrated my saves over to the new version of "to the sky today."  And, found several recipe conflicts with Allthecompacted & Compressium, which affects iron, gold, & emerald 1X compressed blocks.  What I'm trying to craft is the Gold tier Centrifuge which requires compressed the 1X gold blocks.  The output of the recipe has changed as follows;

![old_recipe](https://user-images.githubusercontent.com/961490/131228046-0942c6e9-7dc2-4b1f-a142-452e772f23cd.png)

![recipe change](https://user-images.githubusercontent.com/961490/131228048-4d81762e-f3cc-46b3-aefc-1517114e8931.png)

I do understand that I can change the output manually.  However, when using an auto-craft with Refined storage, what is being outputted is being overridden by another mod.

**Comment by ifficles** [comment]
disabling the Allthecompressed mod fixed the issue.

**Comment by mrskiw** [comment]
I got an error with this mod too. The gravel is automatically compressed into blocks from Allthecompressed, not ExCompressum. It can be changed manually, but it is automatically created incorrectly.

**Comment by ifficles** [comment]
Thanks for fixing the above issue.  Have a pleasant morning, day, evening.
