### ISSUE TITLE
AllTheCompressed

### ISSUE THREAD

**Issue by mrskiw** [AllTheMods/atm6-sky#554]
can you make "AllTheCompressed" the next compression step after "Compressium" for conflicting recipes?
It conflicts with two mods at once, some of the blocks are similar and it is not clear why there are two types of one and the same, some options, are in one mode, and some in the other.
And also in "AllTheCompressed" there is an error in the recipes for "imersiveengineering / crusher: cobblestone, gravel"

**Comment by oly2o6** [comment]
fixed in next version, but you can also update allthecompressed to the latest version for yourself
