### ISSUE TITLE
Ice and fire Dragons Server crashing

### ISSUE THREAD

**Issue by Rat-bags** [AllTheMods/atm6-sky#557]
Hi the ICE dragon is still crashing servers when it try's to freeze player or when they die and go back for grave and start attacking them, Only seems to be the ice one that we have found so far 

Mod Ver 1.1.8 i know 1.1.8 had fixes for dragon breath but still crashes with ICE  

1. go to other
2. find ice dragon
3. try kill and die
4. get grave and carry on 

**Expected behavior**
The server Not to crash 

crash log if needed
https://pastebin.com/mpcxvdYY

**Comment by Rat-bags** [comment]
Want to add we are on the new 1.1.8 so i know it say fixed but its not on the ice one

**Comment by oly2o6** [comment]
the ATM team have never been able to reproduce the issues with the dragon crashes but i would recommend reporting this to the mod author

**Comment by Tomu1572** [comment]
I am currently having the same issue and the server keep crashing everytime a player that is fighting an ice dragon logged on.

**Comment by oly2o6** [comment]
going to keep this open as we have multiple reports for ice and fire and also people saying it does not happen for them, so there is something the crashers/none crashers have in common, just need to figure out what it is before it can be fixed and closed

**Comment by Skinklizzard** [comment]
The latest version of the pack (1.1.8) is still using citadel and iceandfire versions of 1.8.0
the mod author has updated to 1.8.1
one of the fixes includes the NullPointerException from getEntity() in EntityProperties
which is what was thrown when the frost dragon used its freezing breath AOE on our server
