### ISSUE TITLE
cyclic, mob grinding tools, and industrial foregoing. 

### ISSUE THREAD

**Issue by soultare** [AllTheMods/atm6-sky#558]
Any chance for alternate recipe's for mob tools way of handling liquid xp? as it currently sits we can't use it in the cyclic tools for bottle of enchanting, and tools from industrial can't use it either for example mob duplicator's cant use the experience to make more mobs.
![image](https://user-images.githubusercontent.com/34783239/131456698-55bfdcde-49b1-43d3-855e-d53b57a748bd.png)

**Comment by oly2o6** [comment]
i believe you can use glass bottles to turn the liquid xp into bottles of enchanting, which then allows it to be used for cyclic and other mods
