### ISSUE TITLE
cant download modpack or update it

### ISSUE THREAD

**Issue by OmegaAlpha83** [AllTheMods/atm6-sky#56]
after removing multi drills for data pack issues I tried to update new profile said could not update so then I tried to delete it and reinstall it and now the mod pack is uninstall able here's a screenshot of what it tells me when I try to install the mod pack something is really messed up here

![image](https://user-images.githubusercontent.com/81062066/111893563-f407ea00-89d9-11eb-99a1-fed9f14a8dba.png)

**Comment by ariosos** [comment]
This happened to me at first, but I closed CurseForge, then opened it again and clicked on the ATM6 To The Skys image, then selected the arrow to update to the new version. It worked for me the 2nd time.

**Comment by WhitePhant0m** [comment]
Nothing to do with the pack
