### ISSUE TITLE
Issue with AllTheCompressed

### ISSUE THREAD

**Issue by RayHell** [AllTheMods/atm6-sky#562]
**Describe the bug**
When you place a piece of cobble/gravel/sand in the compacting drawer it's automatically converting to AllTheCompressed instead of compressium which is incompatible with the auto compress hammer and auto compress sieve.

**To Reproduce**
 Place a piece of cobble/gravel/sand in the compacting drawer

**Expected behavior**
Auto compress hammer / auto compress sieve should accept AllTheCompressed blocks

**Screenshots**
![2021-09-02](https://user-images.githubusercontent.com/9449692/131787250-fbe8359b-cc0c-4cea-b93d-b8b26677cf7c.jpeg)

**Comment by notFalkon** [comment]
Update allthecompressed

**Comment by oly2o6** [comment]
yeah will also be fixed in the next version of the pack but falkon is right, updated ATC is the fix
