### ISSUE TITLE
Can't change worlds/can't join/tags/datapack issue

### ISSUE THREAD

**Issue by Kahadi** [AllTheMods/atm6-sky#564]
**Describe the bug**
Any time I exit a world and try opening a different one, be it starting a new world or swapping to an existing one (I like to keep a creative world for testing setups), the game says "Errors in the currently selected datapacks prevented the world from loading. You can either try to load it with only the vanilla data pack ("Safe Mode"), or go back to the title screen and fix it manually." Underneath are two buttons, "Safe Mode" and Back to Title Screen". When I select Safe Mode, it freezes for a bit, then just remains where it is. Going back to the Title Screen doesn't fix the issue either. A new world won't even show in the menu, but trying to use the title of that failed world will result in a (1) added at the end, as though the world is there. The only fix I've been able to find is quitting the game and letting it all load back up again.

**To Reproduce**
1. Start the pack
2. Load a world
3. Exit the world
4. Open or create a different world
5. See error.

**Expected behavior**
A new world being opened or created.

**Screenshots**
![image](https://user-images.githubusercontent.com/82643849/132090415-764464f1-f997-4d6c-8e13-a62ca0706039.png)

**Comment by justinkillen** [comment]
I saw this error too, and also the one described in https://github.com/AllTheMods/atm6-sky/issues/567.  I updated cyclic from Cyclic-1.16.5-1.3.6 to Cyclic-1.16.5-1.3.8 and that seems to fix the problem.

**Comment by oly2o6** [comment]
leaving this thread open and closing the others, updating cyclic did not fix your issue? Make sure JustEnoughResources is removed from the server if you did not use the 1.8.0-FIXED.jar server files on curseforge

**Comment by justinkillen** [comment]
Updating cyclic did fix my issue.  Not sure about the OP.

**Comment by justinkillen** [comment]
I'm using the CurseForge app.  I'm not sure how it knows which file to download from curseforge.com.

**Comment by bloodwrath23** [comment]
Hello, I'm having the same type of problem with the error message as well. happened when I updated from 1.1.6 to 1.1.8. not sure how to proceed to begin fixing this issue. Using CurseForge app as well. looked at the mod list and it does look like some can be updated but cyclic was not one of them that showed needing to be updated. also on resource packs the "packmod" is showing to be incompatible with current version of minecraft. any suggestions? thank you.

**Comment by Kahadi** [comment]
Update Cyclic separately, on your own. Go to the mod's download page, download Cyclic 1.6.5-1.3.8, go to your instance folder, under mods (there's a link through CurseForge that takes you there). Copy the new Cyclic to it, then delete the old one that was already there. I don't know why CurseForge won't do it for you, but its probably because its not been updated in the pack yet.

**Comment by justinkillen** [comment]
For those less technically inclined:

open your browser to: https://www.curseforge.com/minecraft/mc-mods/cyclic/files/3448837
under "File Details", click the download button

open the CurseForge app
right-click on the pack, and choose "Open Folder"
this should open a file browser, e.g. windows file explorer or macos finder
from that folder, double-click the "mods" folder
find the file "cyclic-1.16.5-1.3.6.jar" - right-click it and choose "delete"
in your downloads folder, find the file "cyclic-1.16.5-1.3.8.jar" that you downloaded earlier, and copy it into this mods folder

Load the pack via CurseForge, and it should be working
