### ISSUE TITLE
Diamond chest with compacting 2x2 pedestal on top - sorting causes single player to lag.

### ISSUE THREAD

**Issue by bsjohnson20** [AllTheMods/atm6-sky#566]
**Describe the bug**
A clear and concise description of what the bug is:
Pedestal with 2x2 compacting upgrade on diamond chest with half diamond chest of pieces, if you sort the items on singleplayer, chest stays open and theoneprobe reports "waiting for server"

**To Reproduce**
Steps to reproduce the behaviour:
Have diamond chest with lots of exnihilio resource pieces with pedestal on top with compacting 2x2 upgrade
2. midclick inside chest to sort items
3. chest stays open, and singleplayer lags. 
**Expected behaviour**
Items to be sorted instantly, without causing server lag or console errors.
**Screenshots**
![image](https://user-images.githubusercontent.com/44623479/132127226-779c867a-2557-4898-a65a-14ff90a3ac8f.png)
https://pastebin.com/Z0ULSK3H

**Additional context**
ATM6 - to the sky, version 1.1.8, doesn't matter if it's enchanted or not
chest - doesn't matter if sorted or not 
![image](https://user-images.githubusercontent.com/44623479/132127284-c60c5909-f0e3-4cc1-8106-a3fa3b2e4e69.png)
Running on GDlauncher- not sure if that changes anything.

**Comment by oly2o6** [comment]
It is just the way they are coded (due to it having so many slots and checking said slots to compact), i would recommend have the pedestal on a smaller chest, and then use a pipe to pull the compacted items out of it into the diamond

**Comment by bsjohnson20** [comment]
Used a wooden chest too. Still did it but a shorter lag time.

**Comment by voidei** [comment]
Shorter lag time is due to it not having to check as many slots, it lags because you're trying to sort an inventory while something checking each slot and crafting using items in said slot

**Comment by oly2o6** [comment]
ohh right i completely missed that part of the message, your answer is just do not middle click in the chest that has a pedestal ontop of it, nothing more i can say i guess, long answer do what i said above, and middle click that chest instead as there will not be a pedestal on it, this is still not a bug
