### ISSUE TITLE
Unknown Server Crash

### ISSUE THREAD

**Issue by dragonlord026** [AllTheMods/atm6-sky#569]
So I've been playing all the mods 6 to the sky. Basically when I came back from afking I couldn't log in. I keep getting kicked from the server saying its down. I am running it on a BisectHosting server. looked at the console and its restarting it self. looked at the logs. there was a new crash report every 5 minutes. I restored the server from a backup. worked fine could play no problem other then some lag of course. AFK a few hours while I went to work and same issue cant tell exactly what's causing the problem idk if its the same thing that's lagging the game when I can play unsure. 

[crash-2021-09-06_00.55.08-server.txt](https://github.com/AllTheMods/atm6-sky/files/7117766/crash-2021-09-06_00.55.08-server.txt)

**Comment by oly2o6** [comment]
change max-tick-time=-1 in the server.properties
