### ISSUE TITLE
Dimensions not saving world data

### ISSUE THREAD

**Issue by Jimbopanda** [AllTheMods/atm6-sky#57]
**Describe the bug**
Entering any dimension will reset any blocks placed/mined when you re-enter. 
E.g. After updating to 1.0.3c, I entered the Other and mined some ore. I left to smelt it, re-entered the other and the ore had "respawned", allowing me to mine it again and double it. 
Works for any block in any dimension placed there before before updating. 
If you place a block in a dimension, leave and re-enter, that block will be deleted. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Launch version 1.0.3c
2. Enter any dimension and break any block
3. Leave and re-enter the same dimension
4. The broken blocks have reappeared

**Expected behaviour**
Blocks should only be abled to be broken once and world data should be saved

**Comment by WhitePhant0m** [comment]
We downgraded AE2 to an older version in 1.0.4b to fix this issue. Please update.
