### ISSUE TITLE
Ice and Fire Ice Dragon Egg disappears during hatching process.

### ISSUE THREAD

**Issue by Wolfsokim** [AllTheMods/atm6-sky#570]
**Describe the bug**
When attempting to hatch an Ice Dragon, the egg starts shaking like it should, however 2-5 minutes in it just disappears. I stand near it so it doesn't de-spawn when it hatches.
I'm on the official ATM6:ToTheSky server if that matters.

**Expected behavior**
Egg is placed in water, water freezes, egg should hatch, producing a dragon.

**Comment by oly2o6** [comment]
I just managed to spawn a dragon? not sure how or why yours is despawning but i also do not know much about ice and fire > closing (reopen if anyone else can reproduce this, on a different server/ singleplayer
