### ISSUE TITLE
There is no Osmium Ore Piece.

### ISSUE THREAD

**Issue by TheLexCraft** [AllTheMods/atm6-sky#571]
**Describe the bug**
**There is no way to become osmium ore piece or osmium ore chunk. There is no Item that named like this.**

**Expected behavior**
I cant become Osmium. I can becom it only from Osmium Bees. 
**Screenshots**
![image](https://user-images.githubusercontent.com/77213356/132521798-64a0b378-8c38-4766-9edb-dfdbea56058b.png)

I have my Minecraft and The Server restarted.

**Comment by lilrichy** [comment]
You should be able to get the Osmium Ore Piece from using a Sieve with a Diamond, Emerald, or Netherite Mesh.
I'm using Current version of Mod Pack - 1.1.8 
![image](https://user-images.githubusercontent.com/8129775/133311849-486883c2-a901-489c-84a3-9223d1be2141.png)

**Comment by uberfuzzy** [comment]
Looking at OPs picture, the two missing are coming from KubeJS, so its possible it wasnt loaded?

**Comment by oly2o6** [comment]
potentially something wrong with your instance (some of the kube files failed to download potentially, not sure) but im also looking right at osmium pieces in jei >closing
