### ISSUE TITLE
World Crashes

### ISSUE THREAD

**Issue by ConnorRedwood** [AllTheMods/atm6-sky#572]
The game loads but when I try to open my world it won't load. I have allotted 8G for this pack.
[crash-2021-09-08_16.21.35-server.txt](https://github.com/AllTheMods/atm6-sky/files/7132076/crash-2021-09-08_16.21.35-server.txt)

**Comment by lilrichy** [comment]
Try going into your world folder and then into serverconfig folder and look for file called buildinggadgets-server.toml delete that file and try to start game again and see if it starts or if the crash log changes the file it is having a problem with.

"net.minecraftforge.fml.config.ConfigFileTypeHandler$ConfigLoadingException: Failed loading config file buildinggadgets-server.toml"

**Comment by oly2o6** [comment]
no response from author in 3 weeks so assuming it is fixed > closing (reopen if it does not work still connor)
