### ISSUE TITLE
Quests not Completing

### ISSUE THREAD

**Issue by GwennyDaCatgirl** [AllTheMods/atm6-sky#574]
Whenever I get all of the required items to complete a quest it will usually register that I have said items but the quest itself won't complete even if I completed all of the quests before it completely cutting me off from large portions of the quest trees. The newest instance was the "The Inferior Essence" quest which has completely cut me off form completing any of the quests involving the seeds.

**Comment by oly2o6** [comment]
just tried to reproduce this and i could not, extra information required, potentially a screenshot of your inventory and then a screenshot of the quest you are trying to complete with said items in the inventory

**Comment by EROZCRAFT** [comment]
Not Work
![image](https://user-images.githubusercontent.com/92201114/136646948-3671d451-5ede-45c4-84fd-73df0c17b8c0.png)

Prudentium essence complete, and dont detected.

**Comment by norile** [comment]
Since this is marked as completed what was the solution?
