### ISSUE TITLE
Ice dragon crashes server

### ISSUE THREAD

**Issue by Diamantino-Op** [AllTheMods/atm6-sky#576]
**Description**
While fighting an ice dragon, whenever it killed me or when Stage 5 attacked me, the server crashed,

**Steps To Reproduce**
1) Start a server
2) Go to the other dimension and find ice dragons
3) Wait for them to kill you or go to a stage 5 and fight with it.

**Expected behavior**
Dragon should die and dropp scales and and egg.

**Screenshots**
If you need a video, ask and i'll make one and upload on YT.

**Additional context**
I encountered this bag in: atm6-sky.bigcommunitygames.com

**Comment by lilrichy** [comment]
I had same problem Updating the mods Ice and Fire: **Dragons to version 2.1.9** and **Citadel to version 1.8.1** Fixed this.

**Comment by Diamantino-Op** [comment]
Thx, i'll try that
