### ISSUE TITLE
Elytras are quite broken

### ISSUE THREAD

**Issue by chadandersen1** [AllTheMods/atm6-sky#577]
I may be in the minority of people here using an elytra rather than a jetpack, and I realize I should probably switch to a jetpack anyway, and I will eventually, but this still really bugs me.
In other words, this isn't a huge game breaking glitch, and doesn't really need to be fixed, it just ruins the fun of elytras for me personally, and I can't find a fix or bug report anywhere else so I'll report it here.

Just using the elytra allows you to fly infinitely. You will receive infinite small boosts, sometimes in bursts, and can continue flying forever. It happens at random, hinders the player in the case they want to land without taking damage (you're going to land, and it boosts you straight into the ground), and does not seem like intended behavior.

If it is a "feature" added by some mod, I'd like to know what so I can disable it, I'm not sure why it would be enabled by default as it removes most of the usefulness from fireworks, other vanilla mechanics and multi-jump mechanics. I've already searched the keybinds and skimmed through the configs, couldn't find anything myself.

**To Reproduce**
Equip an elytra, back slot or chest, and start using it. It can be the only thing equipped and in your inventory, and enchantments don't affect the behavior. This happens in many Forge modpacks; which is why I think it could be intended; but very prominently in ATM6 and ATM6 to the sky. 

**Expected behavior**
Vanilla elytra behavior

In this clip you can see and hear me gain two elytra boosts, I am only holding W and the only thing equipped is an unenchanted elytra
https://user-images.githubusercontent.com/35705223/133312669-50052f5e-78dc-416c-b968-e4b8a0d4d196.mp4

**Comment by oly2o6** [comment]
going to leave this open as i assume its a mod but i would also like to know what is causing it

**Comment by Grath** [comment]
It's probably the leylines mechanic from Mahou Tsukai, which I noticed in regular ATM6 doing the "random boosts with an elytra" oddity.

**Comment by stepsword** [comment]
yes, mahou leylines give a boost to elytras if you fly in one direction on them. if you're not flying on leylines, its probably something else.

you can turn it off by setting LEY_ELYTRA_LIMITED_TO_FAY_SIGHT = true, in mahoutsukai-server.toml, and then itll only affect players with the fay sight spell on.
