### ISSUE TITLE
Way to obtain Ars Nouveau's Archwood ?

### ISSUE THREAD

**Issue by Nagispace** [AllTheMods/atm6-sky#579]
It seems that archwood doesn't generate and I can't find a way to get it.
Any idea ?

**Comment by sdfox945** [comment]
Can be purchased from the market from the Farming for Blockheads mod.

**Comment by Nagispace** [comment]
> 
> 
> Can be purchased from the market from the Farming for Blockheads mod.

Oh thanks
If you have any other moded skyblock tips I'll gladly take the, I'm not really used to it comapared to a non skyblock version (:
