### ISSUE TITLE
Performance Issues With Apotheosis Spawner in 1.1.8

### ISSUE THREAD

**Issue by TrevorRuppert** [AllTheMods/atm6-sky#580]
Issue: After updating the pack to 1.1.8 The apotheosis spawner (Without Anti-Matter) caused significant amounts of lag and stutter whenever a spawn event would occur. After playing around with and testing a bunch of different scenarios (Including removing the 3 new mods added in the latest update just to rule those out.) I found that the issue is with Citadel 1.8.0. Specifically, Whenever an entity was spawned there was a log entry for every entity spawned about a null pointer exception. After updating the version of citadel to 1.8.1 the issue was resolved. This is the same issue causing many peoples clients to crash when it comes to the ice dragon (Not the same issue that caused crashes in 1.1.7 that was a null pointer exception aswell but specifically for the "Frozen" effect which was fixed in Citadel 1.7.3).

Resolution: Update Citadel from 1.8.0 to 1.8.1

**Comment by oly2o6** [comment]
fixed in dev
