### ISSUE TITLE
Getting very low framerate which makes it barely playable.

### ISSUE THREAD

**Issue by SKY3E** [AllTheMods/atm6-sky#582]
**Describe the bug**
When I load into any world the frame rate drops drastically to between 1-10 fps. Im not sure how to fix this. I know this is related only to atm6-sky because it doesnt happen in any other modpacks. I'm letting the game use all the ram I have in my pc and have lowered all video settings in minecraft.

**Expected behavior**
I was hoping to get at least 30fps even though i should be able to reach 60+

**Screenshots**
Not sure how to add screenshots, sry.

**Additional context**
Graphics card : RX 5700 xt
Cpu : Ryzen 5 2600x
Ram : 16g (Im letting the game use 12g)

**Comment by orbidlo** [comment]
Did you try investigating the source of lag using /spark profiler --timeout 30 or the lag goggles from Observable mod?
Have you tried using the correct java args? `-XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true`
Have you tried installing recommended java 11 version? https://adoptopenjdk.net/?variant=openjdk11&jvmVariant=hotspot

**Comment by SKY3E** [comment]
I just installed Java 111 with your link and have inserted the arguments you wrote into curseforge launcher. Im not sure how to do the first thing you said could help. thanks for the help, and ill keep you updated.

**Comment by SKY3E** [comment]
Didnt change much, still at 2-3 fps.

**Comment by orbidlo** [comment]
Well first point was the most important if it's caused by smething in your base  - you can post your spark log here and we can help look into it for source of bad lag.  But if you create new empty skyblock world and it's giving you same abysmall fps, I can't help, sorry.

**Comment by TrevorRuppert** [comment]
@SKY3E is this in an existing world or a new world? If this is an existing world did it start after the 1.1.8 update (Current Release Version)? If it did do you have any apotheosis spawners in your loaded chunks? If you have apotheosis spawners in your loaded chunks I posted a bug a week ago after the update regarding Apotheosis spawners causing huge amounts of lag to the point my game would crash. The fix is to update the citadel mode to 1.8.1. There is a bug in the ATM6-sky citadel version (1.8.0) regarding null reference pointers to entity tracking. I never was able to test the full extent but it may be worth giving it a shot.

**Comment by oly2o6** [comment]
considering you are using AMD parts i would say set mipmaps to 0, i have a ryzen7 and an rx580 and the game is unpayable for me also unless i do this (i have no idea why, just minecraft) if this does not fix the issue please reply

**Comment by SKY3E** [comment]
Thank you so much changin the Mipmap level worked.

**Comment by AdamBrianBright** [comment]
Just created world. Fast/no-shadows/no-smooth-light: 120 FPS avg. with frequent drops to 20 or even freezes. 
**Pack version**: 1.2.0
**System**: Macbook Pro 16" (2019) i7, 16G, 5500M

As suggested, used Java 11 and decreased mipmaps to 0.
Fresh world load still takes a couple minutes, but FPS now 250 with sometimes drops to 150

Nothing really changed in visuals, or not that I'm aware of. Thanks!  ❤️ 💕 💖
