### ISSUE TITLE
Industrial Foregoing Machine Frames No Crafting Recipe

### ISSUE THREAD

**Issue by TrevorRuppert** [AllTheMods/atm6-sky#584]
**Describe the bug**
after 1.1.8 Update Industrial Foregoing Machine Frames have no crafting recipe after the pity machine frame. It seems as if the Dissolution chamber itself has no uses whatsoever anymore except for pink slime balls 

**To Reproduce**

1. Launch the pack and look at crafting recipes for the industrial foregoing machine frames, or look at the uses for the dissolution chamber

**Expected behavior**
Crafting recipes

**Additional context**
I do not remember the crafting recipe from previous versions so i cannot test if the recipes still work and are just not showing in JEI or if the issue itself exists with the recipes for the dissolution chamber. After some further digging though it does appear that all dissolution chamber recipes except for pink slime balls have been removed.

**Comment by notFalkon** [comment]
This is a known issue. Update industrial foregoing to see the recipes in jei again.

**Comment by oly2o6** [comment]
fixed in dev
