### ISSUE TITLE
Gamecrash

### ISSUE THREAD

**Issue by Matsyatzy** [AllTheMods/atm6-sky#586]
My game crashed for no reason.
[crash-2021-09-25_02.49.27-server.txt](https://github.com/AllTheMods/atm6-sky/files/7228917/crash-2021-09-25_02.49.27-server.txt)

**Comment by b0lshevik** [comment]
Your Java build is ANCIENT. Java 8u51 was released in 2015. Not to mention Java 11 is recommended for 1.16+
