### ISSUE TITLE
Misleading Drawer Controller Slave quest description

### ISSUE THREAD

**Issue by nddragoon** [AllTheMods/atm6-sky#587]
![image](https://user-images.githubusercontent.com/54559451/134851090-808e60b4-ac18-418b-b672-f04653f0a514.png)
The controller slave doesn't extend the range of the controller, it only adds another place to access the network's inventory. The network's size is hard limited by the range of the controller, there's no way to extend it.

**Comment by oly2o6** [comment]
must have been an oversight from the quest team, thank you for fixing this, honestly surprised it was not found sooner
