### ISSUE TITLE
Multiple recipes for compressed cobblestone (and other blocks)

### ISSUE THREAD

**Issue by justinkillen** [AllTheMods/atm6-sky#590]
**Describe the bug**
Since upgrading to 1.1.8 and applying the cyclic 1.16.5-1.3.8 update to fix https://github.com/AllTheMods/atm6-sky/issues/564, I've had an issue where there are 2 different crafting recipes for a 3x3 grid of cobblestone - one for "Compressium: Compressed Cobble (1x)" and one for "AllTheCompressed: Cobblestone Block 1x".  And it seems that each mod in the pack seems to use one or the other, but changes between reloads of the pack/world (I'm not sure which).

I notice this most frequently in a setup I have for sieving:

pedestal -> drawer controller / compacting drawer -> auto hammer.

The compacting drawer seems to always use AllTheCompressed, but other blocks like the RFToolsUtility Crafter are sometimes AllTheCompressed and sometimes Compressium.  The auto hammer ONLY accepts Compressium, so if the Crafter happened to choose the AllTheCompressed recipe, the whole setup breaks (the same for other blocks too, like gravel).

Side-note: I've noticed that some mods like RefinedStorage let you pick either, which is nice.

Also, this didn't seem to be an issue in the previous version, so it might be related to the 1.1.7 -> 1.1.8 upgrade, or perhaps related to my manual patch/update of cyclic.

**Expected behavior**
It would be nice if all mods would allow either like RefinedStorage, but I realize that is out of scope for a pack dev.
Realistically, I would hope to not have duplicate recipes, or not have ones that are so limiting as this one.  At a minimum, it would be nice to have a custom recipe to be able to convert between the Compressium variant and the AllTheCompressed variant and vice-versa.

**Comment by Pdiddy973** [comment]
update AllTheCompressed, or wait till the next update will be fixed then.

**Comment by justinkillen** [comment]
Thanks @Pdiddy973 for the quick response.

Also, I see now that there are other issues about this already:
https://github.com/AllTheMods/atm6-sky/issues/562
https://github.com/AllTheMods/atm6-sky/issues/553
https://github.com/AllTheMods/ATM-6/issues/2264

Sorry for the dup - next time I'll check before opening an issue.
