### ISSUE TITLE
I keep getting Datapack errors trying to load into my Singleplayer World

### ISSUE THREAD

**Issue by ZornyETM** [AllTheMods/atm6-sky#594]
So i tried loading my World and all of a sudden i started getting the issue that tags are missing and i am supposed to contact the server owner, even tho i am playing in sinlgeplayer and then i keep getting the message: "Datapack errors prevent the world from loading [...] Try safe mode or go to the main menu to solve it manually". I have no idea what i am supposed to do here as safe mode is not working and i don't see datapacks anywhere. When i try to start a new singleplayer world i get the same error all the time.

I attached a crash report and the latest log in my folder if that is of any help.

[crash-2021-10-02_00.25.59-client.txt](https://github.com/AllTheMods/atm6-sky/files/7271189/crash-2021-10-02_00.25.59-client.txt)
[latest.log](https://github.com/AllTheMods/atm6-sky/files/7271192/latest.log)

Any help would be appreciated

**Comment by notFalkon** [comment]
update pack or cyclic

**Comment by ZornyETM** [comment]
Thanks^^
Updating worked. I totally didn't see the update button. My bad.
