### ISSUE TITLE
No Coal Coke from Immersive Engineering

### ISSUE THREAD

**Issue by TEXHIK** [AllTheMods/atm6-sky#596]
**Describe the bug**
Coke produced by IE coke oven is from thermal series, however IE machinist villager wants IE coke only.
So it only possible to waste emeralds on hammers if you want to level him up (cause there are two trades at the start - buy coke and sell hammer)

**To Reproduce**
1. Smelt coal or coal block in Immersive Coke oven
2. you get Coke/Coke block from Thermal series
3. Get Machinist villager from IE (workstation - anvil) Andtry to sell coke.
4. Villager does not accept thermal coke, IE coke is unobtainable. So you shoul just by tons of hammers for 4 emeralds - that's insane

**Expected behavior**
Villager accept any coke, or Coke oven gives IE coke

**Screenshots**
![2021-10-04_22 53 10](https://user-images.githubusercontent.com/27730114/135916662-e252ac4f-bbb6-491b-a3a1-a8deb53a322e.png)
![2021-10-04_22 53 08](https://user-images.githubusercontent.com/27730114/135916098-8499962c-5abb-44f5-aea2-637fce93e891.png)
![2021-10-04_22 53 12](https://user-images.githubusercontent.com/27730114/135916163-fb70aacf-6924-432e-81b8-1d6325e74c72.png)
![2021-10-04_22 57 26](https://user-images.githubusercontent.com/27730114/135916176-3c2850f9-7dbc-4da1-8889-2fa426235368.png)

**Comment by notFalkon** [comment]
As a workaround, tou can probably get IE coal coke from the mekanism oredictionifier. It might unify in your inventory into thermal coal coke, but not sure. If it does, just put the villager into a villager trading block from `@easyvillagers` and pipe from the oredictionifer directly into that
