### ISSUE TITLE
Quests not complete from older save in new version

### ISSUE THREAD

**Issue by DJDrWright** [AllTheMods/atm6-sky#597]
Loaded a save world from a previous version, quests not complete and I cannot complete the very first checkmark quest: Welcome to All the Mods 6 Sky. I thought the quests I have already done would still be completed.

**Comment by notFalkon** [comment]
![image](https://user-images.githubusercontent.com/79824068/136075778-2f4bf8ec-4225-43c4-ae76-711275133a77.png)

**Comment by DJDrWright** [comment]
Thank you.
