### ISSUE TITLE
ATM6 Skyblock Mod Suggestions

### ISSUE THREAD

**Issue by jeremiahwinsley** [AllTheMods/atm6-sky#6]
Here is a new place to share mods you would like to see in ATM6 Skyblock. 

MAKE SURE THEY ARE UPDATED TO 1.16.5 AND ON FORGE before asking.
And only provide links to mods from Curse Forge.

If your post was hidden with "resolved" it means that it has been added, but if hidden for any other reason, it was decided against.
One submission per post to make it easier.

**Comment by pbutternj** [comment]
https://www.curseforge.com/minecraft/mc-mods/useful-railroads

**Comment by pbutternj** [comment]
https://www.curseforge.com/minecraft/mc-mods/time-in-a-bottle

**Comment by pbutternj** [comment]
https://www.curseforge.com/minecraft/mc-mods/mass-inscriber

**Comment by scarha** [comment]
https://www.curseforge.com/minecraft/mc-mods/colossal-chests

**Comment by scarha** [comment]
https://www.curseforge.com/minecraft/mc-mods/passive-charms

**Comment by scarha** [comment]
https://www.curseforge.com/minecraft/mc-mods/vacuum-chest
Better than cyclic collector i am hoping

**Comment by scarha** [comment]
https://www.curseforge.com/minecraft/mc-mods/dummy-players

Life sized dolls for you know what.

**Comment by scarha** [comment]
https://www.curseforge.com/minecraft/mc-mods/the-abyss-chapter-ii

**Comment by redcreeper14385** [comment]
https://www.curseforge.com/minecraft/mc-mods/botany-pots
Better than Bonsai Pots IMO.

**Comment by scarha** [comment]
https://modrinth.com/mod/retail
There isnt a single mod in the pack that does this. And it makes setting shops up really easy.

**Comment by Thunder-Nova** [comment]
@scarha please curseforge only
https://www.curseforge.com/minecraft/mc-mods/retail

**Comment by Ryukossei** [comment]
For Decoration Purposes we should have a the Biomes mods (then some way to get the trees, either by market, or making saplings with mystical agriculture nature essence.) 

Additionally Pam's Trees are also nice to add, just for a different food alternative.

**Comment by WhitePhant0m** [comment]
https://www.curseforge.com/minecraft/mc-mods/buildersaddition #3 By KingOnoi

**Comment by WhitePhant0m** [comment]
This adds some machines that make automating Botania simpler. Anything to make Botania simpler is great by me. https://www.curseforge.com/minecraft/mc-mods/botanical-machinery
#5 By InverseRain

**Comment by WhitePhant0m** [comment]
For both [ATM 6](https://github.com/AllTheMods/ATM-6/issues) and All the Skies (name suggestion), we could make use of a bigger crating table GUI for more endgame recipes.
The mod [Extended Crafting](https://www.curseforge.com/minecraft/mc-mods/extended-crafting) is quite useful in that remark
I was thinking ArmorPlus mod bus was not updated past it's Beta 1.16.3
#2 By Thunder-Nova

**Comment by FiveTailsGaming** [comment]
So Xpetrified ore and stella ore need ways to get them outside mining dimension.

**Comment by WhitePhant0m** [comment]
> 
> 
> So Xpetrified ore and stella ore need ways to get them outside mining dimension.

Yes, but, that isn't a mod suggestion :p

**Comment by scarha** [comment]
I dont know if you guys would be willing to add this but endgame it would be fun as an option. https://www.curseforge.com/minecraft/mc-mods/projecte

**Comment by scarha** [comment]
https://www.curseforge.com/minecraft/mc-mods/the-abyss-chapter-ii

**Comment by scarha** [comment]
https://www.curseforge.com/minecraft/mc-mods/itank

**Comment by starforcraft** [comment]
[Refined Storage](https://www.curseforge.com/minecraft/mc-mods/refined-storage)

**Comment by scarha** [comment]
https://www.curseforge.com/minecraft/mc-mods/time-in-a-bottle-standalone

**Comment by starforcraft** [comment]
Addon for Refined Storage
[Creative Wireless Transmitter](https://www.curseforge.com/minecraft/mc-mods/creative-wireless-transmitter)

**Comment by starforcraft** [comment]
[Infinite Coal](https://www.curseforge.com/minecraft/mc-mods/infinite-coal)

**Comment by anakinskytalker** [comment]
[Mahou Tsukai](https://www.curseforge.com/minecraft/mc-mods/mahou-tsukai)

**Comment by CrispyPigeon131** [comment]
After playing for an hour or so the game just doesn't feel as fluent I guess without a mass-breaking mod. I suggest Ultimine
https://www.curseforge.com/minecraft/mc-mods/ftb-ultimine

**Comment by moddedmcbytes** [comment]
[End Portal Recipe](https://www.curseforge.com/minecraft/mc-mods/end-portal-recipe)

**Comment by LotuxPunk** [comment]
Hello ! I'd suggest this mod : https://www.curseforge.com/minecraft/mc-mods/nicephore

It's a mod that give some tools in-game around screenshots, it can be great to allow players to share their creations easily !

**Comment by MelanX** [comment]
[MythicBotany](https://www.curseforge.com/minecraft/mc-mods/mythicbotany)

**Comment by MelanX** [comment]
[Morpheus](https://www.curseforge.com/minecraft/mc-mods/morpheus)

**Comment by sharon12346** [comment]
Hi! I would like to strongly suggest this mod：https://www.curseforge.com/minecraft/mc-mods/mob-farm-helpers-forge

**Comment by SpuSpu** [comment]
You think you can add some of the quark add-ons? Like Quark Building, etc. I love cobblestone bricks.

**Comment by stupex** [comment]
https://www.curseforge.com/minecraft/mc-mods/natures-aura

**Comment by FnordMan** [comment]
Angel ring: https://www.curseforge.com/minecraft/mc-mods/angel-ring/files
Just adds an affordable angel ring, kind of essential for skyblock maps in my opinion.

**Comment by BlueDuckYT** [comment]
https://www.curseforge.com/minecraft/mc-mods/the-outer-end

**Comment by FriendlyJoee** [comment]
In addition to CC: Tweaked: [Advanced Peripherals](https://www.curseforge.com/minecraft/mc-mods/advanced-peripherals)

**Comment by RemagOfficial** [comment]
https://www.curseforge.com/minecraft/mc-mods/campfire-smelting-forge

**Comment by Affehund** [comment]
Hey, I would suggest the mod [Void Totem](https://www.curseforge.com/minecraft/mc-mods/voidtotem).
This mod adds a totem that prevents you from dying in the void by teleporting you back to the surface. I think this would fit very well for ATM6 Sky.

**Comment by MelanX** [comment]
[JEA](https://www.curseforge.com/minecraft/mc-mods/jea) (JEI addon to show advancements)

**Comment by DizzyDJW** [comment]
Simple suggestion: Make it so that when you have the Everflowing Chalice in your inventory, it keeps the watering can full all the time, similar to how the old Thermal could move water from a portable reservoir into the watering can.

**Comment by tyler489** [comment]
This isnt exactly a mod request but there are mods that do it. A mod or Data pack that makes the ender dragon drop an elytra as it is currently not possible to obtain for angel ring recipe...

**Comment by masternetra** [comment]
https://www.curseforge.com/minecraft/mc-mods/snad-back-to-the-past (Provides snad for 1.16)

**Comment by MrManiacc** [comment]
https://www.curseforge.com/minecraft/mc-mods/travel-anchors

**Comment by DizzyDJW** [comment]
**_FTBBackups!!!!!!!!!!!!_**
Can't say this enough. Just lost my **ENTIRE** inventory trying to use "/clear" to clear the chat, not realizing it instantly clears your inventory without a prompt. I have **ZERO** backups.

No interest in this modpack anymore. I only had about 50+ hours in it anyways. A Mekanism Fission Reactor Setup and all the stuff in my Storage Bag... All gone, because somebody forgot to add such a simple mod...

**Comment by MelanX** [comment]
> **_FTBBackups!!!!!!!!!!!!_**
> Can't say this enough. Just lost my **ENTIRE** inventory trying to use "/clear" to clear the chat, not realizing it instantly clears your inventory without a prompt. I have **ZERO** backups.
> 
> No interest in this modpack anymore. I only had about 50+ hours in it anyways. A Mekanism Fission Reactor Setup and all the stuff in my Storage Bag... All gone, because somebody forgot to add such a simple mod...

All gone, because someone don’t know how to clear the chat and that the `/clear` command clears the inventory. It’s your fault, not the ATM team. And, as always, if you don’t know what it does, make a backup for yourself.

**Comment by starforcraft** [comment]
Yo

> 
> 
> **_FTBBackups!!!!!!!!!!!!_**
> Can't say this enough. Just lost my **ENTIRE** inventory trying to use "/clear" to clear the chat, not realizing it instantly clears your inventory without a prompt. I have **ZERO** backups.
> 
> No interest in this modpack anymore. I only had about 50+ hours in it anyways. A Mekanism Fission Reactor Setup and all the stuff in my Storage Bag... All gone, because somebody forgot to add such a simple mod...

A little Note: Press F3 + D to clear your client chat

**Comment by DizzyDJW** [comment]
> All gone, because someone don’t know how to clear the chat and that the `/clear` command clears the inventory. It’s your fault, not the ATM team. And, as always, if you don’t know what it does, make a backup for yourself.

Thanks... Super helpful... Super useful comment...

**Comment by tyler489** [comment]
> **_FTBBackups!!!!!!!!!!!!_**
> Can't say this enough. Just lost my **ENTIRE** inventory trying to use "/clear" to clear the chat, not realizing it instantly clears your inventory without a prompt. I have **ZERO** backups.
> 
> No interest in this modpack anymore. I only had about 50+ hours in it anyways. A Mekanism Fission Reactor Setup and all the stuff in my Storage Bag... All gone, because somebody forgot to add such a simple mod...

I mean /clear is a vanilla command isn't it? ... and has done the same thing since like 1.5..  how did you not know what it does

**Comment by doomradadr333** [comment]
https://www.curseforge.com/minecraft/mc-mods/compactstorage really cool chest mod

**Comment by doomradadr333** [comment]
https://www.curseforge.com/minecraft/mc-mods/quantumstorage

**Comment by pbutternj** [comment]
Best Decorative and Functional Lighting mod out there
https://www.curseforge.com/minecraft/mc-mods/fairy-lights
Fairy Lights

**Comment by doomradadr333** [comment]
you should add tinkers construct it just updated to 1.16.5 https://www.curseforge.com/minecraft/mc-mods/tinkers-construct

**Comment by pbutternj** [comment]
A great mod that would also be a good way to craft a lot of things in skyblock.
https://www.curseforge.com/minecraft/mc-mods/alchemistry/files

**Comment by Georg-Beischlager** [comment]
this would be a nice lagfree mobfarm alternative:
https://www.curseforge.com/minecraft/mc-mods/deep-mob-learning-refabricated

**Comment by DrMrPotatoe** [comment]
> this would be a nice lagfree mobfarm alternative:
> https://www.curseforge.com/minecraft/mc-mods/deep-mob-learning-refabricated

theres woot in the pack

**Comment by tyler489** [comment]
https://www.curseforge.com/minecraft/mc-mods/growable-cells-2 Because Why not..

Also I would love to see DeepMobLearning even with woot.

**Comment by Eugene21040** [comment]
https://www.curseforge.com/minecraft/mc-mods/lost-trinkets
https://www.curseforge.com/minecraft/mc-mods/loot-bag-mod

**Comment by VersioniX** [comment]
https://www.curseforge.com/minecraft/mc-mods/extended-crafting bc. it's fun:))

**Comment by TomBombadil4Real** [comment]
> This isnt exactly a mod request but there are mods that do it. A mod or Data pack that makes the ender dragon drop an elytra as it is currently not possible to obtain for angel ring recipe...
> 
> https://www.curseforge.com/minecraft/mc-mods/dragon-drops-elytra Heres a mod for it but data packs would probably be just as easy. https://vanillatweaks.net/picker/datapacks/ has one in the mobs category for Dragon eggs and elytra's. Since eggs are used in solar panels it would be nice to have

I'm not sure when it was added to the pack but you can craft an elytra with a piece that drops from the dragon and some phantom membrane already

**Comment by UnburnedToast** [comment]
Something like BetterFrames or Optifine, i have frequent game crashes, and a lot of frame stuttering, even on the lowest settings. curseforge doesnt have either of those mods, but if theres an alternative ill link it soon

**Comment by Corgam** [comment]
[Caged Mobs](https://www.curseforge.com/minecraft/mc-mods/caged-mobs) 

Mod similar to the Botany Pots and Botany Trees, which both are already inside the modpack. The difference is that instead of growing plants and trees you can imprison a mob and generate its drops. It would help reduce the lag on the servers.

**Comment by tyler489** [comment]
> [Caged Mobs](https://www.curseforge.com/minecraft/mc-mods/caged-mobs)
> 
> Mod similar to the Botany Pots and Botany Trees, which both are already inside the modpack. The difference is that instead of growing plants and trees you can imprison a mob and generate its drops. It would help reduce the lag on the servers.
So an easier version of Woot then? 
no thanks i prefer woot.

**Comment by Parmers249** [comment]
Not sure where else to post this but what about adding a stone block world type to the game? In my opinion it's more fun to mine out your base then to build it

**Comment by Trippanddip** [comment]
One of my favorite mods to help with many things.
[https://www.curseforge.com/minecraft/mc-mods/not-enough-wands](url)

**Comment by GiaruDK** [comment]
1. https://www.curseforge.com/minecraft/mc-mods/overloaded
2. https://www.curseforge.com/minecraft/mc-mods/overloaded-armor-bar
3. https://www.curseforge.com/minecraft/mc-mods/health-overlay
4. https://www.curseforge.com/minecraft/mc-mods/mmmmmmmmmmmm
5. https://www.curseforge.com/minecraft/mc-mods/rs-requestify
6. https://www.curseforge.com/minecraft/mc-mods/bountifulbaubles
7. https://www.curseforge.com/minecraft/mc-mods/natures-compass
8. https://www.curseforge.com/minecraft/mc-mods/random-loot-mod

**Comment by ogmon1243** [comment]
add rftools dimensions back in

**Comment by DrMrPotatoe** [comment]
Add the requestify mod https://www.curseforge.com/minecraft/mc-mods/rs-requestify, its like a detector but better.

**Comment by cech12** [comment]
Useful Hats mod https://www.curseforge.com/minecraft/mc-mods/useful-hats

**Comment by cech12** [comment]
Solar Cooker mod https://www.curseforge.com/minecraft/mc-mods/solar-cooker

**Comment by Slaymeister** [comment]
Auto Feeder Helmet https://www.curseforge.com/minecraft/mc-mods/auto-feeder-helmet
QOL mod. Adds a low cost (accessible almost immediately) device that you craft with any vanilla and most modded helmets to automatically feed the player from any food in inventory. Config files support adding a power requirement and blacklisting food. Great addition when using ultimine or other mods that break a lot of blocks and rapidly increase hunger.

**Comment by MasterOfBob777** [comment]
[Curious Jetpacks](https://www.curseforge.com/minecraft/mc-mods/curious-jetpacks)

**Comment by QWERTYlimau** [comment]
https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2-wireless-terminals-forge

**Comment by twothe** [comment]
I see much potential in this variant of the pack, however the Ex Nihilo start feels very overused, tedious and boring. Also you quickly drown in resources thanks to the ability to automate all that, which kills all sense of progression. Like 8 hours into the game you no longer have any reason to continue this variant of the pack compared to the standard pack.

**Comment by HockeyZman2000** [comment]
Draconic Evolution just got updated to 1.16 (never thought I'd see the day) and would love to have it in the pack. 

https://www.curseforge.com/minecraft/mc-mods/draconic-evolution

**Comment by AHilyard** [comment]
Equipment Compare
https://www.curseforge.com/minecraft/mc-mods/equipment-compare

A simple quality of life mod that adds the ability to easily compare equipped items to those in the inventory with a keybind.

**Comment by AHilyard** [comment]
Item Highlighter
https://www.curseforge.com/minecraft/mc-mods/item-highlighter

Quality of life improvement that adds a small icon on all newly picked up items in the inventory.

**Comment by JotaEmePM** [comment]
Applied Energistics Terminals are necesary!!
https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2-wireless-terminals-forge

**Comment by oly2o6** [comment]
unused thread and pack is nearing end of life
