### ISSUE TITLE
Recipe Suggestion: Certus Quartz Dust -> Certus Quartz

### ISSUE THREAD

**Issue by Hazmatik** [AllTheMods/atm6-sky#60]
**Is your feature request related to a problem? Please describe.**
There are two recipes in JEI for using certus quartz dust in Mekanisms enrichment chamber, one turns them into regular certus quartz and the other turns it into pure certus quartz. The one that turns the dust into pure certus quartz seems to take priority so if you want to obtain regular certus quartz (to make charged certus) you have to craft the pure certus quartz into a block and then craft it back into certus quartz crystals.

**Describe the solution you'd like**
Remove the Certus Quartz Dust -> Pure Certus Quartz recipe from the enrichment chamber since there is already a recipe to change Certus Quartz -> Pure Certus Quartz in the enrichment chamber.

**Comment by oly2o6** [comment]
this is added directly by the mod authors so it would be a better idea to put this on their github
