### ISSUE TITLE
No craft recipe for dissolution chamber

### ISSUE THREAD

**Issue by SaltyColdy** [AllTheMods/atm6-sky#600]
**Describe the bug**
We can't see craft for the dissolution chamber. maybe we have recipe page but empty, or many time we have just no way to see se recipe with JEI

**To Reproduce**
1. For exemple, i try to craft the Supreme Machine Frame
2. I try to push R button for see the craft
3a. that's work but empty page 
3b. Don't work, push as hard as u can, but i broke my button and no page :'(

I don't know if it's mod author or modpack issue. I prefer explain here

**Comment by notFalkon** [comment]
Maybe you shouldn't play on an outdated version then complain about a bug that's been fixed in the newer version

**Comment by notFalkon** [comment]
half fun waiting around 20-30 days
