### ISSUE TITLE
Game crash blood magic

### ISSUE THREAD

**Issue by Exya1** [AllTheMods/atm6-sky#605]
Game Crash when crafting in alchemie table of Blood magic 

Crash log 
[crash-2021-10-24_10.50.49-client.txt](https://github.com/AllTheMods/atm6-sky/files/7405541/crash-2021-10-24_10.50.49-client.txt)
:

**Comment by jimryandp** [comment]
Encountered the same problem right now. I can't progress through blood magic without crashing every alchemy table craft.

**Comment by Stimmer02** [comment]
For now I have a chest containing items that are craftable only in alchemy table (I took them using gamemode 1 command) and I just drop ingredients into the void when I need to use that bugged table. I guess I have no other option than that workaround if I wanna progress, at least until the fix will come.

**Comment by doomfur** [comment]
Had the same issue.  Playing a local server with a friend and tried crafting with the alchemy table.  I put the ingredients in and it was fine.  When I put the blood orb in to initiate crafting it immediately crashed our game (but not the server).  When either of us tried to reconnect, it would automatically crash with a "Ticking block entity" error.  Had to use server console to delete the table to fix our game.  Tried replicating in single player but it works just fine.

**Comment by anthonyloukinas** [comment]
Same issue, "Ticking block entity". I cannot even get back into my world at all. Instant client crashes now :/

**Comment by ManciDRaffy** [comment]
Bug is still there. Please change crafting to not use Blood Magic (or optional).
I am gonna cheat all items that are crafted because there is no work around and game takes 5-10 mins to start so no option to restart everytime I need 1 Item!

**Comment by XiNaru** [comment]
the same bug... pls fix

**Comment by bezgiGaming** [comment]
Yeah just updated my client to 3.1.7-27 from 3.1.7-24 and now i can use the Alchemy Table without my game crashing.
You dont need the newer version on a server it works just for the client.

**Comment by XiNaru** [comment]
> Yeah just updated my client to 3.1.7-27 from 3.1.7-24 and now i can use the Alchemy Table without my game crashing. You dont need the newer version on a server it works just for the client.

ähm no? if you updated a mod on the client you must upodate the mod on the server too o.o. otherwise the server always says the wrong mod version or something and you can't figure it out.

**Comment by bezgiGaming** [comment]
For me it worked i can join my server no problem with the newer mod on my client.
I thaught of that but i figured i'd try it, and it worked without updating it on the server.

**Comment by XiNaru** [comment]
> For me it worked i can join my server no problem with the newer mod on my client. I thaught of that but i figured i'd try it, and it worked without updating it on the server.

i understand.
okay the thing is now, trhe crash problem can be fixed :)
