### ISSUE TITLE
Ice and Fire Dragon Forge Recipes not showing in JEI

### ISSUE THREAD

**Issue by derpicasso** [AllTheMods/atm6-sky#609]
ATM6 to the Sky 1.1.9 There are no DragonForge recipes showing in JEI. 

1. Start Game Version 1.1.9
2. Search for Dragon Steel or Allthemodium Alloys
3. See no recipes of the Dragon Forge

**Expected behavior**
I expected recipes to be shown

**Screenshots**
a Screenshot of something thats not there seems pointless

**Additional context**
Please fix, its a pain to find them online.

**Comment by EYW-015** [comment]
Update the Game Version to 1.2.0 and update Cyclic to 1.4.2

**Comment by Nediamail05** [comment]
I'm currently playing atm6 and I have the same issue. I'm on a server, however when I'm in a singleplayer world it works just fine.

**Comment by EYW-015** [comment]
> 

I'm on a server too. I'm runing mc server on ubuntu 20.04 lts.
The game version is 1.2.0, java8 on server, the client is java11. It work fine both singleplayer and multiplayer.
