### ISSUE TITLE
Teleport pad

### ISSUE THREAD

**Issue by Rafael9898** [AllTheMods/atm6-sky#611]
![2021-11-27_10 28 14](https://user-images.githubusercontent.com/95109890/143677918-f24875e1-7573-4f41-aeb8-090989d9b01f.png)
In this image it is showing that the mining dimension is disabled what can i do to enable it?

**Comment by EdwinTheNuke** [comment]
I believe this is the modpack maker's intention (no mining dimension).  I think that block is supposed to take you to the Ice and Fire dimension, but I haven't gotten that far.  Chosen Architect has an episode when he accesses the Ice and Fire dimension.  That might help.
