### ISSUE TITLE
Soul Lava Bee not Pollinating Soul Lava

### ISSUE THREAD

**Issue by Deme1983** [AllTheMods/atm6-sky#612]
i finally got the Soul Lava Bee and i was hoping after days of grinding that it would pollinate the soul lava seen in the picture but it just stays at the top of the area i built for it. or flies upside down into the soul lava in the ground. any ideas why it wont pollinate the lava to make the Soul Lava Honeycomb to finish the finish the quest. is there a issue possibly that anyone else knows how to fix?
![Screenshot_2](https://user-images.githubusercontent.com/25376037/144561697-807f6747-8924-4eda-b315-83364e72a39b.png)

**Comment by MisterJFK** [comment]
Hi, I wanted to know if you had solved your problem, because I have the same problem right now.

**Comment by Deme1983** [comment]
sadly no i havent i have stopped playing that pack because of that issue. because i could not finish all the quests i dont know when they will get it fixed

**Comment by MisterJFK** [comment]
Okay, let's hope he fixes it soon enough. Thank you for your answer

**Comment by MisterJFK** [comment]
So I found the solution to use an ender beacon and in it there are several effects, you have to click on the calming effect, and now the bee will not be irritated. You will finally have your soul lava honeycomb .

**Comment by Pdiddy973** [comment]
Bees can not pollinate when "angry" the soul lava bee is one of the few that are angry by default, so using a beecon for the calming effect or a calming splash potion is required.
