### ISSUE TITLE
High Framerate but very bad lows

### ISSUE THREAD

**Issue by Dragher** [AllTheMods/atm6-sky#613]
My Framerate in Singleplayer is fine at 50-60 fps (as limited in AMD driver) but my lows while moving sit at 9 fps and as low as 1
A new Empty world does not change the behaviour.

Setup:
Ryzen 5 5600X no OC
16 GB Ram stable OC(Passmark Memtest86, Prime95) at 3600 16-18-18-20-36
RX 6800 XT Driver: 21.12.1

ATM6-sky Version 1.1.9

Taskmanager and AMD Software show low usage of GPU and CPU
I have disabled Mipmap and Texture Animation.
8192 MB of RAM are allocated
Java Additional Arguments:
-XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true

Adding and removing Optifine had no influence.
I have tried current Java 17.0.1.0

Spark log in my World:
https://spark.lucko.me/r2ePeFB2Y9 
Spark log in New, Empty World:
https://spark.lucko.me/tr0AzEnHAp

**Comment by oly2o6** [comment]
might sound completely stupid but have you tried it without java args, and with java 16?

**Comment by oly2o6** [comment]
accidental close

**Comment by Dragher** [comment]
> might sound completely stupid but have you tried it without java args, and with java 16?

Did that and nothing changed at all

**Comment by oly2o6** [comment]
i have no clue, i am full AMD myself and have issues, but there isnt really a way to fix them which is unfortunate, MC hates AMD :(
