### ISSUE TITLE
[1.1.9] Island disappeared and Quests reset

### ISSUE THREAD

**Issue by Waoweens** [AllTheMods/atm6-sky#616]
**Describe the bug**
After not playing for a bit, I opened my world (singleplayer) and I was in the starter island. My inventory still had the items but everything else (including quests and advancements) got reset. I teleported to my known base coordinates (from an old screenshot) and it was just void. I opened the backups folder and it was empty.

Extra mods I added:
[Draconic Evolution](https://www.curseforge.com/minecraft/mc-mods/draconic-evolution) version 3.0.18.428

**To Reproduce**
1. Open the world

**Expected behavior**
> My island and quests do not disappear randomly

**Screenshots**

Backups folder

![image](https://user-images.githubusercontent.com/30313089/146672632-53dbdabe-ac80-426b-a36f-28739b4c3f0e.png)

Starter island (After it disappeared, I might have broken a couple leaf blocks, I changed to creative with Open to LAN)

![2021-12-19_17 24 00](https://user-images.githubusercontent.com/30313089/146671643-2c8a2e4c-9ba0-483d-9fcb-6f083682198d.png)

Island before it disappeared

![image](https://user-images.githubusercontent.com/30313089/146671713-a5dbe6d3-6b05-40aa-a472-6f0fa73c481b.png)

Same coordinates as image above, but after it disappearing

![2021-12-19_17 30 35](https://user-images.githubusercontent.com/30313089/146671817-e94ccfbf-799f-4365-8b3a-f2f4ce775c43.png)

Quests

![image](https://user-images.githubusercontent.com/30313089/146672595-47676b57-3d2a-41f7-b7df-4b41ae9f11c4.png)

**Additional context**
[Latest log](https://gist.githubusercontent.com/Waoweens/d6fb4d522d7ea858a5d726869bb3fd60/raw/bef950be3b7b5b3c2545ddcd894df8d9a2000a15/latest.log)
[Log from before island disappeared](https://gist.githubusercontent.com/Waoweens/25178ffe1ff4e05d362e4d2fada1f7fc/raw/961d1d5747e706357c48ba8c1932bcccfe914644/2021-12-13-1.log)
[World file](https://drive.google.com/file/d/15NsR07x3zlDrj9WdPkIorIqyWow7NKtJ/view?usp=sharing)

**Comment by oly2o6** [comment]
I honestly have no idea what happened, nor have i seen a similar issue like this, maybe there was corruption with the world? honestly no clue unfortunately, especially with their being (for some reason) no backups
