### ISSUE TITLE
XNet Controller has too large a buffer

### ISSUE THREAD

**Issue by abinns** [AllTheMods/atm6-sky#619]
Xnet controllers buffer too much RF. High transfer rate is good, but having each controller buffer 10,000,000 RF is a bit much, particularly when you use it for intro power gen...

**Describe the solution you'd like**
I'd like the buffer set to the original default of 100,000, or even 1,000,000, just something smaller than 10,000,000

**Additional context**
Eg, please change the number here:
https://github.com/AllTheMods/atm6-sky/blob/55649bcebfe0a3314f99b358bf81b64448830269/defaultconfigs/xnet-server.toml#L8

**Comment by oly2o6** [comment]
fixed in next version
