### ISSUE TITLE
I can't log in after the update...

### ISSUE THREAD

**Issue by wibabe** [AllTheMods/atm6-sky#62]
update 1.0.4
![image](https://user-images.githubusercontent.com/71390305/111919245-fd588b80-8a99-11eb-94b5-721935b9ad0e.png)
Is there a solution? :(

**Comment by martinegui** [comment]
Same here, but I just have a black screen.
No messages after click to load my world, just blac screen.

**Comment by WhitePhant0m** [comment]
That tells us nothing, give us your log...

**Comment by wibabe** [comment]
After the update, it already works thanks! You can close the topic.
