### ISSUE TITLE
Server lag to crash when placing Bigger Reactor blocks

### ISSUE THREAD

**Issue by reserveword** [AllTheMods/atm6-sky#620]
**Describe the bug**
When you places a Bigger Reactor reactor block (Controller, Interface, etc.), server stops ticking and finally crash. I tried a 600-second max tick time and it's still not enough.
**To Reproduce**
1. start a server
2. start a client and join that server
3. get a Bigger Reactor place it down
4. wait till the server kicks you out

**Expected behavior**
no lag happens and the controller is placed down

**Additional context**
log and crash report here

[2021-12-23-8.log](https://github.com/AllTheMods/atm6-sky/files/7766994/2021-12-23-8.log)
[crash-2021-12-23_06.15.16-server.txt](https://github.com/AllTheMods/atm6-sky/files/7766996/crash-2021-12-23_06.15.16-server.txt)

**Comment by oly2o6** [comment]
should be fixed in the next version (unreleased) reopen if needed after
