### ISSUE TITLE
The blood magic alchemy table makes the client crash when playing on a server

### ISSUE THREAD

**Issue by Yoseidon** [AllTheMods/atm6-sky#624]
**Describe the bug**
On server, when you try to craft with the alchemy table, the client crashes but not the server, after that you can't reconnect, and when you try the game crashes.

**To Reproduce**
1. Go on an ATM 6 to the sky server
2. Craft the blood magic alchemy table
3. Use the table

**Expected behavior**
The table does the craft correctly and the game does not crash

**Additional context**
The bug is patched by version 3.1.5 and on ATM6 to the sky blood magic is in 3.1.4-24

**Comment by oly2o6** [comment]
working on an update right now to fix this, so ill close as its confirmed working in atm6
