### ISSUE TITLE
Dedicated server failure

### ISSUE THREAD

**Issue by AbsolutePhoenix** [AllTheMods/atm6-sky#63]
Version: 1.0.4
When connecting the a dedicate server it will result in a connection failure
"Failed to synchronize registry data from server, closing connection"

Client results with a log of:
https://pastebin.com/GzDaR78Q

**Comment by AbsolutePhoenix** [comment]
I have figured out the issue.
Adding the config folder that are generated by the dedicated server the the client fixes the issue.
The issue seems to go further though. The files are missing from the client all together so i assume that somewhere between 1.0.3.c and 1.0.4 the files on the build have become missing...or a more likely case as you can not download a fresh version of the pack via the curse launcher and can only update that the curse zip is corrupter and was unable to update the files so it removed them instead.

**Comment by AbsolutePhoenix** [comment]
also the missing files also brakes the jetpack quest as they are not present to load the jetpacks at all.

**Comment by WhitePhant0m** [comment]
Fixed in 1.0.4b
