### ISSUE TITLE
Copy-Paste Gadget Crashes Server

### ISSUE THREAD

**Issue by Robocat4000** [AllTheMods/atm6-sky#630]
Every time I use the copy-paste gadget to paste my lava generation system, the server crashes.

**To Reproduce**
It may be possible to reproduce but I'm not sure. When copy pasting, make sure your copied blocks have, cobble gens(tier 5), cauldrons for melting the cobble, mekanism pipes, and transporters(may be a problem with them being prior configured, have a refined storage external storage set to fluid mode

**Comment by oly2o6** [comment]
might be something to do with the cobble generators, the copy paste gadget is really supposed to be for building only
