### ISSUE TITLE
bug in mod dependency

### ISSUE THREAD

**Issue by XiNaru** [AllTheMods/atm6-sky#633]
there a a bug with refined storage auto crafting.

if i want to craft the 1024k storage part, there needs the 256k storage part, okay.
but, the but ask for the parts from the extra STORAGE mod, but there are no 256k storage part.
the 256k storagepart i need, is in the Extra Disks Mod.

https://i.imgur.com/GkTmvJ1.png

https://i.imgur.com/JcJXMcv.png

**Comment by oly2o6** [comment]
should be rectified in latest
