### ISSUE TITLE
Bug in Exnihilo/sieve drops

### ISSUE THREAD

**Issue by ZaoFran** [AllTheMods/atm6-sky#634]
https://prnt.sc/26ipwkx
Hey guys. I'm playing ATM6 to the sky (1.1.8) with a friend and after watching some videos we noticed that some drops were missing from our sieves (gravel drops with diamond mesh or above, like prosperity shard, ores from thermal series, etc.). And than i tried playing the same modpack on a single player world, and it was working fine with all the drops. The problem is just when playing on a server, anyone knows how to solve that?. Sorry for any grammatical error.

**Comment by oly2o6** [comment]
Would need to freshly install the kubejs file onto the server
