### ISSUE TITLE
Easy Villager Conflict and Mob Imprisonment Tool 

### ISSUE THREAD

**Issue by MisterJFK** [AllTheMods/atm6-sky#635]
mod pack version 1.2.0

I would like to recover a villager in a Mob Imprisonment Tool but it doesn't work because I recover it in my inventory instead. I tried the technique of putting him in a bed but it doesn't work. I also deactivated the "sneak_pick_up" in the configuration file of Easy Villager but it still doesn't work and I always get him in my inventory. Do you have a solution ?

**Comment by oly2o6** [comment]
shifting vs not shifting, offhand vs regular, its one of those that we implemented just cannot remember which as it was almost a year ago now
