### ISSUE TITLE
[FULL][1.2.0] Server stops upon launch

### ISSUE THREAD

**Issue by BasedGodZoo** [AllTheMods/atm6-sky#636]
Just wanna start with thanks for your time, it's greatly appreciated.
Upon using the simple server files the modpack files seems to install just fine, but crashes right upon the launch of the server. It doesn't even create a crash log, so I'm extra clueless on what the issue could be.

![Server start log](https://user-images.githubusercontent.com/98657634/151669750-b5489b77-2d77-4510-be91-d1cbfb566693.png)

**Comment by TastyD** [comment]
I am having the same issue! Tried it on linux and windows. Same error on both operating systems.

**Comment by Mystik314** [comment]
same for me

**Comment by oly2o6** [comment]
Try java 11 (its a requirement for server starter), if not its also the reason why we are discontinuing serverstarter
