### ISSUE TITLE
Full Version [1.2.0] Force loaded chunks unload themselves and must be reselected

### ISSUE THREAD

**Issue by EdwinTheNuke** [AllTheMods/atm6-sky#637]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by EdwinTheNuke** [comment]
Full Version [1.2.0] Playing on private server on MCPro Hosting. I had been playing for about 70 hours before this started happening. I selected 17/25 chunks to be force loaded. After I log out or about 30 minutes the chunks that I selected to be chunk loaded are unselected. I have to go through and reselect them. This started shortly after I added my son as the second member of the team. FTBTeams said he was in my "Party" but he couldn't interact inside claimed chunks until I made him an OP. I'm not sure if these issues are related. The chunks remain claimed but not loaded.

**Comment by EdwinTheNuke** [comment]
I figured out that since my son hasn't been on in three days, our team chunks are unloaded.  With team play I really think any team member being on should reset that timer.  I'm not sure if it is an MCPro Hosting setting or a modpack setting.  I'm investigating with MCPro right now.

**Comment by EdwinTheNuke** [comment]
Ok, so technically this is not a bug so much as an undocumented feature.  It'd be great if anyone on the team reset the chunk unloader timer.

**Comment by oly2o6** [comment]
you can find it in the server config crash utilities file, it will be a config option you need to set to false to disable
