### ISSUE TITLE
Server missing a recipe

### ISSUE THREAD

**Issue by blueberry1048** [AllTheMods/atm6-sky#640]
Missing the 3 unobtainium alloy recipe from ice and fire. Could you help me to find the bugs?
![Screenshot ](https://user-images.githubusercontent.com/85067626/153572133-dcd228c6-0bca-46b8-bea5-f2e511685079.png)

**Comment by X3NekoChanX3** [comment]
Can confirm we have the same issue on the server I play (Version 1.8.20 [had the same issue for a while now with other server versions])

**Comment by oly2o6** [comment]
adding this whilst i look into what would cause it, might just need to replace your kube file with a fresh one on the server maybe? let me know if it works in the next update, if it does not ill ask around and see if its everyone or just a few getting the same issue

**Comment by oly2o6** [comment]
turns out the recipe works its just sometimes not visible in jei
