### ISSUE TITLE
Ice Dragon duplication bug

### ISSUE THREAD

**Issue by Usualworry** [AllTheMods/atm6-sky#641]
**Describe the bug**
If you grow an put an ice dragon egg in water and use a time in a bottle to speed it up it hatches and explodes into many baby dragons

**To Reproduce**
1. make 3 by 3 puddle of water
2. put ice dragon egg in the middle
3. wait for the middle ice to freeze
4. right click the ice a bunch with the time in a bottle
5. watch the dragon egg exploding into 20 or so dragons

**Expected behavior**
Only one dragon to come out

**Screenshots**
![2022-02-16_12 48 10](https://user-images.githubusercontent.com/99810133/154280054-9397a68f-3869-4220-9ceb-8011acdc4e5f.png)

**Additional context**
Playing on ATM6 to the sky, version 1.1.8

**Comment by oly2o6** [comment]
unfixable, but also please dont do this as the only fix would be to remove the bottle, and i like being liked on the internet :)
