### ISSUE TITLE
Disconnected: Illegal Packet Received

### ISSUE THREAD

**Issue by KumaSlayer** [AllTheMods/atm6-sky#645]
Recently me and my friends had a bug wich disconnected everyone except the host from the server saying "Illegal Packet Received" and we werent sure what to do so i found out that fans and xp taps from mob grinding utils mod and dimensional tanks causes a lot of bugs.
I tested out removing those blocks and it worked fine so be sure not to use them.

**Comment by oly2o6** [comment]
the mod has quite a few updates since i last updated the pack, hopefully this is all fixed!
