### ISSUE TITLE
Tier 1 beehive recipe missing

### ISSUE THREAD

**Issue by Austin001316** [AllTheMods/atm6-sky#651]
**Describe the bug**
Tier 1 beehive recipe does not work

**To Reproduce**
Put the recipe in a crafting table, cant craft

**Expected behavior**
To be able to craft a tier 1 beehive

**Screenshots**
![image](https://user-images.githubusercontent.com/91763031/158226298-de1fe73f-fb88-4ebc-b112-1ce76148c444.png)

**Additional context**

**Comment by RossP4ge** [comment]
![image](https://user-images.githubusercontent.com/87759452/158540794-9b942a45-da6b-43bd-a1f0-2a62a49b6562.png)

It's worth noting that I spawned in the tier 1 beehives as they were uncraftable, even after placing them down and breaking them the recipe still doesn't work

**Comment by Denthris** [comment]
Been playing this pack, and wanting to get into Resourceful Bees,  had to enter creative to load in some of the Mods normal spawning structures. Used the Grass Bee hive, and was able to get the Tier one recipe working. Granted had to spawn them in, place them down and dig them up. Granted none of those Recipes can be spawn in naturally from my knowledge. The Minecraft Bees Nest, and the Natural Spawning Beehive, do not work for this recipe.  Could not get the Apiary recipie to work. Would be nice if all the aspect of this Modpack were actually playable.

**Comment by oly2o6** [comment]
Hi Denthris, whilst i feel your concern you also have to remember that this is a very big modpack and this was working previously, so until its reported there is nothing we can do as we cannot check thousands of recipes with every update, we will work to get this working for the next update to make sure "every aspect of this modpack were actually playable", thank you for taking time out of your day to bring this to our attention :)

**Comment by oly2o6** [comment]
(fixed in next version, vanilla beehives can be used in the resourceful bee recipes again)
