### ISSUE TITLE
Update forge from 36.2.23 to 36.2.26 or newer

### ISSUE THREAD

**Issue by JulianVennen** [AllTheMods/atm6-sky#653]
**Is your feature request related to a problem? Please describe.**
Starting forge versions before 36.2.26 on java 8 versions after u321 causes a crash.

**Describe the solution you'd like**
Update the modpacks forge version to 36.2.26 or newer
 
**Additional context**
Server log: https://mclo.gs/Ad9nZ7p
Official forge issue: https://github.com/McModLauncher/modlauncher/issues/91

**Comment by oly2o6** [comment]
done in next ver
