### ISSUE TITLE
Plastic for pneumatic craft recipes

### ISSUE THREAD

**Issue by Austin001316** [AllTheMods/atm6-sky#654]
**Describe the bug**
The different kind of plastics are no longer interchangeable for pneumatic craft recipes

**To Reproduce**

Try to use any other ore dic plastic for pneumatic craft recipes
**Expected behavior**
It would craft like normal

**Comment by oly2o6** [comment]
pnumaticraft plastic compared to other mods is quite an extensive task so i think its better this way, we never changed this mechanic but i do think i prefer it the way it currently is.
