### ISSUE TITLE
No skyblock worldgen? (or anything in my inventory including questbook)

### ISSUE THREAD

**Issue by dima970234** [AllTheMods/atm6-sky#656]
**Describe the bug**
I thought this mudpack would have a sky block world gen. I tried all of  the options (caves, sky islands, bigger biomes, except super flat because why would I try that)

**To Reproduce**
1. Go to singleplayer
2. Click on world types
3. try creating world for any of them
4. See that they are not skyblock

also a side note, I noticed there was nothing in my inventory when I loaded up my world too. Including quest book

**Comment by Wolf68k** [comment]
What version of Java are you using? Should be using Java 8 for this pack.

**Comment by dima970234** [comment]
I had to restart my pc to fix it. It also said in the curseforge mod loader
that it had 0 mods. But after restarting, it was just fine. Sorry I forgot
to the mark the issue as resolved.
