### ISSUE TITLE
Enchantment Applicator not making enchantments past vanilla level

### ISSUE THREAD

**Issue by Lavabounce** [AllTheMods/atm6-sky#657]
**Describe the bug**
When using an enchantment applicator with plenty of essence, I could not get past Vorpal 3. It would just return the sword to me and consume the Vorpal 3 book.

**To Reproduce**
1. Enchant a sword with Vorpal 3.
2. Place the enchanted sword and a Vorpal 3 book in the enchantment applicator with power and essence.
3. The new sword will still have Vorpal 3.

**Expected behavior**
I expected that the sword that was created would have Vorpal 4.

**Comment by oly2o6** [comment]
This only works if apotheosis or a mod that removes the limit on enchantment levels is present, which in this modpack it is not
