### ISSUE TITLE
Duplicated ore pieces for Allthemodium etc - way too easy to get

### ISSUE THREAD

**Issue by LemonShaped** [AllTheMods/atm6-sky#658]
The JAOPCA mod includes ore pieces for Allthemodium, Vibrainium and Unobtainium, which are not balanced and are super easy to get, compared to the custom KubeJS ore pieces which are properly balanced.

**Expected behavior/Fix**
Either remove access to JAOPCA versions,
or remove the kubejs ones and balance the jaopca ones instead.

**Screenshots**
![image](https://user-images.githubusercontent.com/64607380/160894174-15aa4779-5898-472c-9f9d-ececd38317cf.png)
![image](https://user-images.githubusercontent.com/64607380/160894225-98922221-d714-427a-a3a4-2c43ccfeca7a.png)

![image](https://user-images.githubusercontent.com/64607380/160893093-9f4da1d0-2fd1-44b5-bae0-58646152b164.png)
![image](https://user-images.githubusercontent.com/64607380/160893525-2e4ad193-d7c5-44f1-b1ec-ff565f3cf573.png)

**Comment by oly2o6** [comment]
fixed in next ver
