### ISSUE TITLE
Basalt ( Raw ) (Chisel) has no recipe.

### ISSUE THREAD

**Issue by Mat1212fr** [AllTheMods/atm6-sky#659]
Chisel Basalt can only be crafted with Essence Basalt which is created by the Basalt Seed which cannot be created because it requires Basalt from Chisel which itself can only be crafted with Essence Basalt. It's a vicious circle !

Translated with Google Translate ( I do not speak english very well )
![image](https://user-images.githubusercontent.com/99351856/161425525-1720846f-b910-4d1d-83db-6c350c116b3b.png)
![image](https://user-images.githubusercontent.com/99351856/161425540-15eb713a-5a15-4d53-9528-6d3cd9ba5a3b.png)
![image](https://user-images.githubusercontent.com/99351856/161425594-a4206a8f-3f69-45eb-a591-32881b3045e0.png)

**Comment by oly2o6** [comment]
fixed in next version, basalt can now be made with the ex nihilio basalt pebbles
