### ISSUE TITLE
Astral Sorcery  starmetal not attainable

### ISSUE THREAD

**Issue by thorzy** [AllTheMods/atm6-sky#66]
In the current version there is no percievable way to create starmetal.
The recipes for starmetal requires starlight infusion which is impossible due to no astral collector crystals being available
in the world and to craft one you already need starmetal.

Suggest adding either a craftable recipe for starmetal or a way to attain a collector crystal.

**Comment by tyler489** [comment]
I was told that the tier 6 void miner can get it

**Comment by oly2o6** [comment]
its in the quests

**Comment by thorzy** [comment]
The quests give you a rock crystal which is useless towards making a collector crystal unless you have star metal already also the starmetal dust is uncraftable, neither the starmetal not it's dust form show as craftable in JEI in version 1.0.4
