### ISSUE TITLE
Endgame ingots in the first minutes of the game

### ISSUE THREAD

**Issue by DiamondMasterPl** [AllTheMods/atm6-sky#660]
**Describe the bug**

well, in the freshest build, flint sieve can get allthemodium from gravel, as well as other resources from other crushed materials, and i dont think this is supposed to happen

**To Reproduce**
use flint tier mesh

**Expected behavior**

basic early game materials, not featuring endgame materials

**Additional context**

i was using the newest build

**Comment by DiamondMasterPl** [comment]
it might be just the heavy sieve as well

**Comment by oly2o6** [comment]
honestly, no idea how or why this is happening the file hasnt been changed in nearly 6months that handles that so its been racking my brain

**Comment by oly2o6** [comment]
fixed in next
