### ISSUE TITLE
Forbidden & Arcanus bone tools removed

### ISSUE THREAD

**Issue by Wolf68k** [AllTheMods/atm6-sky#661]
pack version 1.2.1
Forbidden & Arcanus removed the bone tools in the final release of 16.2.0. 
-Removed Bone Tools:

They didn't really add anything so we decided to remove them. Arcane Bone Meal got added as replacement.

The last version that had bone tools was 16.2.0-beta-4, which was in the pack version 1.2.0

edit:
The workaround was to change the reward to minecraft:stone_axe/pickaxe because it's the same durability.

**Comment by oly2o6** [comment]
fixed in next
