### ISSUE TITLE
Some recipes of Mana and Artifice possible in JEI

### ISSUE THREAD

**Issue by HalloTheEngineer** [AllTheMods/atm6-sky#663]
**Describe the bug**
If you open for example the recipe of Mana and Artifice's _Mote of Fire_ and click Move Items in JEI, the crafting grid will fill with blaze powder and glowstone (as normal behavior), and sometimes the recipe outputs an item called _Ritual of the Searing Inferno_.

**To Reproduce**
1. Open the Wireless Crafting Grid (Refined Storage)
2. Open the recipe of Mote of Fire in JEI
3. If the items are available in your Refined Storage network, click Move Items ("+" icon) 
4. The crafting grid will fill and sometimes you can grab a Ritual Metal from the output (no ghost item)

**Expected behavior**
When you try to move the items that are needed for the recipe Mote of Fire, the crafting output should stay empty.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/83722147/163683409-8bce7f27-faf3-490c-9bc2-7fb0d65dda71.png)
![grafik](https://user-images.githubusercontent.com/83722147/163683422-efc73c60-d85f-4f8f-b15c-68dc49cb34d9.png)
![grafik](https://user-images.githubusercontent.com/83722147/163683549-b63bcfb3-d704-4829-b703-f3c1cbcd6181.png)
![grafik](https://user-images.githubusercontent.com/83722147/163683578-8633b487-905a-4551-b8f5-0e6335279de6.png)
![grafik](https://user-images.githubusercontent.com/83722147/163683591-5c1dcfdd-d704-485d-8e67-74df228802bd.png)
![grafik](https://user-images.githubusercontent.com/83722147/163683618-74b7c269-cb26-4626-917d-319b444b3efd.png)
![grafik](https://user-images.githubusercontent.com/83722147/163683628-8131a6e6-46af-406f-b301-7c45194ddd41.png)
![grafik](https://user-images.githubusercontent.com/83722147/163683641-aa738cd1-9b06-40b0-8cc2-767d14ca4bde.png)
![grafik](https://user-images.githubusercontent.com/83722147/163683657-0f2f3ece-9618-416f-9bc0-808686960578.png)
![grafik](https://user-images.githubusercontent.com/83722147/163683667-7ed04e4a-9dc2-4e95-83b8-4b6ecd4b02b1.png)

**Additional context**
Also possible with:
Mote of Air
Mote of Earth
Mote of Water
Mote of Magic
Mote of Ender
(full crafting grid isn't needed)

**Comment by oly2o6** [comment]
We could fix this, but this should be reported to mana and artifice for them to fix, as it will be a bug across all packs
