### ISSUE TITLE
Turtle bait 

### ISSUE THREAD

**Issue by DevilMayCryIfrit** [AllTheMods/atm6-sky#673]
Hi I need turtles for the quest of turtle seeds but first need turtles from bait but can't figure out right spawn conditions. Please tell the conditions for spawns or Please add turtle spawn eggs as a quest reward. Please note that I tried bait in beach, ocean and basic spawn locations but all said Please add environment conditions.

**Comment by DevilMayCryIfrit** [comment]
I don't need the bait anymore apparently turtles spawn on Blessed earth while in desert but would still like to learn about the bait so I will leave it open

**Comment by DevilMayCryIfrit** [comment]
Sorry just checked the 5by5 area of my Blessed earth has desert, beach, and lukewarm ocean so I don't know which biome are spawning  the turtles

**Comment by Bloodiko** [comment]
Turtles dont have specifica spawning coditions. Just the usual ones for most mobs apply. 

Grass Blocks, A water source, Grass, Flowers, Tallgrass. 

Basically, Grassland, a water source and then one bonemeal  on the grass to spawn grass and flowers and it will work.

**Comment by DevilMayCryIfrit** [comment]
I know it says that on the main source but it keeps saying please place items from home environment it may be bugged oh well I am tired of looking for answers with no answers thanks anyway
