### ISSUE TITLE
Iron Jetpacks

### ISSUE THREAD

**Issue by Javajoe0224** [AllTheMods/atm6-sky#68]
After dl'ing the newest patch and running the game. The Iron jetpacks are missing. The diamond one I was wearing was gone as well.

**Comment by iliaskar97** [comment]
same issue here

**Comment by ariosos** [comment]
Only the belt and coils are available. (This makes one of the quests have a question mark on it).

**Comment by WhitePhant0m** [comment]
Seemed to be some config issues on 1.0.4 for some reason, it's fixed on 1.0.4b, update to that.
