### ISSUE TITLE
OptiFine

### ISSUE THREAD

**Issue by VoidableMoon884** [AllTheMods/atm6-sky#694]
Hello, my laptop isn't so good, so I will install OptiFine. But when I added OptiFine in the "Mods" folder, the game doesn't start. Can anyone help me?

**Comment by Shadedstalker** [comment]
Optifine doesn’t work by itself with forge you need to add a separate mod so that it doesn’t crash I can’t remember exactly what it’s called as it’s changed

**Comment by ConnorJBrown** [comment]
I added OptiFine_1.16.5_HD_U_G8.jar to the mods folder and it works fine for me
