### ISSUE TITLE
Skyblock recipe request thread

### ISSUE THREAD

**Issue by Thunder-Nova** [AllTheMods/atm6-sky#7]
**Welcome to the Skyblock recipe request thread.**

**Please Post your suggestion per post**

**Grouped posts are ok, as long as it's related, such as list of Compressed blocks**

**Fix type suggestions are highly encouraged**

**Please be a balanced suggestion: So if the item originally has no easy access, leave it that way, there are multiple ways to craft / grind / infuse, so it is encouraged to use a variety depending on the difficulty**

**Comment by Kurunoa** [comment]
pure certus quartz crystals -> Smelt -> silicon
pure fluix crystals -> Smelt -> silicon

**Comment by Thunder-Nova** [comment]
Gonna add:
**Soul lava bucket**
Lava bucket + 1 of each mob essence (Ghast, Wither, Guardian, Blaze, Zombie, Skeleton, Creeper, and Dragon)

**Comment by pbutternj** [comment]
Dense ME Cable -> 4x Covered ME Cable
4x Covered ME Cable -> Dense ME Cable
Smart Dense ME Cable -> 4x Smart ME Cable
4x Smart ME Cable -> Smart Dense ME Cable

**Comment by pbutternj** [comment]
Flint Block and Compressium recipes for said block

**Comment by pbutternj** [comment]
Compressium for Sky Stone

**Comment by Thunder-Nova** [comment]
Compressium for dust, endstone powder, netherrack powder

And grinding of those **compressed**:
- cobble -> gravel -> sand -> dust (once Implement)
- netherack and end stone to once implemented compressed powder versions.

This is for preparation incase we get compressed sieves.

**Comment by pbutternj** [comment]
Make recipe for steel block use Immersive Engineering Steel Block instead of Mekanism for slabs and multiblocks

**Comment by Thunder-Nova** [comment]
Moved from my main thread so White can edit and delete if it's done.

Music disc (Pigstep):
> Mystical agriculture does have music disc craftable, but pigstep is the only one which doesn't have a recipe. The common recipe is blank disc, skeleton essence, creeper essence, and a dye (makes sense). But for pigstep, blank disc, pig essence, gold essence, and nether essence.

Wet Sponge:
> Since Elder Guardian are not spawnable, this one should be simply: yellow wool and yellow coral. Though would like a form of infusion with water such as cyclic or other liquid crafting machines.

Spawners: 

> Since Apotheosis is on spawners can be upgraded, but unlike woot it does spawn entities freely. So recipes to make spawners should be somewhat expensive.

> Thanks to Pneumaticcraft we got some stuff we can work with. Empty spawner (no recipe other then a spawner), and an empty core.

> For the empty spawner's recipe, an empty core in the center, allthemodium-vibranium alloy corners, 2 unobtainium ingots at the sides, and a woot controller at the bottom, and an infinite drawer upgrade at the top.

> Afterwards all that is left is a way to infuse the empty spawner

**Comment by Thunder-Nova** [comment]
Someone mentioned about this and it's not posted here
Elytra:
> 2 leather, 6 phantom membranes, and that dragon scale that dupes elytra

**Comment by stupex** [comment]
Raw Uraninite should be dropped from sifting gravel/dust

**Comment by nddragoon** [comment]
Right now you can make compressed cobble into compressed gravel and compressed gravel into compressed sand with a non-compressed hammer, but you can't turn compressed sand into compressed dust

**Comment by ariosos** [comment]
The cobblegens could require its' previous tier to craft instead of glass, that way there's a least a progressing for the cobblegen. (I'm assuming it's going to change anyway, as even the quest book looks a little barren at the moment)

**Comment by DizzyDJW** [comment]
> Spawners:
> 
> > Since Apotheosis is on spawners can be upgraded, but unlike woot it does spawn entities freely. So recipes to make spawners should be somewhat expensive.

I would say Vibranium Bars. Vibranium takes ages to collect in adequate amounts and just obtaining 6 ingots would be a challenge. Maybe a Nether Star in the center?

**Comment by legitadimc** [comment]
> > Spawners:
> > > Since Apotheosis is on spawners can be upgraded, but unlike woot it does spawn entities freely. So recipes to make spawners should be somewhat expensive.
> 
> I would say Vibranium Bars. Vibranium takes ages to collect in adequate amounts and just obtaining 6 ingots would be a challenge. Maybe a Nether Star in the center?

Vibranium is pretty easy to obtain from The Other, so maybe something else. Forbidden & Arcanus adds spawner scraps which drop from spawners. Also why would you even want to add a recipe like that? You can find blaze spawners in the fortress and just silk touch them.

**Comment by DizzyDJW** [comment]
> Vibranium is pretty easy to obtain from The Other, so maybe something else. Forbidden & Arcanus adds spawner scraps which drop from spawners. Also why would you even want to add a recipe like that? You can find blaze spawners in the fortress and just silk touch them.

Been looking around for hours and haven't found a **SINGLE** fortress. Maybe that's why...

**Comment by DrMrPotatoe** [comment]
> > Vibranium is pretty easy to obtain from The Other, so maybe something else. Forbidden & Arcanus adds spawner scraps which drop from spawners. Also why would you even want to add a recipe like that? You can find blaze spawners in the fortress and just silk touch them.
> 
> Been looking around for hours and haven't found a **SINGLE** fortress. Maybe that's why...

they only spawn underground, so get something that can mine a lot really fast and go to town

**Comment by Hazmatik** [comment]
> > > Vibranium is pretty easy to obtain from The Other, so maybe something else. Forbidden & Arcanus adds spawner scraps which drop from spawners. Also why would you even want to add a recipe like that? You can find blaze spawners in the fortress and just silk touch them.
> > 
> > 
> > Been looking around for hours and haven't found a **SINGLE** fortress. Maybe that's why...
> 
> they only spawn underground, so get something that can mine a lot really fast and go to town

under what ground the nether is a void world?

**Comment by Daschi1** [comment]
Creative storage and creative storage fluid disk from RefinedStorage.

**Comment by WhitePhant0m** [comment]
> Creative storage and creative storage fluid disk from RefinedStorage.

@Daschi1 
We already have infinite ones tho???

**Comment by The28AWG** [comment]
Add compost recipe from Chorus Flower. A lot of these colors remain during processing.

**Comment by Eugene21040** [comment]
add slime sapling tinker 
and maybe if you added TC can remove silent gear?

**Comment by VersioniX** [comment]
Please add the original formula for crafting the ALLTHEMODIUM alloys. Thank you <3

**Comment by VersioniX** [comment]
> Please add the original formula for crafting the ALLTHEMODIUM alloys. Thank you <3

The only way to craft them is Dragon Forge... And I don't find any dragons in the other...

**Comment by DrMrPotatoe** [comment]
please consider checking the recipes for all for the bees, seeing as it is impossible to get to any of the high level bees, such as soul lava, wither, dragonic, allthemodium, vibranium and unobtanium, as well as iron, gold, aluminium and tin, because the stoned bee is uncraftable, as well as the wither bee. all this was checked using both the online chart, JEI and files.

**Comment by lootf777** [comment]
The mob spawner from apotheosis!

**Comment by AmphaRaven** [comment]
> please consider checking the recipes for all for the bees, seeing as it is impossible to get to any of the high level bees, such as soul lava, wither, dragonic, allthemodium, vibranium and unobtanium, as well as iron, gold, aluminium and tin, because the stoned bee is uncraftable, as well as the wither bee. all this was checked using both the online chart, JEI and files.

[https://docs.google.com/spreadsheets/d/1R7wVb_cWZhfT_NMqReKnONuQBwkkSp3A8yHcMOAlVYk/edit?usp=sharing](url)
I made a spreadsheet trying to map out obtaining bees, using the modpack config files and the mod's base documents. I highlighted the bees that are mentioned in one or the other, with no current means of obtaining them in ATM6 Skyblock. I see that Stoned Bee has since been updated, though the Dragon Bee, Wither Bee, and the Wither Bee Centrifuge chain (Dragonic, Allthemodium, Vibranium, Unobtainium, and Soul Lava Bees) are still unobtainable because of the lack of sources for the Netherite Bee. Netherite Bee was a hybrid in the base mod, though that hybrid uses a bee it now hybrids into.

**Comment by SomeoneJN** [comment]
@DrMrPotatoe 

> please consider checking the recipes for all for the bees, seeing as it is impossible to get to any of the high level bees, such as soul lava, wither, dragonic, allthemodium, vibranium and unobtanium, as well as iron, gold, aluminium and tin, because the stoned bee is uncraftable, as well as the wither bee. all this was checked using both the online chart, JEI and files.

It may just be your side as they are craftable, with stoned bee being obtained from breeding a cobbee and a lava bee, I can say I have obtained all of them even in the latest update

**Comment by Mightylight** [comment]
> @DrMrPotatoe
> 
> > please consider checking the recipes for all for the bees, seeing as it is impossible to get to any of the high level bees, such as soul lava, wither, dragonic, allthemodium, vibranium and unobtanium, as well as iron, gold, aluminium and tin, because the stoned bee is uncraftable, as well as the wither bee. all this was checked using both the online chart, JEI and files.
> 
> It may just be your side as they are craftable, with stoned bee being obtained from breeding a cobbee and a lava bee, I can say I have obtained all of them even in the latest update

This comment was submitted about a month ago, back when a stoned bee required lava crystal, which could not be stacked xD

**Comment by SomeoneJN** [comment]
> > @ DrMrPotatoe
> > > please consider checking the recipes for all for the bees, seeing as it is impossible to get to any of the high level bees, such as soul lava, wither, dragonic, allthemodium, vibranium and unobtanium, as well as iron, gold, aluminium and tin, because the stoned bee is uncraftable, as well as the wither bee. all this was checked using both the online chart, JEI and files.
> > 
> > 
> > It may just be your side as they are craftable, with stoned bee being obtained from breeding a cobbee and a lava bee, I can say I have obtained all of them even in the latest update
> 
> This comment was submitted about a month ago, back when a stoned bee required lava crystal, which could not be stacked xD

Oh damn, I didn't see the date other than knowing something like it was recently said in the Github feed channel, apologies then

**Comment by ariosos** [comment]
XP Bucket - empty bucket surrounded by XP essence should yield 1 Fluid XP Bucket (Mob Grinding Utils).

**Comment by DrMrPotatoe** [comment]
> XP Bucket - empty bucket surrounded by XP essence should yield 1 Fluid XP Bucket (Mob Grinding Utils).

do u know you can get a bucket of liquid XP from MobGrindingUtils by just standing on top of a xp drain singularity tank and jusp bucket out the liquid XP?

**Comment by masakitenchi** [comment]
ender pearl dust: universal grinding recipe (e.g. create, mek, even ae2's quartz grinder). Currently thermal series' the only solution.

**Comment by ifficles** [comment]
Please add thermal series creosote oil to the industrial foregoing dissolution chamber recipe for creating treated planks.  thanks

**Comment by TheLexCraft** [comment]
Osmium Ore Piece - Can you Please add Osmium Ore Piece and Osmium Ore Chunk. Because its so Hard and almost Impossible to become Osmium from Bees because its bad described. And you need Quartz to become Witch Water for the cyclic:melter and cyclic :soldifier for Mycelium.  

Prospertie Shards - Add an easier recipe for Prospertie Shards beacuse it is Impossible to become these.

**Comment by chadandersen1** [comment]
> Osmium Ore Piece - Can you Please add Osmium Ore Piece and Osmium Ore Chunk. Because its so Hard and almost Impossible to become Osmium from Bees because its bad described. And you need Quartz to become Witch Water for the cyclic:melter and cyclic :soldifier for Mycelium.
> 
> Prospertie Shards - Add an easier recipe for Prospertie Shards beacuse it is Impossible to become these.

update or reinstall your pack. These are both obtainable very easily.

**Comment by oly2o6** [comment]
unused thread and pack is nearing end of life
