### ISSUE TITLE
Teams

### ISSUE THREAD

**Issue by kankuroboa** [AllTheMods/atm6-sky#72]
I can't see a way to modify teams at all, or anything to allow cooperative quest completion, or at the very least the commands are disabled. We are on the same team, and have gone through all the commands for FTB quests and teams to try to find a way to turn it on.

**Comment by MelanX** [comment]
Did you try the `/skyblock` Commands, too? They are used for the teams when using Skyblock world type

**Comment by kankuroboa** [comment]
Oh, I didn't know about those, thanks.

**Comment by kankuroboa** [comment]
I gave those a try and they don't seem to have the function of sync the quests between the both of us. I put the both of us on the same team with /skyblock command, but it didn't seem to do anything.

**Comment by MelanX** [comment]
Yes, this does not work. You just asked for teams, not that you want them to sync your quests. About this, I have no idea but I think it’s not possible at the Moment and a bit buggy.

**Comment by kankuroboa** [comment]
Apologies, I think I just worded it poorly.

**Comment by oly2o6** [comment]
ftb will be adding teams for quests soon
