### ISSUE TITLE
Wireless Power (Flux Networks)

### ISSUE THREAD

**Issue by KillerWinsGamin** [AllTheMods/atm6-sky#73]
The Flux Plug and other Flux network blocks cannot get power from any cables or directly from the machines. I tried pipez energy pipe, mekanism’s energy cable, and a few others. I also tried directly connecting to several power producing machines without getting power to the flux plug.

**To Reproduce**
1. Get a flux plug from the Flux Network Mod
2. Have a power source such as a dynamo or generator
3. Use an energy cable capable of transferring Fe or Rf etc.
4. Connect the Flux Plug to the cable
5. It won’t charge up

The flux plug will not gain/collect power

**Comment by DizzyDJW** [comment]
No issue here. Many are aware that the "Pipez" mod has issues when inserting a buffer between them. I use mekanism pipes and flux plugs/points together without issue.

**Comment by KillerWinsGamin** [comment]
I actually found out that it was just a visual bug not displaying the stored RF
