### ISSUE TITLE
The End is broken

### ISSUE THREAD

**Issue by legitadimc** [AllTheMods/atm6-sky#75]
**Describe the bug**
End cities and chorus plants don't generate

**To Reproduce**
1. Go to the Outer End
2. Try to find a chorus fruit
3. Also try /locate endcity - won't work

**Expected behavior**
End cities should generate and so should chorus flowers.

**Comment by tyler489** [comment]
"intended behavior" according to https://github.com/AllTheMods/atm6-sky/issues/46

Not sure how your suppost to get an elytras for the angel ring

**Comment by legitadimc** [comment]
> "intended behavior" according to #46
> 
> Not sure how your suppost to get an elytras for the angel ring

Aw. It's fine. You can craft the elytras now.
