### ISSUE TITLE
The Other is always the same

### ISSUE THREAD

**Issue by legitadimc** [AllTheMods/atm6-sky#76]
**Describe the bug**
The Other looks the same for everyone and structures/dragons spawn in the exact same places.

**To Reproduce**
1. Create new world
2. Go to The Other
3. Remember the spawn
4. Generate another world
5. Go to The Other - totally the same terrain

**Expected behavior**
It should be diffrent.

**Additional context**
also please where do i find ice dragons stage 4-5 female i'm suffering help

**Comment by JellyFisheh** [comment]
> **Describe the bug**
> The Other looks the same for everyone and structures/dragons spawn in the exact same places.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Create new world
> 2. Go to The Other
> 3. Remember the spawn
> 4. Generate another world
> 5. Go to The Other - totally the same terrain
> 
> **Expected behavior**
> It should be diffrent.
> 
> **Additional context**
> also please where do i find ice dragons stage 4-5 female i'm suffering help

Have you tried changing your world seed as I'm pretty sure if you keep regenerating it on the same seed it will keep being the same.

**Comment by legitadimc** [comment]
> Have you tried changing your world seed as I'm pretty sure if you keep regenerating it on the same seed it will keep being the same.
Yes, it's occurring on diffrent seeds.

**Comment by oly2o6** [comment]
@thevortex
