### ISSUE TITLE
A few smaller Sieving/Hammering recipe glitches.

### ISSUE THREAD

**Issue by Vertigo81** [AllTheMods/atm6-sky#78]
I've found a few small issues in the sieving and smashing workflow.

Sieving compressed dirt yields only the results of uncompressed.  IE - Compressing dirt to sieve through heavy sieve wasted 8 blocks.

Sieving Coarse Dirt produces 1.4 blocks of Dirt and .4 of Gravel.  But costs .5 and .5.  You can grind a stack of Gravel combining with dirt and Sieving back to dirt More than doubling your dirt and costing 10% of your gravel.  Circumvents production of dirt by intended methods.

You can grind Platinum chunks like all the other metal chunks using create millstones or grinding wheels, but the produced ground platinum can't be smelted or washed.  It has Zero recipes, making it junk (and it doesn't seem that platinum ingots any use either.  Every recipe using them I could find would accept any metal.)

Not sure if it's intended or not, but you can't use a millstone to reduce gravel to sand.  All the other machines work, Mekanism, thermal, etc.  And you can use the large grindstones in create as well, but if you use a millstone it will only produce flint, no sand.  I didn't notice until I'd constructed a very large millstone production line >_<

And lastly - probably not a bug, but I'm trying to use Create for everything for aesthetic purposes, but the only way to produce crushed sky stone for Certus Quartz production is by Hammering, so the only automated way to produce it for sieving is with the little hammer slaves =/. It would be nice if you could produce it with the crushing wheels or millstone.

As it is, all the other crushing/grinding devices turn it into sky stone dust, which has only 1 use, making sky stone.  But you already get the dust from sieving, so there's really not much point in ever doing so.  I'd suggest changing the various crushing recipes to make crushed sky stone instead of dust.

**Comment by oly2o6** [comment]
this is a mod issue and should be reported to the author instead of us, some have also been fixed, and enhancements will be put on the dev list for discussion
