### ISSUE TITLE
Make Mystical Agriculture Blocks/Items Upgrade-able and/or Recycle-able

### ISSUE THREAD

**Issue by DizzyDJW** [AllTheMods/atm6-sky#79]
**Is your feature request related to a problem? Please describe.**
The Growth Accelerators from Mystical Aggriculture are essentially useless in the lowest tiers. They cannot be used to make the higher tiers nor can they be recycled back into essence.

**Describe the solution you'd like**
Please consider adding in a few simple recipes that take non-upgradeable/non-recyclable items/blocks and upgrades them to the next tiers.
The best way to do this for the Growth Accelerators would be to change the recipes to need 8 of the next tier essence and one of the previous Growth Accelerators to craft 4 at a time.

**Additional context**
There seems to be quite a large number of blocks/items that once made can't be used for anything else or upgraded to the above tiers.

**Comment by oly2o6** [comment]
this is a mod enhancement and should be reported to the author instead of us
