### ISSUE TITLE
Are ice and fire dragons spawning at all?

### ISSUE THREAD

**Issue by Krum26** [AllTheMods/atm6-sky#80]
I searched for 5 hrs straight the other dimension and didnt find a single ice and fire mob except cockatrice how am i supposed to get to the alloy metals if i cant find a dragon in 6hrs?? is there any bug or something wrong?

**Comment by zerofall** [comment]
I also experienced this. After reviewing https://github.com/AllTheMods/atm6-sky/issues/45 , I turned the spawn chance up from 80 to 1800. After exploring more unexplored chunks in the Other Dimension, I was still unable to find any dragons. So, I cheated in some spawn eggs for the various dragon types. The dragons spawn with tens of thousands of HP, which is not reasonable to kill manually. Unfortunately, blocks like the Mob Crusher do not leave behind a corpse, thus no loot. SO.... I cheated in the end-game paxel that does over 1000 damage, and killed a dragon that way. When I looted the body, Creative Essence dropped. Is that supposed to happen? How is any of this supposed to work?

**Comment by Vertigo81** [comment]
How did you get to the other dimension?  From what I could find the Ice and fire dragon dimension is accessed by portals in the mansion things, and there are none?

(Secondly to that, there are no Nether fortress, bastions or end cities either.  Was looking at chosen architects lets play and they exist in his game, so not sure what's different, but there are for sure none in mine.  After exploring in a 3000 block radius using an emerald jetpack I gave up and tried a locate command, nothing)

**Comment by tyler489** [comment]
> I also experienced this. After reviewing #45 , I turned the spawn chance up from 80 to 1800. After exploring more unexplored chunks in the Other Dimension, I was still unable to find any dragons. So, I cheated in some spawn eggs for the various dragon types. The dragons spawn with tens of thousands of HP, which is not reasonable to kill manually. Unfortunately, blocks like the Mob Crusher do not leave behind a corpse, thus no loot. SO.... I cheated in the end-game paxel that does over 1000 damage, and killed a dragon that way. When I looted the body, Creative Essence dropped. Is that supposed to happen? How is any of this supposed to work?

You can make a silent gems sword that does 200+ damage from what ive seen... but yeah it takes a while to kill.. I don't Believe that creative essence should drop... I didnt get any when i killed my dragon.

**Comment by tyler489** [comment]
> How did you get to the other dimension? From what I could find the Ice and fire dragon dimension is accessed by portals in the mansion things, and there are none?
> 
> (Secondly to that, there are no Nether fortress, bastions or end cities either. Was looking at chosen architects lets play and they exist in his game, so not sure what's different, but there are for sure none in mine. After exploring in a 3000 block radius using an emerald jetpack I gave up and tried a locate command, nothing)

Nether Forts are in the other dimension you need to put down an allthemodium teleport in the nether and (shift>) right click it with an empty hand.
End Cities do not exist.
Dragons are also in the Other Dimention.

**Comment by Vertigo81** [comment]
Ugh, accidentally opened a new issue and can't figure out how to delete it.  Was trying to say "Thanks, I didn't see the portal, but now I've tried it and it doesn't seem to do anything.  I placed it, snuck right clicked it, empty hand, nothing in my off hand, but nothing happens.  Tried replacing it a few times, no effect."

**Comment by Vertigo81** [comment]
Follow up - I also haven't found any dragons in the "other" dimension.  I also can't seem to re-spawn the ender dragon to get dragon breath.  Is the method changed by something in the modpack?

**Comment by oly2o6** [comment]
should be fixed in 1.0,6 (delete the other in the dimensions folder to regen it)
