### ISSUE TITLE
Ae Quantum singularity

### ISSUE THREAD

**Issue by tyler489** [AllTheMods/atm6-sky#82]
**Describe the bug**
Quantum Entangled singularities do not seem to be able to be crafted with thermals version of ender dust 
**To Reproduce**
1. drop singularity 
2. drop thermal ender dust 
3. blow it up
4. Thermal ender dust is destroyed by the explosion.

**Expected behavior**
Should make quantum entangled singularities

**Comment by oly2o6** [comment]
this has been the same for multiple years, only ae2 dust works

**Comment by tyler489** [comment]
> this has been the same for multiple years, only ae2 dust works

But Ae2 dust is disabled in the pack in favor of thermals.
