### ISSUE TITLE
Compact Machines Have Crafting Bench Recipes Instead of Field Projector Ones and No Way To Craft Tunnels

### ISSUE THREAD

**Issue by DizzyDJW** [AllTheMods/atm6-sky#84]
**Describe the bug**
All the Recipes for Compact Machines are wrong and can be done in a crafting bench rather than the Field Projectors and there are no recipes for the Tunnels, making the Compact Machines Entirely Useless.

**Screenshots**
![Screenshot 2021-03-24 201820](https://user-images.githubusercontent.com/26727521/112400174-2a957b80-8cde-11eb-9c6f-af60a88a89ac.png)

**Additional context**
Fix the recipes to utilize the Field Projectors and add in the recipes for the tunnels please.

**Comment by WhitePhant0m** [comment]
Tunnels are still W.I.P, there are TONS of ways of transporting items across dimensions and wirelessly, so they aren't useless, and about the compact machine recipe, that will be fixed at a later date.

**Comment by DizzyDJW** [comment]
> Tunnels are still W.I.P, there are TONS of ways of transporting items across dimensions and wirelessly, so they aren't useless, and about the compact machine recipe, that will be fixed at a later date.

Well through some rigorous testing even Ender Chests refuse to function inside the Compact Machines

**Comment by oly2o6** [comment]
this is a mod issue and should be reported to the author instead of us
