### ISSUE TITLE
[Crash] Placing Blocks Inside a Compact Machine Causes Crash

### ISSUE THREAD

**Issue by DizzyDJW** [AllTheMods/atm6-sky#85]
**Describe the bug**
Placing a Block inside a Compact Machine Causes an Instant Crash To Desktop.
I placed a Flux Point inside a Normal Sized Mahcine and the game crashed.

**To Reproduce**
1. Get Compact Machine.
2. Place Flux Point.
3. See error

**Expected behavior**
Placing any blocks inside a Compact Machine shouldn't cause a crash.

https://pastebin.com/JvMyQ3ZH

**Comment by WhitePhant0m** [comment]
You used W.I.P tunnels, that is the reason for the crash, making this report invalid.
