### ISSUE TITLE
Mekanism Pipes Are Broken Inside Compact Machines

### ISSUE THREAD

**Issue by DizzyDJW** [AllTheMods/atm6-sky#86]
**Describe the bug**
Mekanism Pipes, specifically logistical pipes, are broken inside Compact Machines. Items refuse to move inside pipes properly and are stuck in some sort of back and forth hyper-speed limbo inside the pipe.
Also, they seem to save their block state and refuse to update. Pics below.

**To Reproduce**
1. Go inside a compact machine
2. Place Mekanism Pipes
3. Remove and replace Mekanism Pipes

**Expected behavior**
Mekanism Pipes should function normally inside the Compact Machine.

**Screenshots**
![Screenshot 2021-03-25 023538](https://user-images.githubusercontent.com/26727521/112429592-3fd8cd00-8d13-11eb-99e2-e469ecc8f658.png)
![Screenshot 2021-03-25 023618](https://user-images.githubusercontent.com/26727521/112429601-41a29080-8d13-11eb-8b5a-29a9416903b7.png)

**Comment by DizzyDJW** [comment]
![1111111](https://user-images.githubusercontent.com/26727521/112429864-ae1d8f80-8d13-11eb-94ae-9d53eb9c6550.png)
I suspect it has much to do with the rendering issue as well

**Comment by oly2o6** [comment]
report to the mod authors
