### ISSUE TITLE
Duplication with Autoclickers

### ISSUE THREAD

**Issue by MrCandyCane** [AllTheMods/atm6-sky#87]
Describe the bug: Duplication bug.

To Reproduce:
1. Place down Auto Clicker from Click Machine mod.
2. Store any item in 1 slot internal buffer.
3. Take Crescent Hammer from Thermal Series mod.
4. Right-click the Auto Clicker to rotate it.
5. The Items should fly out of the Auto Clicker + the same items are still in the internal buffer.

Expected behavior: Just wanted to automate the feeding of Auto Sieves, once I put Food in the buffer and rotated Auto Clicker I noticed it doubled the Food amount.

![Screenshot (199)](https://user-images.githubusercontent.com/63596358/112483168-b1933400-8d70-11eb-9af2-76985f809533.png)
![Screenshot (200)](https://user-images.githubusercontent.com/63596358/112483172-b2c46100-8d70-11eb-9334-ad7eea88d03e.png)
![Screenshot (201)](https://user-images.githubusercontent.com/63596358/112483182-b3f58e00-8d70-11eb-863e-b42460517704.png)

**Comment by oly2o6** [comment]
report this to the mod author
