### ISSUE TITLE
FPS SPIKES

### ISSUE THREAD

**Issue by kian10sadler** [AllTheMods/atm6-sky#88]
when i load into the game its fine but 10 mins after my fps goes down to 40 50 i have also have optifine installed

**Comment by mohnzilla** [comment]
Also, experiencing severe lag/FPS spikes.  usually dropping all the way down to 1-2FPS.  I've tried adjusting memory allocation anywhere between 4096-12,000.

PC specs: Ryzen7 3700X; Radeon RX 5700XT; 16GB memory

**Comment by mohnzilla** [comment]
I found the fix, it apparently had something to do with the Minecraft garbage collector.  I found the fix [here](https://www.reddit.com/r/allthemods/comments/ljeyp0/atm6_1165_lag_spikes/) from reddit user enviromath.

> I was having the same thing, not sure if its exactly what's happening to you. But I have a solid computer and 16gb of ram and I allocated 7.5 to the game. After playing for about 30min to 1 hour I was having massive lag spikes which made it unplayable. I did some research and turns out it was the garbage collector in Java which was dumping useless files every 2 sec.

>I found an old thread on atm where people talked about this and gave arguments to put into the curseforge loader. What I did, is that in the curseforge loader under the "additional arguments" in the setting I entered this

>-version:1.8 -d64 -server -XX:+AggressiveOpts -XX:ParallelGCThreads=3 -XX:+UseConcMarkSweepGC -XX:+UnlockExperimentalVMOptions -XX:+UseParNewGC -XX:MaxGCPauseMillis=10 -XX:GCPauseIntervalMillis=50 -XX:+UseFastAccessorMethods -XX:+OptimizeStringConcat -XX:NewSize=84m -XX:+UseAdaptiveGCBoundary -XX:NewRatio=3 -Dfml.readTimeout=90 -Ddeployment.trace=true -Ddeployment.log=true -Ddeployment.trace.level=all -XX:+DisableExplicitGC



>Now I have like no lag spikes even after playing for hours. Hopefully this helps. As other comments mentionned, its also important to allocate the right amount of ram, not too much or too little.
