### ISSUE TITLE
Some blocks have no texture

### ISSUE THREAD

**Issue by fredooda** [AllTheMods/atm6-sky#89]
**Describe the bug**
Some blocks, mainly modded blocks, have no texture and are mimicking the sky (aka invisible). I get a (OpenGL Error: 1281 (Invalid Value)) message in chat
![image](https://user-images.githubusercontent.com/42467979/112521317-49eee000-8d94-11eb-9251-0a6ee6ce2b68.png)

**Comment by WhitePhant0m** [comment]
I'm assuming you optifine? Do you?

**Comment by fredooda** [comment]
Yeah, do you think it’s an issue with that? I’ve been using it since I started and only 15hrs in it does this

**Comment by WhitePhant0m** [comment]
Most likely optifine, try optiforge with it, it *should* fix those issues, if not, you'll just have to deal with it. not much we can do.
