### ISSUE TITLE
When auto sorting the inventory of the auto sieve the mesh will disappear.

### ISSUE THREAD

**Issue by servireettueri** [AllTheMods/atm6-sky#90]
**Describe the bug**

If you have a mesh in an auto sieve (I was using an emerald mesh) and you use the auto sort function (middle click by default) the mesh will disappear. I checked in the output chest and it's not there either.

**Comment by Pdiddy973** [comment]
Duplicate of 
https://github.com/AllTheMods/atm6-sky/issues/37
