### ISSUE TITLE
AllTheModium Teleport Pad Not Working

### ISSUE THREAD

**Issue by DizzyDJW** [AllTheMods/atm6-sky#91]
**Describe the bug**
The Teleport does not function. Tried, sneak right-clicking with an empty hand, right-clicking with an empty hand, standing on it vs standing off it, punching it. Nothing works.

**To Reproduce**
1. Place AllTheModium Teleport Pad
2. Sneak Right-Click with an empty hand
3. See Error

**Expected behavior**
I guess I was supposed to be teleported to some other dimension???

**Screenshots**
![image](https://user-images.githubusercontent.com/26727521/112563882-921bfb80-8db0-11eb-9911-800e801dc989.png)

**Comment by WhitePhant0m** [comment]
Use it in the nether.

**Comment by DizzyDJW** [comment]
> Use it in the nether.

Change the info to not say "Place in the OverWorld"
![image](https://user-images.githubusercontent.com/26727521/112568237-83394700-8db8-11eb-9041-4b10d4852df5.png)

**Comment by rwp140** [comment]
because it works in the over world for specific feature, it looks like you disabled the mining dimension where it sends you to from the **overworld**.
