### ISSUE TITLE
Flux plug and network will not import power

### ISSUE THREAD

**Issue by gbusrt** [AllTheMods/atm6-sky#92]
flux plug will connect to energy pipe, but not charge
flux play will connect to thermal energy cell , but will not charge
flux plug will connect to fist tier meknisim energy cable but will not charge 
![ATM6 sky flux bug 1](https://user-images.githubusercontent.com/30660534/112639354-16659180-8e38-11eb-994f-0f57695a425f.jpg)
![ATM6 sky flux bug 2](https://user-images.githubusercontent.com/30660534/112639363-182f5500-8e38-11eb-9467-3104f82e32a7.jpg)
![ATM6 sky flux bug 3](https://user-images.githubusercontent.com/30660534/112639375-1a91af00-8e38-11eb-8f1b-a7f24a5c8de8.jpg)

**Comment by WhitePhant0m** [comment]
flux controllers don't store power

**Comment by gbusrt** [comment]
thanks, i checker the energy pipes and they would not connect to flux point but mek cables work, got remote power :)
was looking at the wrong end of the problem
![ATM6 sky flux bug 4](https://user-images.githubusercontent.com/30660534/112642125-e53a9080-8e3a-11eb-874c-af322db23397.jpg)

**Comment by WhitePhant0m** [comment]
that issue with pipez wil be fixed in the next update :)
