### ISSUE TITLE
Pipez Mod Filtering

### ISSUE THREAD

**Issue by DarkBreaker09** [AllTheMods/atm6-sky#95]
Hey there.

How to Filter Items irgnoring NBT ?

I did search an YT but there is no Tutorial or so about this Mod.

**Comment by Topside08** [comment]
from the description if the NBT text field is empty it ignores NBT

"If the object you inserted had NBT data, the NBT string will be displayed in the second text area. You can remove the NBT text if you don't want to match NBT tags."
