### ISSUE TITLE
Resourceful Bees

### ISSUE THREAD

**Issue by Ragelyna** [AllTheMods/atm6-sky#98]
There is no certain way to obtain bees at the moment. Even checked the egg recipes but there seems to be no craftings.

**Comment by apotato321** [comment]
If you throw a buzzing doll from ex nihilo in witchwater barrel it spawns a bee

**Comment by WhitePhant0m** [comment]
Resourceful bees aren't obtainable yet, we still need to think of ways of getting them.

**Comment by DrMrPotatoe** [comment]
> Resourceful bees aren't obtainable yet, we still need to think of ways of getting them.

Maybe make them tale a bee in a jar and sorrounded by the material of the bee, but the only craftable bees should b the base materials, like rgb, zombee, gravel sanx and dist...

**Comment by WhitePhant0m** [comment]
That is something I was definitely thinking of doing, but, I heard from Resourceful bees devs that there was a DNA system being implemented or something like that, and I'd like the try using that after it comes out, tho I might make the natural bees craftable before that, we'll see if their DNA system comes out before next pack update.

**Comment by DrMrPotatoe** [comment]
> That is something I was definitely thinking of doing, but, I heard from Resourceful bees devs that there was a DNA system being implemented or something like that, and I'd like the try using that after it comes out, tho I might make the natural bees craftable before that, we'll see if their DNA system comes out before next pack update(probably wont).

Oooooooh yes me like

**Comment by oly2o6** [comment]
will be obtainable in 1.0,7
