### ISSUE TITLE
Crashed when placed down Immersive engineering work bench

### ISSUE THREAD

**Issue by riceoftheasian** [AllTheMods/atm6-sky#99]
**Describe the bug**
When I placed down Immersive engineering workbench and checked inside the workbench, the game crashed

27.03 21:15:37 [Server] Server thread/ERROR POI data mismatch: never registered at BlockPos{x=-29, y=80, z=21}
27.03 21:15:37 [Server] Server thread/ERROR POI data mismatch: never registered at BlockPos{x=-29, y=80, z=21}
27.03 21:15:48 [Server] Server thread/FATAL [ne.mi.co.ForgeMod/]: Preparing crash report with UUID f272ea38-faa1-4991-8680-40f9e36e237b
27.03 21:15:48 [Server] Server thread/ERROR Encountered an unexpected exception
27.03 21:15:48 [Server] INFO net.minecraft.crash.ReportedException: Ticking block entity
27.03 21:15:48 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:855) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
27.03 21:15:48 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?] {re:classloading,pl:accesstransformer:B}
27.03 21:15:48 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
27.03 21:15:48 [Server] INFO at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
27.03 21:15:48 [Server] INFO at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
27.03 21:15:48 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282] {}
27.03 21:15:48 [Server] INFO Caused by: java.lang.NullPointerException
27.03 21:15:48 [Server] INFO at net.minecraft.entity.player.ServerPlayerEntity.func_70670_a(ServerPlayerEntity.java:1114) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
27.03 21:15:48 [Server] INFO at net.minecraft.entity.LivingEntity.func_195064_c(LivingEntity.java:825) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:set_player_field,xf:fml:apotheosis:apothshieldblock,xf:fml:apotheosis:apothpotiondmg,xf:fml:astralsorcery:water_movement_slowdown_prevention,pl:mixin:APP:caelus.mixins.json:LivingEntityMixin,pl:mixin:APP:eidolon.mixins.json:LivingEntityMixin,pl:mixin:APP:kubejs-common.mixins.json:LivingEntityMixin,pl:mixin:APP:assets/shetiphiancore/shetiphiancore.mixins.json:MixinLivingEntity,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorLivingEntity,pl:mixin:A,pl:runtimedistcleaner:A}
27.03 21:15:48 [Server] INFO at cofh.ensorcellation.enchantment.FrostRebukeEnchantment.onHit(FrostRebukeEnchantment.java:92) ~[ensorcellation:1.2.0] {re:classloading}
27.03 21:15:48 [Server] INFO at cofh.ensorcellation.enchantment.FrostRebukeEnchantment.func_151367_b(FrostRebukeEnchantment.java:72) ~[ensorcellation:1.2.0] {re:classloading}
27.03 21:15:48 [Server] INFO at net.minecraft.enchantment.EnchantmentHelper.func_212575_b(EnchantmentHelper.java:141) ~[?:?] {re:mixin,re:classloading,xf:fml:astralsorcery:add_enchantment_helper_levels,xf:fml:astralsorcery:add_enchantment_helper_enchantments,xf:fml:astralsorcery:add_enchantment_helper_apply_modifier,xf:fml:apotheosis:apothaffixprot,xf:fml:apotheosis:apothaffixdmg,xf:fml:apotheosis:apothlure,xf:fml:apotheosis:apothlure,xf:fml:apotheosis:apothenchaffix,xf:fml:apotheosis:apothenchdata,pl:mixin:A}
27.03 21:15:48 [Server] INFO at net.minecraft.enchantment.EnchantmentHelper.func_222184_a(EnchantmentHelper.java:104) ~[?:?] {re:mixin,re:classloading,xf:fml:astralsorcery:add_enchantment_helper_levels,xf:fml:astralsorcery:add_enchantment_helper_enchantments,xf:fml:astralsorcery:add_enchantment_helper_apply_modifier,xf:fml:apotheosis:apothaffixprot,xf:fml:apotheosis:apothaffixdmg,xf:fml:apotheosis:apothlure,xf:fml:apotheosis:apothlure,xf:fml:apotheosis:apothenchaffix,xf:fml:apotheosis:apothenchdata,pl:mixin:A}
27.03 21:15:48 [Server] INFO at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_282] {}
27.03 21:15:48 [Server] INFO at net.minecraft.enchantment.EnchantmentHelper.func_77518_a(EnchantmentHelper.java:103) ~[?:?] {re:mixin,re:classloading,xf:fml:astralsorcery:add_enchantment_helper_levels,xf:fml:astralsorcery:add_enchantment_helper_enchantments,xf:fml:astralsorcery:add_enchantment_helper_apply_modifier,xf:fml:apotheosis:apothaffixprot,xf:fml:apotheosis:apothaffixdmg,xf:fml:apotheosis:apothlure,xf:fml:apotheosis:apothlure,xf:fml:apotheosis:apothenchaffix,xf:fml:apotheosis:apothenchdata,pl:mixin:A}
27.03 21:15:48 [Server] INFO at net.minecraft.enchantment.EnchantmentHelper.func_77516_a(EnchantmentHelper.java:113) ~[?:?] {re:mixin,re:classloading,xf:fml:astralsorcery:add_enchantment_helper_levels,xf:fml:astralsorcery:add_enchantment_helper_enchantments,xf:fml:astralsorcery:add_enchantment_helper_apply_modifier,xf:fml:apotheosis:apothaffixprot,xf:fml:apotheosis:apothaffixdmg,xf:fml:apotheosis:apothlure,xf:fml:apotheosis:apothlure,xf:fml:apotheosis:apothenchaffix,xf:fml:apotheosis:apothenchdata,pl:mixin:A}
27.03 21:15:48 [Server] INFO at net.minecraft.enchantment.EnchantmentHelper.func_151384_a(EnchantmentHelper.java:144) ~[?:?] {re:mixin,re:classloading,xf:fml:astralsorcery:add_enchantment_helper_levels,xf:fml:astralsorcery:add_enchantment_helper_enchantments,xf:fml:astralsorcery:add_enchantment_helper_apply_modifier,xf:fml:apotheosis:apothaffixprot,xf:fml:apotheosis:apothaffixdmg,xf:fml:apotheosis:apothlure,xf:fml:apotheosis:apothlure,xf:fml:apotheosis:apothenchaffix,xf:fml:apotheosis:apothenchdata,pl:mixin:A}
27.03 21:15:48 [Server] INFO at net.minecraft.entity.player.PlayerEntity.func_71059_n(PlayerEntity.java:1152) ~[?:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:caelus.mixins.json:PlayerEntityMixin,pl:mixin:APP:balancedenchanting.mixins.json:PlayerEntityMixin,pl:mixin:APP:assets/botania/botania.mixins.json:MixinPlayerEntity,pl:mixin:A,pl:runtimedistcleaner:A}
27.03 21:15:48 [Server] INFO at net.minecraft.entity.player.ServerPlayerEntity.func_71059_n(ServerPlayerEntity.java:1292) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
27.03 21:15:48 [Server] INFO at mob_grinding_utils.tile.TileEntitySaw.activateBlock(TileEntitySaw.java:101) ~[mob_grinding_utils:1.16.5-0.4.2] {re:classloading}
27.03 21:15:48 [Server] INFO at mob_grinding_utils.tile.TileEntitySaw.func_73660_a(TileEntitySaw.java:66) ~[mob_grinding_utils:1.16.5-0.4.2] {re:classloading}
27.03 21:15:48 [Server] INFO at net.minecraft.world.World.func_217391_K(World.java:491) ~[?:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,xf:fml:astralsorcery:sun_brightness_server,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,xf:fml:astralsorcery:sun_brightness_server,pl:runtimedistcleaner:A}
27.03 21:15:48 [Server] INFO at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:371) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
27.03 21:15:48 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
27.03 21:15:48 [Server] INFO ... 5 more

**Comment by oly2o6** [comment]
this should be reported to the mod authors and not us directly
